-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\barrio_camera\barrio_camera.cts
-- Level:D:\projects\blingbling\data\cutscenes\barrio_camera\barrio_camera.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
end

function shot1()
	fade_in(0.5)
	letterbox_fade_in(true)
	delay(59.4333)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	letterbox_fade_out(true)
	fade_out(0.5)
end
