---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: chopshop_chinatown
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk12", true )
	load_chunks("sr_chunk12_chop", "sr_chunk12")
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
end

function shot1()
	local excluded_lights_1 = {"BB FreeSpot01", "BB FreeSpot02", "BB FreeSpot05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni11", "BB Omni12", "BB Player Key Shot 8 Omni13", "BB Player Rim Shot 8 Omni14"}
	light_set_lights(excluded_lights_1, 10, false)

	local included_lights_1 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "BB Omni05", "BB Omni09", "BB Omni10", "BB Dennis Omni13"}
	light_set_lights(included_lights_1, 8, true)

	fade_in(0.5)
	select_slate("slate_chpshp_ct_01")
	character_show("#PLAYER#")
	teleport_to_slate_pos("#PLAYER#", 0.342, -0.076, -5.589, "slate_chpshp_ct_01")
	play_custom_action_do("#PLAYER#", "chopshop_chinatown_player_1")
	teleport_to_slate_pos("CS_dennis", -3.553, -0.001, -3.357, "slate_chpshp_ct_01")
	play_custom_action_do("CS_dennis", "chopshop_chinatown_dennis_1")
	set_human_cutscene_weapon("cellphone1", "CS_dennis")
	set_level_lights(false)
end

function shot2()
	local excluded_lights_2 = {"BB FreeSpot02", "BB FreeSpot05", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni12", "BB Player Key Shot 8 Omni13", "BB Player Rim Shot 8 Omni14"}
	light_set_lights(excluded_lights_2, 9, false)

	local included_lights_2 = {"BB FreeSpot01", "BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "BB Omni08", "BB Omni09", "BB Omni10", "BB Dennis Omni13"}
	light_set_lights(included_lights_2, 9, true)

	teleport_to_slate_pos("#PLAYER#", 0.38, -0.073, -6.213, "slate_chpshp_ct_01")
	play_custom_action_do("#PLAYER#", "chopshop_chinatown_player_2")
	teleport_to_slate_pos("CS_dennis", -3.478, 0.0, -4.031, "slate_chpshp_ct_01")
	play_custom_action_do("CS_dennis", "chopshop_chinatown_dennis_2")
end

function shot3()
	local excluded_lights_3 = {"BB FreeSpot01", "BB FreeSpot02", "BB FreeSpot05", "BB Omni03", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni11", "BB Player Key Shot 8 Omni13", "BB Player Rim Shot 8 Omni14"}
	light_set_lights(excluded_lights_3, 10, false)

	local included_lights_3 = {"BB Omni01", "BB Omni02", "BB Omni04", "BB Omni08", "BB Omni09", "BB Omni10", "BB Omni12", "BB Dennis Omni13"}
	light_set_lights(included_lights_3, 8, true)

	teleport_to_slate_pos("#PLAYER#", 0.342, -0.075, -5.591, "slate_chpshp_ct_01")
	play_custom_action_do("#PLAYER#", "chopshop_chinatown_player_3")
	teleport_to_slate_pos("CS_dennis", -2.36, 0.007, -4.983, "slate_chpshp_ct_01")
	play_custom_action_do("CS_dennis", "chopshop_chinatown_dennis_3")
end

function shot4()
	local excluded_lights_4 = {"BB Omni01", "BB FreeSpot02", "BB Omni03", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni11", "BB Omni12", "BB Player Key Shot 8 Omni13", "BB Player Rim Shot 8 Omni14"}
	light_set_lights(excluded_lights_4, 11, false)

	local included_lights_4 = {"BB FreeSpot01", "BB FreeSpot05", "BB Omni02", "BB Omni04", "BB Omni09", "BB Omni10", "BB Dennis Omni13"}
	light_set_lights(included_lights_4, 7, true)

	teleport_to_slate_pos("#PLAYER#", 0.343, -0.076, -5.589, "slate_chpshp_ct_01")
	play_custom_action_do("#PLAYER#", "chopshop_chinatown_player_4")
	teleport_to_slate_pos("CS_dennis", -2.462, 0.001, -3.801, "slate_chpshp_ct_01")
	play_custom_action_do("CS_dennis", "chopshop_chinatown_dennis_4")
end

function shot5()
	local excluded_lights_5 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni02", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Player Key Shot 8 Omni13", "BB Player Rim Shot 8 Omni14"}
	light_set_lights(excluded_lights_5, 9, false)

	local included_lights_5 = {"BB Omni01", "BB FreeSpot05", "BB Omni04", "BB Omni05", "BB Omni08", "BB Omni09", "BB Omni10", "BB Omni12", "BB Dennis Omni13"}
	light_set_lights(included_lights_5, 9, true)

	teleport_to_slate_pos("#PLAYER#", 0.343, -0.075, -5.588, "slate_chpshp_ct_01")
	play_custom_action_do("#PLAYER#", "chopshop_chinatown_player_5")
	teleport_to_slate_pos("CS_dennis", -2.478, 0.0, -3.813, "slate_chpshp_ct_01")
	play_custom_action_do("CS_dennis", "chopshop_chinatown_dennis_5")
end

function shot6()
	local excluded_lights_6 = {"BB FreeSpot05", "BB Omni03", "BB Omni04", "BB Omni05", "BB Omni09", "BB Player Key Shot 8 Omni13", "BB Player Rim Shot 8 Omni14"}
	light_set_lights(excluded_lights_6, 7, false)

	local included_lights_6 = {"BB FreeSpot01", "BB Omni01", "BB FreeSpot02", "BB Omni02", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni10", "BB Omni11", "BB Omni12", "BB Dennis Omni13"}
	light_set_lights(included_lights_6, 11, true)

	teleport_to_slate_pos("#PLAYER#", 0.394, -0.057, -5.262, "slate_chpshp_ct_01")
	play_custom_action_do("#PLAYER#", "chopshop_chinatown_player_6")
	teleport_to_slate_pos("CS_dennis", -2.101, 0.009, -4.035, "slate_chpshp_ct_01")
	play_custom_action_do("CS_dennis", "chopshop_chinatown_dennis_6")
end

function shot7()
	local excluded_lights_7 = {"BB FreeSpot01", "BB Omni01", "BB FreeSpot02", "BB FreeSpot05", "BB Omni02", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Player Key Shot 8 Omni13", "BB Player Rim Shot 8 Omni14"}
	light_set_lights(excluded_lights_7, 11, false)

	local included_lights_7 = {"BB Omni03", "BB Omni04", "BB Omni09", "BB Omni10", "BB Omni11", "BB Omni12", "BB Dennis Omni13"}
	light_set_lights(included_lights_7, 7, true)

	teleport_to_slate_pos("#PLAYER#", -0.913, -0.066, -4.458, "slate_chpshp_ct_01")
	play_custom_action_do("#PLAYER#", "chopshop_chinatown_player_7")
	teleport_to_slate_pos("CS_dennis", -1.546, 0.009, -4.093, "slate_chpshp_ct_01")
	play_custom_action_do("CS_dennis", "chopshop_chinatown_dennis_7")
end

function shot8()
	local excluded_lights_8 = {"BB Omni01", "BB FreeSpot05", "BB Omni02", "BB Omni03", "BB Omni04", "BB Omni05", "BB Omni06", "BB Omni09", "BB Omni11", "BB Omni12", "BB Dennis Omni13"}
	light_set_lights(excluded_lights_8, 11, false)

	local included_lights_8 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni07", "BB Omni08", "BB Omni10", "BB Player Key Shot 8 Omni13", "BB Player Rim Shot 8 Omni14"}
	light_set_lights(included_lights_8, 7, true)

	teleport_to_slate_pos("#PLAYER#", -0.91, -0.066, -4.457, "slate_chpshp_ct_01")
	play_custom_action_do("#PLAYER#", "chopshop_chinatown_player_8")
	teleport_to_slate_pos("CS_dennis", -1.559, 0.009, -4.08, "slate_chpshp_ct_01")
	play_custom_action_do("CS_dennis", "chopshop_chinatown_dennis_8")
end

function shot9()
	local excluded_lights_9 = {"BB FreeSpot01", "BB Omni01", "BB FreeSpot02", "BB FreeSpot05", "BB Omni02", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Player Key Shot 8 Omni13", "BB Player Rim Shot 8 Omni14"}
	light_set_lights(excluded_lights_9, 11, false)

	local included_lights_9 = {"BB Omni03", "BB Omni04", "BB Omni09", "BB Omni10", "BB Omni11", "BB Omni12", "BB Dennis Omni13"}
	light_set_lights(included_lights_9, 7, true)

	teleport_to_slate_pos("#PLAYER#", -0.908, -0.067, -4.46, "slate_chpshp_ct_01")
	play_custom_action_do("#PLAYER#", "chopshop_chinatown_player_9")
	teleport_to_slate_pos("CS_dennis", -1.555, 0.009, -4.082, "slate_chpshp_ct_01")
	play_custom_action_do("CS_dennis", "chopshop_chinatown_dennis_9")
	delay(3.9)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
end

function cutscene_end()
	character_show("#PLAYER#")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_dennis")
	letterbox_fade_out(true)
	fade_out(0.5)
end
