-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\drugtraffic_factory\drugtraffic_factory.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk17__FAground.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	load_chunk("sr_chunk17", true )
	select_slate("slate_drug_factory")
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function shot8()
end

function shot9()
end

function cutscene_abort()
end

function cutscene_end()
end
