-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\drugtraffic_factory\drugtraffic_factory.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk17__FAground.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
end

function shot1()
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("CS_billy", 0.580121, 0.0, 1.40348, "slate_drug_factory")
	play_custom_action_do("CS_billy", "drugtraffic_factory_b_1")
	teleport_to_slate_pos("#PLAYER#", 1.60384, 0.0, -3.63227, "slate_drug_factory")
	play_custom_action_do("#PLAYER#", "drugtraffic_factory_player_1")
	teleport_to_slate_pos("CS_tobias", 1.29915, 0.0, 1.91576, "slate_drug_factory")
	play_custom_action_do("CS_tobias", "drugtraffic_factory_tobias_1")
end

function shot2()
	teleport_to_slate_pos("CS_billy", 0.189571, 0.0, 1.16589, "slate_drug_factory")
	play_custom_action_do("CS_billy", "drugtraffic_factory_b_2")
	teleport_to_slate_pos("#PLAYER#", 1.60362, 0.0, -3.63401, "slate_drug_factory")
	play_custom_action_do("#PLAYER#", "drugtraffic_factory_player_2")
	teleport_to_slate_pos("CS_tobias", 1.36701, 0.0, 1.94432, "slate_drug_factory")
	play_custom_action_do("CS_tobias", "drugtraffic_factory_tobias_2")
end

function shot3()
	teleport_to_slate_pos("CS_billy", 0.184172, 0.0, 1.17187, "slate_drug_factory")
	play_custom_action_do("CS_billy", "drugtraffic_factory_b_3")
	teleport_to_slate_pos("#PLAYER#", 1.6034, 0.0, -3.63582, "slate_drug_factory")
	play_custom_action_do("#PLAYER#", "drugtraffic_factory_player_3")
	teleport_to_slate_pos("CS_tobias", 1.40026, 0.0, 1.96333, "slate_drug_factory")
	play_custom_action_do("CS_tobias", "drugtraffic_factory_tobias_3")
end

function shot4()
	teleport_to_slate_pos("CS_billy", 0.18352, 0.0, 1.17554, "slate_drug_factory")
	play_custom_action_do("CS_billy", "drugtraffic_factory_b_4")
	teleport_to_slate_pos("#PLAYER#", 1.60329, 0.0, -3.63668, "slate_drug_factory")
	play_custom_action_do("#PLAYER#", "drugtraffic_factory_player_4")
	teleport_to_slate_pos("CS_tobias", 1.40722, 0.0, 1.95793, "slate_drug_factory")
	play_custom_action_do("CS_tobias", "drugtraffic_factory_tobias_4")
end

function shot5()
	teleport_to_slate_pos("CS_billy", 0.180964, 0.0, 1.17524, "slate_drug_factory")
	play_custom_action_do("CS_billy", "drugtraffic_factory_b_5")
	teleport_to_slate_pos("#PLAYER#", 1.60957, 0.0, -2.99454, "slate_drug_factory")
	play_custom_action_do("#PLAYER#", "drugtraffic_factory_player_5")
	teleport_to_slate_pos("CS_tobias", 1.36105, 0.0, 1.94826, "slate_drug_factory")
	play_custom_action_do("CS_tobias", "drugtraffic_factory_tobias_5")
end

function shot6()
	teleport_to_slate_pos("CS_billy", 0.180964, 0.0, 1.17524, "slate_drug_factory")
	play_custom_action_do("CS_billy", "drugtraffic_factory_b_6")
	teleport_to_slate_pos("#PLAYER#", 1.30271, 0.0, -0.59424, "slate_drug_factory")
	play_custom_action_do("#PLAYER#", "drugtraffic_factory_player_6")
	teleport_to_slate_pos("CS_tobias", 1.32135, 0.0, 1.7007, "slate_drug_factory")
	play_custom_action_do("CS_tobias", "drugtraffic_factory_tobias_6")
end

function shot7()
	teleport_to_slate_pos("CS_billy", 0.180964, 0.0, 1.17524, "slate_drug_factory")
	play_custom_action_do("CS_billy", "drugtraffic_factory_b_7")
	teleport_to_slate_pos("#PLAYER#", 1.25429, 0.0, -0.339439, "slate_drug_factory")
	play_custom_action_do("#PLAYER#", "drugtraffic_factory_player_7")
	teleport_to_slate_pos("CS_tobias", 1.23216, 0.0, 1.31887, "slate_drug_factory")
	play_custom_action_do("CS_tobias", "drugtraffic_factory_tobias_7")
end

function shot8()
	teleport_to_slate_pos("CS_billy", 0.180964, 0.0, 1.17524, "slate_drug_factory")
	play_custom_action_do("CS_billy", "drugtraffic_factory_b_8")
	teleport_to_slate_pos("#PLAYER#", 1.25794, 0.0, -0.34648, "slate_drug_factory")
	play_custom_action_do("#PLAYER#", "drugtraffic_factory_player_8")
	teleport_to_slate_pos("CS_tobias", 1.26527, 0.0, 1.30628, "slate_drug_factory")
	play_custom_action_do("CS_tobias", "drugtraffic_factory_tobias_8")
end

function shot9()
	teleport_to_slate_pos("CS_billy", 0.180964, 0.0, 1.17524, "slate_drug_factory")
	play_custom_action_do("CS_billy", "drugtraffic_factory_b_9")
	teleport_to_slate_pos("#PLAYER#", 1.33234, 0.0, -0.316062, "slate_drug_factory")
	play_custom_action_do("#PLAYER#", "drugtraffic_factory_player_9")
	teleport_to_slate_pos("CS_tobias", 1.25561, 0.0, 1.28729, "slate_drug_factory")
	play_custom_action_do("CS_tobias", "drugtraffic_factory_tobias_9")
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	stop_custom_actions("CS_billy")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_tobias")
	letterbox_fade_out(true)
	fade_out(0.5)
end
