---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: escort_redlight
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk06", true )
	load_chunks("sr_chunk06_sc", "sr_chunk06")
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
	thread_new_cutscene_shot("shot12", 12)
	thread_new_cutscene_shot("shot13", 13)
	thread_new_cutscene_shot("shot14", 14)
	thread_new_cutscene_shot("shot15", 15)
	thread_new_cutscene_shot("shot16", 16)
	thread_new_cutscene_shot("shot17", 17)
	thread_new_cutscene_shot("shot18", 18)
	thread_new_cutscene_shot("shot19", 19)
	thread_new_cutscene_shot("shot20", 20)
end

function shot1()
	set_level_lights(false)
	fade_in(0.5)
	select_slate("slate_escort_redlight")
	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_bruno", -1.357, -0.064, -0.292, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_1")
	teleport_to_slate_pos("CS_papparazzi", -3.556, 0.0, 0.871, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_1")
	teleport_to_slate_pos("CS_stripper", 2.031, -0.064, -2.677, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_1")
	teleport_to_slate_pos("#PLAYER#", -0.015, -0.064, -2.491, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_1")
	teleport_to_slate_pos("CS_camera", -3.15, 0.0, 0.451, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_1")
	thread_new("scripted_event1", 1)
	thread_new("scripted_event2", 2)
	thread_new("scripted_event3", 3)
	thread_new("scripted_event4", 4)
	thread_new("scripted_event5", 5)
	thread_new("scripted_event6", 6)
	thread_new("scripted_event7", 7)
	thread_new("scripted_event8", 8)
	thread_new("scripted_event9", 9)
	thread_new("scripted_event10", 10)
	thread_new("scripted_event11", 11)
	thread_new("scripted_event12", 12)
end

function shot2()
	teleport_to_slate_pos("CS_bruno", -1.369, -0.064, -0.294, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_2")
	teleport_to_slate_pos("CS_papparazzi", -2.422, 0.0, -0.34, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_2")
	teleport_to_slate_pos("CS_stripper", 1.927, -0.073, -2.624, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_2")
	teleport_to_slate_pos("#PLAYER#", -0.006, -0.064, -2.468, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_2")
	teleport_to_slate_pos("CS_camera", -1.971, 0.0, -0.79, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_2")
end

function shot3()
	teleport_to_slate_pos("CS_bruno", -1.372, -0.064, -0.291, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_3")
	teleport_to_slate_pos("CS_papparazzi", -2.415, 0.0, -0.345, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_3")
	teleport_to_slate_pos("CS_stripper", 0.624, -0.067, -2.397, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_3")
	teleport_to_slate_pos("#PLAYER#", 0.09, -0.064, -2.483, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_3")
	teleport_to_slate_pos("CS_camera", -1.943, 0.0, -0.797, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_3")
	play_action_sequence("CS_stand02", "angry stand")
end

function shot4()
	teleport_to_slate_pos("CS_bruno", -1.359, -0.064, -0.306, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_4")
	teleport_to_slate_pos("CS_papparazzi", -2.404, 0.0, -0.377, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_4")
	teleport_to_slate_pos("CS_stripper", 0.668, -0.069, -2.428, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_4")
	teleport_to_slate_pos("#PLAYER#", 0.157, -0.064, -2.509, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_4")
	teleport_to_slate_pos("CS_camera", -1.927, 0.0, -0.818, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_4")
end

function shot5()
	teleport_to_slate_pos("CS_bruno", -1.518, -0.064, -0.621, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_5")
	teleport_to_slate_pos("CS_papparazzi", -2.296, -0.064, -0.554, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_5")
	teleport_to_slate_pos("CS_stripper", 0.555, -0.066, -2.289, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_5")
	teleport_to_slate_pos("#PLAYER#", 0.096, -0.064, -2.49, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_5")
	teleport_to_slate_pos("CS_camera", -1.911, 0.0, -0.821, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_5")
end

function shot6()
	teleport_to_slate_pos("CS_bruno", -1.149, -0.064, -0.406, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_6")
	teleport_to_slate_pos("CS_papparazzi", -1.795, -0.064, -0.859, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_6")
	teleport_to_slate_pos("CS_stripper", 0.639, -0.065, -2.374, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_6")
	teleport_to_slate_pos("#PLAYER#", 0.145, -0.064, -2.494, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_6")
	teleport_to_slate_pos("CS_camera", -0.943, 0.0, -0.713, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_6")
end

function shot7()
	teleport_to_slate_pos("CS_bruno", -0.709, -0.064, -0.622, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_7")
	teleport_to_slate_pos("CS_papparazzi", 0.354, -0.064, -1.921, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_7")
	teleport_to_slate_pos("CS_stripper", 0.748, -0.063, -2.523, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_7")
	teleport_to_slate_pos("#PLAYER#", 0.137, -0.064, -2.669, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_7")
	teleport_to_slate_pos("CS_camera", -0.358, 0.0, -0.453, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_7")
end

function shot8()
	teleport_to_slate_pos("CS_bruno", -0.256, -0.064, -1.343, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_8")
	teleport_to_slate_pos("CS_papparazzi", 0.283, -0.064, -1.979, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_8")
	teleport_to_slate_pos("CS_stripper", 0.749, -0.062, -2.457, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_8")
	teleport_to_slate_pos("#PLAYER#", 0.264, -0.064, -2.774, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_8")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_8")
end

function shot9()
	teleport_to_slate_pos("CS_bruno", -0.356, -0.064, -1.411, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_9")
	teleport_to_slate_pos("CS_papparazzi", 0.11, -0.064, -1.795, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_9")
	teleport_to_slate_pos("CS_stripper", 0.799, -0.069, -2.397, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_9")
	teleport_to_slate_pos("#PLAYER#", 0.367, -0.064, -2.797, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_9")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_9")
end

function shot10()
	teleport_to_slate_pos("CS_bruno", -0.412, -0.064, -1.413, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_10")
	teleport_to_slate_pos("CS_papparazzi", 0.111, 0.0, -1.834, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_10")
	teleport_to_slate_pos("CS_stripper", 0.813, -0.07, -2.569, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_10")
	teleport_to_slate_pos("#PLAYER#", 0.37, -0.064, -2.799, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_10")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_10")
end

function shot11()
	teleport_to_slate_pos("CS_bruno", -0.594, -0.064, -1.707, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_11")
	teleport_to_slate_pos("CS_papparazzi", 0.182, -0.064, -1.912, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_11")
	teleport_to_slate_pos("CS_stripper", 0.726, -0.067, -2.554, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_11")
	teleport_to_slate_pos("#PLAYER#", 0.385, -0.064, -2.978, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_11")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_11")
end

function shot12()
	teleport_to_slate_pos("CS_bruno", -1.16, -0.064, -2.491, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_12")
	teleport_to_slate_pos("CS_papparazzi", -2.648, -0.064, -4.246, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_12")
	teleport_to_slate_pos("CS_stripper", 0.776, -0.06, -2.485, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_12")
	teleport_to_slate_pos("#PLAYER#", 0.35, -0.064, -2.854, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_12")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_12")
end

function shot13()
	teleport_to_slate_pos("CS_bruno", -1.181, -0.064, -1.98, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_13")
	teleport_to_slate_pos("CS_papparazzi", -2.723, 0.0, -4.137, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_13")
	teleport_to_slate_pos("CS_stripper", 0.741, -0.046, -2.487, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_13")
	teleport_to_slate_pos("#PLAYER#", 0.176, -0.064, -2.896, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_13")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_13")
end

function shot14()
	teleport_to_slate_pos("CS_bruno", -1.0, -0.064, -1.585, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_14")
	teleport_to_slate_pos("CS_papparazzi", -1.167, 0.0, -3.321, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_14")
	teleport_to_slate_pos("CS_stripper", 0.738, -0.04, -2.493, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_14")
	teleport_to_slate_pos("#PLAYER#", -0.344, -0.064, -2.944, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_14")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_14")
end

function shot15()
	teleport_to_slate_pos("CS_bruno", -0.755, -0.064, -1.347, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_15")
	teleport_to_slate_pos("CS_papparazzi", -1.689, -0.064, -3.808, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_15")
	teleport_to_slate_pos("CS_stripper", 0.709, -0.035, -2.461, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_15")
	teleport_to_slate_pos("#PLAYER#", -0.543, -0.064, -2.924, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_15")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_15")
end

function shot16()
	teleport_to_slate_pos("CS_bruno", -0.726, -0.064, -1.8, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_16")
	teleport_to_slate_pos("CS_papparazzi", -2.585, -0.064, -4.366, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_16")
	teleport_to_slate_pos("CS_stripper", 0.231, -0.054, -2.285, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_16")
	teleport_to_slate_pos("#PLAYER#", -0.022, -0.064, -2.914, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_16")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_16")
end

function shot17()
	teleport_to_slate_pos("CS_bruno", -0.651, -0.064, -1.953, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_17")
	teleport_to_slate_pos("CS_papparazzi", -2.57, 0.0, -4.377, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_17")
	teleport_to_slate_pos("CS_stripper", 0.463, -0.064, -2.708, "slate_escort_redlight")
	play_custom_action_do("CS_stripper", "escort_redlight_s01_17")
	teleport_to_slate_pos("#PLAYER#", -0.022, -0.064, -2.888, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_17")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_17")
end

function shot18()
	teleport_to_slate_pos("CS_bruno", -0.645, -0.064, -1.966, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_18")
	teleport_to_slate_pos("CS_papparazzi", -2.57, -0.064, -4.376, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_18")
	teleport_to_slate_pos("#PLAYER#", -0.031, -0.064, -2.875, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_18")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_18")
end

function shot19()
	teleport_to_slate_pos("CS_bruno", -0.54, -0.064, -1.957, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_19")
	teleport_to_slate_pos("CS_papparazzi", -2.57, 0.0, -4.377, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_19")
	teleport_to_slate_pos("#PLAYER#", -0.017, -0.064, -2.886, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_19")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_19")
end

function shot20()
	teleport_to_slate_pos("CS_bruno", -0.531, -0.064, -1.983, "slate_escort_redlight")
	play_custom_action_do("CS_bruno", "escort_redlight_b01_20")
	teleport_to_slate_pos("CS_papparazzi", -2.57, -0.064, -4.377, "slate_escort_redlight")
	play_custom_action_do("CS_papparazzi", "escort_redlight_pr01_20")
	teleport_to_slate_pos("#PLAYER#", -0.028, -0.064, -2.901, "slate_escort_redlight")
	play_custom_action_do("#PLAYER#", "escort_redlight_p01_20")
	teleport_to_slate_pos("CS_camera", 0.266, 0.0, -0.995, "slate_escort_redlight")
	play_custom_action_do("CS_camera", "escort_redlight_cam_20")
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	stop_custom_actions("CS_bruno")
	stop_custom_actions("CS_papparazzi")
	stop_custom_actions("CS_stripper")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_camera")
	letterbox_fade_out(true)
	fade_out(0.5)
end

function scripted_event1()
	teleport("CS_strip01", "CS_CharNav_strip01_1")
	play_action_sequence("CS_strip01", "dance a")
end

function scripted_event2()
	teleport("CS_talker01", "CS_CharNav_talker01_1")
	play_action_sequence("CS_talker01", "dance a")
end

function scripted_event3()
	teleport("CS_talker02", "CS_CharNav_talker02_1")
	play_action_sequence("CS_talker02", "dance a")
end

function scripted_event4()
	teleport("CS_stand01", "CS_CharNav_stand01_1")
	play_action_sequence("CS_stand01", "stand")
end

function scripted_event5()
	teleport("CS_stand02", "CS_CharNav_stand02_1")
	play_action_sequence("CS_stand02", "stand")
end

function scripted_event6()
	teleport("CS_strip02", "CS_CharNav_strip02_1")
	play_action_sequence("CS_strip02", "dance b")
end

function scripted_event7()
	teleport("CS_bar01", "CS_CharNav_bar01_1")
	play_action_sequence("CS_bar01", "drunk stand")
end

function scripted_event8()
	teleport("CS_stand03", "CS_CharNav_stand03_1")
	play_action_sequence("CS_stand03", "drunk stand")
end

function scripted_event9()
	teleport("CS_sit01", "CS_CharNav_sit01_1")
	play_action_sequence("CS_sit01", "sitting")
end

function scripted_event10()
	teleport("CS_sit02", "CS_CharNav_sit02_1")
	play_action_sequence("CS_sit02", "sitting")
end

function scripted_event11()
	teleport("CS_talker03", "CS_CharNav_talker03_1")
	play_action_sequence("CS_talker03", "dance a")
end

function scripted_event12()
	teleport("CS_talker04", "CS_CharNav_talker04_1")
	play_action_sequence("CS_talker04", "dance a")
end
