-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\escort_airport\escort_airport.cts
-- Level:D:\projects\blingbling\data\test\cutscene_escort_airport.cts
-------------------------------------


function cutscene_main()
	load_chunk("sr_chunk14", true )
	load_chunks("sr_chunk14_sc", "sr_chunk14")
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function shot8()
end

function shot9()
end

function cutscene_abort()
end

function cutscene_end()
end
