-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\hijacking_highend\hijacking_highend.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk30b__interiors.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	load_chunk("sr_chunk30b", true )
	select_slate("slate_hijacking")
	audio_play("CS Hijacking Highend", "voice", true)
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function cutscene_abort()
end

function cutscene_end()
end
