---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: hijacking_highend
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk30b", true )
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
end

function shot1()
	fade_in(0.5)
	select_slate("slate_hijacking")
	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_sam", -0.835, 0.0, -1.039, "slate_hijacking")
	play_custom_action_do("CS_sam", "hijacking_highend_sam_1")
	teleport_to_slate_pos("#PLAYER#", 2.238, 0.0, 0.757, "slate_hijacking")
	play_custom_action_do("#PLAYER#", "hijacking_highend_player_1")
	set_far_clip(100)
	time_of_day_character_shadows_enable(false)
	spawning_peds(false)
	spawning_cars(false)
	set_level_lights(false)
end

function shot2()
	teleport_to_slate_pos("CS_sam", -0.838, 0.0, -1.044, "slate_hijacking")
	play_custom_action_do("CS_sam", "hijacking_highend_sam_2")
	teleport_to_slate_pos("#PLAYER#", -0.54, 0.0, -0.069, "slate_hijacking")
	play_custom_action_do("#PLAYER#", "hijacking_highend_player_2")
end

function shot3()
	teleport_to_slate_pos("CS_sam", -0.773, 0.0, -1.02, "slate_hijacking")
	play_custom_action_do("CS_sam", "hijacking_highend_sam_3")
	teleport_to_slate_pos("#PLAYER#", -0.937, 0.0, 0.092, "slate_hijacking")
	play_custom_action_do("#PLAYER#", "hijacking_highend_player_3")
end

function shot4()
	teleport_to_slate_pos("CS_sam", -0.97, 0.0, -1.005, "slate_hijacking")
	play_custom_action_do("CS_sam", "hijacking_highend_sam_4")
	teleport_to_slate_pos("#PLAYER#", -0.922, 0.0, 0.045, "slate_hijacking")
	play_custom_action_do("#PLAYER#", "hijacking_highend_player_4")
end

function shot5()
	teleport_to_slate_pos("CS_sam", -0.909, 0.0, -1.023, "slate_hijacking")
	play_custom_action_do("CS_sam", "hijacking_highend_sam_5")
	teleport_to_slate_pos("#PLAYER#", -1.055, 0.0, 0.093, "slate_hijacking")
	play_custom_action_do("#PLAYER#", "hijacking_highend_player_5")
	delay(4.66667)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
	time_of_day_character_shadows_enable(true)
	set_far_clip(4000)
	spawning_peds(true)
	spawning_cars(true)
end

function cutscene_end()
	character_show("#PLAYER#")
	stop_custom_actions("CS_sam")
	stop_custom_actions("#PLAYER#")
	letterbox_fade_out(true)
	fade_out(0.5)
	time_of_day_character_shadows_enable(true)
	set_far_clip(4000)
	spawning_peds(true)
	spawning_cars(true)
end
