---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: hitman_sunnyvale
-- Exported By: Ding.Ye
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk07_bar", true )
	load_chunks("sr_chunk07", "sr_chunk07_bar")
	time_of_day_lights_enable(false)
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
end

function shot1()
	fade_in(0.5)
	select_slate("slate_hitman_sunnyvale")
	character_show("#PLAYER#")
	teleport_to_slate_pos("#PLAYER#", 1.344, 0.0, 1.23, "slate_hitman_sunnyvale")
	play_custom_action_do("#PLAYER#", "hitman_sunnyvale_pc_1")
	teleport_to_slate_pos("CS_marcel", -0.552, 0.0, 1.775, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_marcel", "hitman_sunnyvale_mar_1")
	teleport_to_slate_pos("CS_beer", -0.207, 0.0, 1.607, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_beer", "hitman_sunnyvale_br_1")
	teleport_to_slate_pos("CS_photo", 0.179, 0.0, 1.91, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_photo", "hitman_sunnyvale_photo_1")
	set_level_lights(false)
end

function shot2()
	teleport_to_slate_pos("#PLAYER#", 1.181, 0.0, 1.776, "slate_hitman_sunnyvale")
	play_custom_action_do("#PLAYER#", "hitman_sunnyvale_pc_2")
	teleport_to_slate_pos("CS_marcel", -0.552, 0.0, 1.775, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_marcel", "hitman_sunnyvale_mar_2")
	teleport_to_slate_pos("CS_beer", -0.207, 0.0, 1.607, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_beer", "hitman_sunnyvale_br_2")
	teleport_to_slate_pos("CS_photo", 0.179, 0.0, 1.91, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_photo", "hitman_sunnyvale_photo_2")
end

function shot3()
	teleport_to_slate_pos("#PLAYER#", 1.181, 0.0, 1.776, "slate_hitman_sunnyvale")
	play_custom_action_do("#PLAYER#", "hitman_sunnyvale_pc_3")
	teleport_to_slate_pos("CS_marcel", -0.552, 0.0, 1.775, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_marcel", "hitman_sunnyvale_mar_3")
	teleport_to_slate_pos("CS_beer", -0.207, 0.0, 1.607, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_beer", "hitman_sunnyvale_br_3")
	teleport_to_slate_pos("CS_photo", 0.179, 0.0, 1.91, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_photo", "hitman_sunnyvale_photo_3")
end

function shot4()
	teleport_to_slate_pos("#PLAYER#", 1.181, 0.0, 1.776, "slate_hitman_sunnyvale")
	play_custom_action_do("#PLAYER#", "hitman_sunnyvale_pc_4")
	teleport_to_slate_pos("CS_marcel", -0.552, 0.0, 1.775, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_marcel", "hitman_sunnyvale_mar_4")
	teleport_to_slate_pos("CS_beer", -0.207, 0.0, 1.607, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_beer", "hitman_sunnyvale_br_4")
	teleport_to_slate_pos("CS_photo", 0.179, 0.0, 1.91, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_photo", "hitman_sunnyvale_photo_4")
end

function shot5()
	teleport_to_slate_pos("#PLAYER#", 1.181, 0.0, 1.776, "slate_hitman_sunnyvale")
	play_custom_action_do("#PLAYER#", "hitman_sunnyvale_pc_5")
	teleport_to_slate_pos("CS_marcel", -0.552, 0.0, 1.775, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_marcel", "hitman_sunnyvale_mar_5")
	teleport_to_slate_pos("CS_beer", -0.207, 0.0, 1.607, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_beer", "hitman_sunnyvale_br_5")
	teleport_to_slate_pos("CS_photo", 0.179, 0.0, 1.91, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_photo", "hitman_sunnyvale_photo_5")
end

function shot6()
	teleport_to_slate_pos("#PLAYER#", 1.181, 0.0, 1.776, "slate_hitman_sunnyvale")
	play_custom_action_do("#PLAYER#", "hitman_sunnyvale_pc_6")
	teleport_to_slate_pos("CS_marcel", -0.552, 0.0, 1.775, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_marcel", "hitman_sunnyvale_mar_6")
	teleport_to_slate_pos("CS_beer", -0.207, 0.0, 1.607, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_beer", "hitman_sunnyvale_br_6")
	teleport_to_slate_pos("CS_photo", 0.179, 0.0, 1.91, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_photo", "hitman_sunnyvale_photo_6")
end

function shot7()
	teleport_to_slate_pos("#PLAYER#", 1.181, 0.0, 1.776, "slate_hitman_sunnyvale")
	play_custom_action_do("#PLAYER#", "hitman_sunnyvale_pc_7")
	teleport_to_slate_pos("CS_marcel", -0.552, 0.0, 1.775, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_marcel", "hitman_sunnyvale_mar_7")
	teleport_to_slate_pos("CS_beer", -0.207, 0.0, 1.607, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_beer", "hitman_sunnyvale_br_7")
	teleport_to_slate_pos("CS_photo", 0.179, 0.0, 1.91, "slate_hitman_sunnyvale")
	play_custom_action_do("CS_photo", "hitman_sunnyvale_photo_7")
	delay(1.63333)
	fade_out(0.5)
end

function cutscene_abort()
	time_of_day_lights_enable(true)
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
end

function cutscene_end()
	time_of_day_lights_enable(true)
	character_show("#PLAYER#")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_marcel")
	stop_custom_actions("CS_beer")
	stop_custom_actions("CS_photo")
	letterbox_fade_out(true)
	fade_out(0.5)
end
