-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\hitman_sunnyvale\hitman_sunnyvale.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk07_bar__interiors.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	load_chunk("sr_chunk07_bar", true )
	select_slate("slate_hitman_sunnyvale")
	audio_play("CS Hitman Sunnyvale", "voice", true)
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function cutscene_abort()
end

function cutscene_end()
end
