---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: insurance_chinatown
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk12_lo", true)
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
end

function shot1()
	fade_in(0.5)
	select_slate("slate_ins_china")
	teleport_to_slate_pos("CS_seth", -5.396, 0.069, -1.303, "slate_ins_china")
	play_custom_action_do("CS_seth", "insurance_chinatown_seth_1")
	teleport_to_slate_pos("#PLAYER#", -3.359, 0.065, -0.995, "slate_ins_china")
	play_custom_action_do("#PLAYER#", "insurance_chinatown_player_1")
	teleport_to_slate_pos("CS_chair", -5.153, 0.0, -0.679, "slate_ins_china")
	play_custom_action_do("CS_chair", "insurance_chinatown_chair_1")
	set_level_lights(false)
end

function shot2()
	character_hide("CS_chair")
	teleport_to_slate_pos("CS_seth", -4.954, 0.084, -1.428, "slate_ins_china")
	play_custom_action_do("CS_seth", "insurance_chinatown_seth_2")
	teleport_to_slate_pos("#PLAYER#", -3.342, 0.068, -0.972, "slate_ins_china")
	play_custom_action_do("#PLAYER#", "insurance_chinatown_player_2")
	teleport_to_slate_pos("CS_chair", -5.153, 0.0, -0.679, "slate_ins_china")
	play_custom_action_do("CS_chair", "insurance_chinatown_chair_2")

end

function shot3()
	character_show("CS_chair")
	teleport_to_slate_pos("CS_seth", -5.017, 0.096, -0.752, "slate_ins_china")
	play_custom_action_do("CS_seth", "insurance_chinatown_seth_3")
	teleport_to_slate_pos("CS_chair", -5.153, 0.0, -0.679, "slate_ins_china")
	play_custom_action_do("CS_chair", "insurance_chinatown_chair_3")
	delay(14.4333)
	fade_out(0.5)

end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	stop_custom_actions("CS_seth")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_chair")
	letterbox_fade_out(true)
	fade_out(0.5)
end
