-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\insurance_downtown\insurance_downtown.cts
-- Level:D:\projects\blingbling\data\test\cutscene_insurance_downtown.cts
-------------------------------------


function cutscene_main()
	load_chunk("sr_chunk35", true)
	load_chunks("sr_chunk35_lo", "sr_chunk35")
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function cutscene_abort()
end

function cutscene_end()
end
