-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc04_tunload\lc04_tunload.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk18__ground.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	load_chunk("sr_chunk18", true )
	select_slate("slate_truck_unload")
	audio_play("LC04 TRUCK UNLOAD", "voice", true)
end

function shot2()
end

function cutscene_abort()
end

function cutscene_end()
end
