-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc04_tunload\lc04_tunload.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk18__ground.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
end

function shot1()
	set_level_lights(false)
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("CS_hthug", -0.0276093, 0.0, -0.0180694, "slate_truck_unload")
	play_custom_action_do("CS_hthug", "lc04_tunload_hthug_1")
	teleport_to_slate_pos("CS_wbthug01", -0.701275, 0.0, 0.914944, "slate_truck_unload")
	play_custom_action_do("CS_wbthug01", "lc04_tunload_wbthug01_1")
	teleport_to_slate_pos("CS_ahthug", -1.47578, 0.0, 0.35122, "slate_truck_unload")
	play_custom_action_do("CS_ahthug", "lc04_tunload_ahthug_1")
	teleport_to_slate_pos("CS_fthug01", -0.113241, 0.0, -0.543872, "slate_truck_unload")
	play_custom_action_do("CS_fthug01", "lc04_tunload_fthug01_1")
	teleport_to_slate_pos("CS_fthug02", -0.225004, 0.0, -0.00399141, "slate_truck_unload")
	play_custom_action_do("CS_fthug02", "lc04_tunload_fthug02_1")
	teleport_to_slate_pos("#PLAYER#", 10.8638, 0.0, 4.62839, "slate_truck_unload")
	play_custom_action_do("#PLAYER#", "lc04_tunload_player_1")
	teleport_to_slate_pos("CS_truck", 12.0754, 0.0, 6.17862, "slate_truck_unload")
	play_custom_action_do("CS_truck", "lc04_tunload_truck_1")
	teleport_to_slate_pos("CS_rthug", -0.46428, 0.0, -0.6828, "slate_truck_unload")
	play_custom_action_do("CS_rthug", "lc04_tunload_rthug_1")
	teleport_to_slate_pos("CS_fem", -1.46967, 0.0, -0.159996, "slate_truck_unload")
	play_custom_action_do("CS_fem", "lc04_tunload_fem_1")
end

function shot2()
	teleport_to_slate_pos("CS_hthug", -0.980124, 0.0, -0.641461, "slate_truck_unload")
	play_custom_action_do("CS_hthug", "lc04_tunload_hthug_2")
	teleport_to_slate_pos("CS_wbthug01", -0.758635, 0.0, 0.989733, "slate_truck_unload")
	play_custom_action_do("CS_wbthug01", "lc04_tunload_wbthug01_2")
	teleport_to_slate_pos("CS_ahthug", -1.60754, 0.0, 0.382572, "slate_truck_unload")
	play_custom_action_do("CS_ahthug", "lc04_tunload_ahthug_2")
	teleport_to_slate_pos("CS_fthug01", -0.133069, 0.0, -0.545592, "slate_truck_unload")
	play_custom_action_do("CS_fthug01", "lc04_tunload_fthug01_2")
	teleport_to_slate_pos("CS_fthug02", -0.231913, 0.0, -0.00415361, "slate_truck_unload")
	play_custom_action_do("CS_fthug02", "lc04_tunload_fthug02_2")
	teleport_to_slate_pos("#PLAYER#", -1.25542, 0.0, 6.0226, "slate_truck_unload")
	play_custom_action_do("#PLAYER#", "lc04_tunload_player_2")
	teleport_to_slate_pos("CS_truck", -0.807767, 0.0, 4.05659, "slate_truck_unload")
	play_custom_action_do("CS_truck", "lc04_tunload_truck_2")
	teleport_to_slate_pos("CS_rthug", -0.496536, 0.0, -0.730093, "slate_truck_unload")
	play_custom_action_do("CS_rthug", "lc04_tunload_rthug_2")
	teleport_to_slate_pos("CS_fem", -1.47061, 0.0, -0.156739, "slate_truck_unload")
	play_custom_action_do("CS_fem", "lc04_tunload_fem_2")
	delay(4)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end

function cutscene_end()
	stop_custom_actions("CS_hthug")
	stop_custom_actions("CS_wbthug01")
	stop_custom_actions("CS_ahthug")
	stop_custom_actions("CS_fthug01")
	stop_custom_actions("CS_fthug02")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_truck")
	stop_custom_actions("CS_rthug")
	stop_custom_actions("CS_fem")
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end
