---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: lc04_tload
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk02", true )
	load_chunks("sr_chunk02_mec", "sr_chunk02")
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
end

function shot1()
	fade_in(0.5)
	select_slate("slate_samsons_garage")
	character_hide("#PLAYER#")
	teleport_to_slate_pos("CS_Runner", 0.998, 0.0, -15.447, "slate_samsons_garage")
	play_custom_action_do("CS_Runner", "lc04_tload_RunnerThug_1")
	teleport_to_slate_pos("CS_HelperThug", 0.721, 0.0, -9.372, "slate_samsons_garage")
	play_custom_action_do("CS_HelperThug", "lc04_tload_HelperThug_1")
	teleport_to_slate_pos("CS_WBThug", 1.419, 0.0, -7.143, "slate_samsons_garage")
	play_custom_action_do("CS_WBThug", "lc04_tload_WBThug_1")
	teleport_to_slate_pos("CS_AHThug", 0.453, 0.0, -7.204, "slate_samsons_garage")
	play_custom_action_do("CS_AHThug", "lc04_tload_AHThug_1")
	teleport_to_slate_pos("CS_FatThug01", 1.906, 0.0, -9.163, "slate_samsons_garage")
	play_custom_action_do("CS_FatThug01", "lc04_tload_FatThug01_1")
	teleport_to_slate_pos("CS_FatThug02", 0.242, 0.0, -8.169, "slate_samsons_garage")
	play_custom_action_do("CS_FatThug02", "lc04_tload_FatThug02_1")
	teleport_to_slate_pos("CS_truck", 0.949, 0.0, -4.533, "slate_samsons_garage")
	play_custom_action_do("CS_truck", "lc04_tload_truck_1")
	teleport_to_slate_pos("CS_WBThugFem", 0.196, 0.0, -9.266, "slate_samsons_garage")
	play_custom_action_do("CS_WBThugFem", "lc04_tload_WBThugFem_1")
end

function shot2()
	teleport_to_slate_pos("CS_Runner", 1.068, 0.0, -9.328, "slate_samsons_garage")
	play_custom_action_do("CS_Runner", "lc04_tload_RunnerThug_2")
	teleport_to_slate_pos("CS_HelperThug", 0.634, 0.0, -6.927, "slate_samsons_garage")
	play_custom_action_do("CS_HelperThug", "lc04_tload_HelperThug_2")
	teleport_to_slate_pos("CS_WBThug", 1.412, 0.0, -4.676, "slate_samsons_garage")
	play_custom_action_do("CS_WBThug", "lc04_tload_WBThug_2")
	teleport_to_slate_pos("CS_AHThug", 0.468, 0.0, -4.726, "slate_samsons_garage")
	play_custom_action_do("CS_AHThug", "lc04_tload_AHThug_2")
	teleport_to_slate_pos("CS_FatThug01", 1.911, 0.0, -6.698, "slate_samsons_garage")
	play_custom_action_do("CS_FatThug01", "lc04_tload_FatThug01_2")
	teleport_to_slate_pos("CS_FatThug02", 0.241, 0.0, -5.696, "slate_samsons_garage")
	play_custom_action_do("CS_FatThug02", "lc04_tload_FatThug02_2")
	teleport_to_slate_pos("CS_truck", 0.949, 0.0, -2.071, "slate_samsons_garage")
	play_custom_action_do("CS_truck", "lc04_tload_truck_2")
	teleport_to_slate_pos("CS_WBThugFem", 0.197, 0.0, -6.805, "slate_samsons_garage")
	play_custom_action_do("CS_WBThugFem", "lc04_tload_WBThugFem_2")
end

function shot3()
	teleport_to_slate_pos("CS_Runner", 1.224, 0.0, 8.101, "slate_samsons_garage")
	play_custom_action_do("CS_Runner", "lc04_tload_RunnerThug_3")
	teleport_to_slate_pos("CS_HelperThug", 0.692, 0.0, 7.432, "slate_samsons_garage")
	play_custom_action_do("CS_HelperThug", "lc04_tload_HelperThug_3")
	teleport_to_slate_pos("CS_WBThug", 1.397, 0.0, 9.618, "slate_samsons_garage")
	play_custom_action_do("CS_WBThug", "lc04_tload_WBThug_3")
	teleport_to_slate_pos("CS_AHThug", 0.452, 0.0, 9.571, "slate_samsons_garage")
	play_custom_action_do("CS_AHThug", "lc04_tload_AHThug_3")
	teleport_to_slate_pos("CS_FatThug01", 1.926, 0.0, 7.599, "slate_samsons_garage")
	play_custom_action_do("CS_FatThug01", "lc04_tload_FatThug01_3")
	teleport_to_slate_pos("CS_FatThug02", 0.238, 0.0, 8.674, "slate_samsons_garage")
	play_custom_action_do("CS_FatThug02", "lc04_tload_FatThug02_3")
	teleport_to_slate_pos("CS_truck", 0.949, 0.0, 12.24, "slate_samsons_garage")
	play_custom_action_do("CS_truck", "lc04_tload_truck_3")
	teleport_to_slate_pos("CS_WBThugFem", 0.221, 0.0, 7.366, "slate_samsons_garage")
	play_custom_action_do("CS_WBThugFem", "lc04_tload_WBThugFem_3")
	delay(3.46667)
	fade_out(0.5)
--NOTE delay should be 3.46
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
end

function cutscene_end()
	character_show("#PLAYER#")
	stop_custom_actions("CS_Runner")
	stop_custom_actions("CS_HelperThug")
	stop_custom_actions("CS_WBThug")
	stop_custom_actions("CS_AHThug")
	stop_custom_actions("CS_FatThug01")
	stop_custom_actions("CS_FatThug02")
	stop_custom_actions("CS_truck")
	stop_custom_actions("CS_WBThugFem")
	letterbox_fade_out(true)
	fade_out(0.5)
end
