-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc05_scene02\lc05_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk21__ground.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	load_chunks("sr_chunk21", "sr_chunk14_lopez")
	select_slate("slate_docks")
	audio_play("LC05_SCENE02", "voice", true)
end

function shot2()
	load_chunk("sr_chunk14_lopez", true )
	select_slate("slate_angelo_bedroom")
end

function shot3()
end

function cutscene_abort()
end

function cutscene_end()
end
