-- /////////////////////////////////////////////////////////////
--                Code generated by LUA Cutscene Editor
--                      Version: 0.2b
--                      Date: 12/14/2005 10:38:21 AM
--                      Author: Ding.Ye
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc05_scene02\lc05_scene02.cts
-- Level:D:\projects\blingbling\data\cutscenes\lc05_scene02\lc05_scene02.cts
-- /////////////////////////////////////////////////////////////

function cutscene_main()
	time_of_day_character_shadows_enable(false)
end

function shot1()
	set_level_lights(false)
	character_hide("#PLAYER#")
	character_hide("CS_stander01")
end

function shot2()
	time_of_day_lights_enable(false)
end

function shot3()
end

function cutscene_abort()
	time_of_day_lights_enable(true)
	character_show("#PLAYER#")
	time_of_day_character_shadows_enable(true)
end

function cutscene_end()
	time_of_day_lights_enable(true)
	character_show("#PLAYER#")
	time_of_day_character_shadows_enable(true)
end

function scripted_event1()
--	teleport("CS_stander01", "CS_CS_CSCharnav-stander01_1")
--	play_action_sequence("CS_stander01", "stand ready")
end

function scripted_event2()
	local stander_navs = {"CS_pathNav-stander02_01_1"}
	move_to("CS_stander02", stander_navs, 1)
end
