-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc05_scene01\lc05_scene01.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk02_gunshop__interiors.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
	thread_new_cutscene_shot("shot12", 12)
	thread_new_cutscene_shot("shot13", 13)
end

function shot1()
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("#PLAYER#", 1.927, 0.0, -0.506807, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_1")
	teleport_to_slate_pos("CS_dex", 3.54215, 0.0, -0.07437, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_1")
	teleport_to_slate_pos("CS_saleslady", 4.80239, 0.0, -0.197303, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_1")
	teleport_to_slate_pos("CS_troy", 3.56771, 0.0, 0.524027, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_1")
end

function shot2()
	teleport_to_slate_pos("#PLAYER#", 1.92701, 0.0, -0.506801, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_2")
	teleport_to_slate_pos("CS_dex", 3.5427, 0.0, -0.190604, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_2")
	teleport_to_slate_pos("CS_saleslady", 4.79399, 0.0, -0.194744, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_2")
	teleport_to_slate_pos("CS_troy", 3.58189, 0.0, 0.538658, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_2")
end

function shot3()
	teleport_to_slate_pos("#PLAYER#", 1.92702, 0.0, -0.506792, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_3")
	teleport_to_slate_pos("CS_dex", 3.5938, 0.0, -0.0543747, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_3")
	teleport_to_slate_pos("CS_saleslady", 4.80232, 0.0, -0.211772, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_3")
	teleport_to_slate_pos("CS_troy", 3.67032, 0.0, 0.60126, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_3")
end

function shot4()
	teleport_to_slate_pos("#PLAYER#", 1.92702, 0.0, -0.506785, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_4")
	teleport_to_slate_pos("CS_dex", 3.53339, 0.0, -0.188067, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_4")
	teleport_to_slate_pos("CS_saleslady", 4.78699, 0.0, -0.273052, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_4")
	teleport_to_slate_pos("CS_troy", 3.68865, 0.0, 0.615114, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_4")
end

function shot5()
	teleport_to_slate_pos("#PLAYER#", 1.92702, 0.0, -0.506787, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_5")
	teleport_to_slate_pos("CS_dex", 3.55202, 0.0, -0.180016, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_5")
	teleport_to_slate_pos("CS_saleslady", 4.75598, 0.0, -0.290989, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_5")
	teleport_to_slate_pos("CS_troy", 3.54402, 0.0, 0.462612, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_5")
end

function shot6()
	teleport_to_slate_pos("#PLAYER#", 1.92701, 0.0, -0.506796, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_6")
	teleport_to_slate_pos("CS_dex", 3.58202, 0.0, -0.0338955, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_6")
	teleport_to_slate_pos("CS_saleslady", 4.79302, 0.0, -0.304608, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_6")
	teleport_to_slate_pos("CS_troy", 3.58401, 0.0, 0.499658, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_6")
end

function shot7()
	teleport_to_slate_pos("#PLAYER#", 2.63765, 0.0, -0.767185, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_7")
	teleport_to_slate_pos("CS_dex", 3.57032, 0.0, -0.165035, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_7")
	teleport_to_slate_pos("CS_saleslady", 4.90223, 0.0, -0.120398, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_7")
	teleport_to_slate_pos("CS_troy", 3.56117, 0.0, 0.479499, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_7")
end

function shot8()
	teleport_to_slate_pos("#PLAYER#", 3.59963, 0.0, -0.965161, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_8")
	teleport_to_slate_pos("CS_dex", 3.41983, 0.0, -0.0998958, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_8")
	teleport_to_slate_pos("CS_saleslady", 6.81265, 0.0, 1.32338, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_8")
	teleport_to_slate_pos("CS_troy", 3.70549, 0.0, 0.475518, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_8")
end

function shot9()
	teleport_to_slate_pos("#PLAYER#", 3.59465, 0.0, -0.991038, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_9")
	teleport_to_slate_pos("CS_dex", 3.41879, 0.0, -0.104263, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_9")
	teleport_to_slate_pos("CS_saleslady", 6.81265, 0.0, 1.32338, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_9")
	teleport_to_slate_pos("CS_troy", 3.71067, 0.0, 0.487589, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_9")
end

function shot10()
	teleport_to_slate_pos("#PLAYER#", 3.60115, 0.0, -0.972867, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_10")
	teleport_to_slate_pos("CS_dex", 3.51918, 0.0, -0.00972453, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_10")
	teleport_to_slate_pos("CS_saleslady", 6.81265, 0.0, 1.32338, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_10")
	teleport_to_slate_pos("CS_troy", 3.69973, 0.0, 0.469847, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_10")
end

function shot11()
	teleport_to_slate_pos("#PLAYER#", 3.58565, 0.0, -0.943419, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_11")
	teleport_to_slate_pos("CS_dex", 3.41968, 0.0, -0.107686, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_11")
	teleport_to_slate_pos("CS_saleslady", 6.81265, 0.0, 1.32338, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_11")
	teleport_to_slate_pos("CS_troy", 3.70962, 0.0, 0.484858, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_11")
end

function shot12()
	teleport_to_slate_pos("#PLAYER#", 3.59596, 0.0, -0.990734, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_12")
	teleport_to_slate_pos("CS_dex", 3.42661, 0.0, -0.105851, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_12")
	teleport_to_slate_pos("CS_saleslady", 6.81265, 0.0, 1.32338, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_12")
	teleport_to_slate_pos("CS_troy", 3.7123, 0.0, 0.459957, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_12")
end

function shot13()
	teleport_to_slate_pos("#PLAYER#", 3.60798, 0.0, -0.944351, "slate_friendlyFire")
	play_custom_action_do("#PLAYER#", "lc05_scene01_player_13")
	teleport_to_slate_pos("CS_dex", 3.41143, 0.0, -0.136705, "slate_friendlyFire")
	play_custom_action_do("CS_dex", "lc05_scene01_dex_13")
	teleport_to_slate_pos("CS_saleslady", 6.81265, 0.0, 1.32338, "slate_friendlyFire")
	play_custom_action_do("CS_saleslady", "lc05_scene01_salesLady_13")
	teleport_to_slate_pos("CS_troy", 3.71355, 0.0, 0.46735, "slate_friendlyFire")
	play_custom_action_do("CS_troy", "lc05_scene01_troy_13")
	delay(4)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_dex")
	stop_custom_actions("CS_saleslady")
	stop_custom_actions("CS_troy")
	letterbox_fade_out(true)
	fade_out(0.5)
end
