-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc07_scene02b\lc07_scene02b.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk14__interiors.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
end

function shot1()
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("CS_luz", 1.25969, -0.900007, -0.318574, "slate_angelo_bedroom")
	play_custom_action_do("CS_luz", "lc07_scene02b_luz_1")
	teleport_to_slate_pos("CS_angelo", 0.547852, -0.899984, -0.297293, "slate_angelo_bedroom")
	play_custom_action_do("CS_angelo", "lc07_scene02b_angelo_1")
end

function shot2()
	teleport_to_slate_pos("CS_luz", 1.2783, -0.900004, -0.405594, "slate_angelo_bedroom")
	play_custom_action_do("CS_luz", "lc07_scene02b_luz_2")
	teleport_to_slate_pos("CS_angelo", 0.541204, -0.899985, -0.297235, "slate_angelo_bedroom")
	play_custom_action_do("CS_angelo", "lc07_scene02b_angelo_2")
end

function shot3()
	teleport_to_slate_pos("CS_luz", 1.25969, -0.900003, -0.318676, "slate_angelo_bedroom")
	play_custom_action_do("CS_luz", "lc07_scene02b_luz_3")
	teleport_to_slate_pos("CS_angelo", 0.538659, -0.899985, -0.297213, "slate_angelo_bedroom")
	play_custom_action_do("CS_angelo", "lc07_scene02b_angelo_3")
end

function shot4()
	teleport_to_slate_pos("CS_luz", 1.08448, -0.900002, 0.499761, "slate_angelo_bedroom")
	play_custom_action_do("CS_luz", "lc07_scene02b_luz_4")
	teleport_to_slate_pos("CS_angelo", 0.592554, -0.899984, -0.185714, "slate_angelo_bedroom")
	play_custom_action_do("CS_angelo", "lc07_scene02b_angelo_4")
end

function shot5()
	teleport_to_slate_pos("CS_luz", 1.08148, -0.900001, 0.505097, "slate_angelo_bedroom")
	play_custom_action_do("CS_luz", "lc07_scene02b_luz_5")
	teleport_to_slate_pos("CS_angelo", 0.617857, -0.899984, -0.136171, "slate_angelo_bedroom")
	play_custom_action_do("CS_angelo", "lc07_scene02b_angelo_5")
end

function shot6()
	teleport_to_slate_pos("CS_luz", 1.13549, -1.06472, 0.520037, "slate_angelo_bedroom")
	play_custom_action_do("CS_luz", "lc07_scene02b_luz_6")
	teleport_to_slate_pos("CS_angelo", 0.617857, -0.899984, -0.136171, "slate_angelo_bedroom")
	play_custom_action_do("CS_angelo", "lc07_scene02b_angelo_6")
	delay(5)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	stop_custom_actions("CS_luz")
	stop_custom_actions("CS_angelo")
	letterbox_fade_out(true)
	fade_out(0.5)
end
