-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc08_policestation\lc08_policestation.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk14__interiors.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
end

function shot1()
	set_level_lights(false)
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("#PLAYER#", -0.574577, 0.0, -1.54611, "slate_barrio_police")
	play_custom_action_do("#PLAYER#", "lc08_police_pc_1")
	teleport_to_slate_pos("CS_saint01", 1.35621, 0.63187, 2.63126, "slate_barrio_police")
	play_custom_action_do("CS_saint01", "lc08_police_snt1_1")
	teleport_to_slate_pos("CS_saint02", 1.24934, 0.633209, 1.53339, "slate_barrio_police")
	play_custom_action_do("CS_saint02", "lc08_police_snt2_1")
	teleport_to_slate_pos("CS_saint03", 1.33817, 0.633209, 1.9544, "slate_barrio_police")
	play_custom_action_do("CS_saint03", "lc08_police_snt3_1")
	teleport_to_slate_pos("CS_saint04", 1.34246, 0.63187, 2.40099, "slate_barrio_police")
	play_custom_action_do("CS_saint04", "lc08_police_snt4_1")
	teleport_to_slate_pos("CS_truck", 4.6603, 0.0439067, 2.16018, "slate_barrio_police")
	play_custom_action_do("CS_truck", "lc08_police_truck_1")
end

function shot2()
	teleport_to_slate_pos("#PLAYER#", -0.540275, 0.0, -1.54715, "slate_barrio_police")
	play_custom_action_do("#PLAYER#", "lc08_police_pc_2")
	teleport_to_slate_pos("CS_saint01", 1.02796, 0.63187, 2.63093, "slate_barrio_police")
	play_custom_action_do("CS_saint01", "lc08_police_snt1_2")
	teleport_to_slate_pos("CS_saint02", 0.945227, 0.633209, 1.53316, "slate_barrio_police")
	play_custom_action_do("CS_saint02", "lc08_police_snt2_2")
	teleport_to_slate_pos("CS_saint03", 1.02376, 0.633209, 1.9544, "slate_barrio_police")
	play_custom_action_do("CS_saint03", "lc08_police_snt3_2")
	teleport_to_slate_pos("CS_saint04", 0.918792, 0.63187, 2.4002, "slate_barrio_police")
	play_custom_action_do("CS_saint04", "lc08_police_snt4_2")
	teleport_to_slate_pos("CS_truck", 4.50235, 0.0439067, 2.16018, "slate_barrio_police")
	play_custom_action_do("CS_truck", "lc08_police_truck_2")
end

function shot3()
	teleport_to_slate_pos("#PLAYER#", -0.575217, 0.0, -1.55527, "slate_barrio_police")
	play_custom_action_do("#PLAYER#", "lc08_police_pc_3")
	teleport_to_slate_pos("CS_saint01", -0.335384, 0.63187, 2.6417, "slate_barrio_police")
	play_custom_action_do("CS_saint01", "lc08_police_snt1_3")
	teleport_to_slate_pos("CS_saint02", -0.36113, 0.633209, 1.5331, "slate_barrio_police")
	play_custom_action_do("CS_saint02", "lc08_police_snt2_3")
	teleport_to_slate_pos("CS_saint03", -0.233149, 0.633209, 1.95441, "slate_barrio_police")
	play_custom_action_do("CS_saint03", "lc08_police_snt3_3")
	teleport_to_slate_pos("CS_saint04", -0.326935, 0.63187, 2.41731, "slate_barrio_police")
	play_custom_action_do("CS_saint04", "lc08_police_snt4_3")
	teleport_to_slate_pos("CS_truck", 3.64295, 0.0439067, 2.16018, "slate_barrio_police")
	play_custom_action_do("CS_truck", "lc08_police_truck_3")
end

function shot4()
	teleport_to_slate_pos("#PLAYER#", -0.560602, 0.0, -1.55165, "slate_barrio_police")
	play_custom_action_do("#PLAYER#", "lc08_police_pc_4")
	teleport_to_slate_pos("CS_saint01", -2.99515, 0.63187, 2.52055, "slate_barrio_police")
	play_custom_action_do("CS_saint01", "lc08_police_snt1_4")
	teleport_to_slate_pos("CS_saint02", -2.26195, 0.633209, 1.49892, "slate_barrio_police")
	play_custom_action_do("CS_saint02", "lc08_police_snt2_4")
	teleport_to_slate_pos("CS_saint03", -4.08245, 0.0, 2.04737, "slate_barrio_police")
	play_custom_action_do("CS_saint03", "lc08_police_snt3_4")
	teleport_to_slate_pos("CS_saint04", -5.28988, 0.0, 2.05193, "slate_barrio_police")
	play_custom_action_do("CS_saint04", "lc08_police_snt4_4")
	teleport_to_slate_pos("CS_truck", 2.73613, 0.0439067, 2.16018, "slate_barrio_police")
	play_custom_action_do("CS_truck", "lc08_police_truck_4")
end

function shot5()
	teleport_to_slate_pos("#PLAYER#", -0.523675, 0.0, -1.55077, "slate_barrio_police")
	play_custom_action_do("#PLAYER#", "lc08_police_pc_5")
	teleport_to_slate_pos("CS_saint01", -11.7342, 0.0, 1.00408, "slate_barrio_police")
	play_custom_action_do("CS_saint01", "lc08_police_snt1_5")
	teleport_to_slate_pos("CS_saint02", -11.7241, 0.0, 1.36284, "slate_barrio_police")
	play_custom_action_do("CS_saint02", "lc08_police_snt2_5")
	teleport_to_slate_pos("CS_saint03", -8.58616, 0.0, -5.35408, "slate_barrio_police")
	play_custom_action_do("CS_saint03", "lc08_police_snt3_5")
	teleport_to_slate_pos("CS_saint04", -11.6042, 0.0, 0.447208, "slate_barrio_police")
	play_custom_action_do("CS_saint04", "lc08_police_snt4_5")
	teleport_to_slate_pos("CS_truck", 0.18551, 0.0439067, 2.16018, "slate_barrio_police")
	play_custom_action_do("CS_truck", "lc08_police_truck_5")
	fade_out(0.0)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end

function cutscene_end()
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_saint01")
	stop_custom_actions("CS_saint02")
	stop_custom_actions("CS_saint03")
	stop_custom_actions("CS_saint04")
	stop_custom_actions("CS_truck")
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end
