-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc08_policestation\lc08_policestation.cts
-- Level:D:\projects\blingbling\data\test\cutscene_lc08_policestation.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	character_hide("CS_truck")
end

function shot2()
	character_show("CS_truck")
end

function shot3()
end

function shot4()
end

function cutscene_abort()
end

function cutscene_end()
end
