-- /////////////////////////////////////////////////////////////
--                Code generated by LUA Cutscene Editor
--                      Version: 0.2b
--                      Date: 12/16/2005 4:52:42 PM
--                      Author: jeff.spoonhower
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc08_policestation\lc08_policestation.cts
-- Level:D:\projects\blingbling\data\test\cutscene_lc08_policestation.cts
-- /////////////////////////////////////////////////////////////

function cutscene_main()
end

function shot1()
	spawning_peds(false)
	spawning_cars(false)
	thread_new("scripted_event1", 1)
	thread_new("scripted_event2", 2)
	tree_shadows_enable(false)
	set_level_lights(false)
end

function shot2()
end

function shot3()
end

function shot4()
end

function cutscene_abort()
	spawning_peds(true)
	spawning_cars(true)
end

function cutscene_end()
	spawning_peds(true)
	spawning_cars(true)
end

function scripted_event1()
	tree_shadows_enable(true)
	teleport("CS_look01", "CS_CharNav_look01_1")
	play_action_sequence("CS_look01", "angry stand")
end

function scripted_event2()
	tree_shadows_enable(true)
	teleport("CS_look02", "CS_CharNav_look02_1")
	play_action_sequence("CS_look02", "angry stand")
end
