-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc08_scene01\lc08_scene01.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk02__interiors.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
end

function shot1()
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("CS_dex", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_dex", "lc08_scene01_dex_1")
	teleport_to_slate_pos("#PLAYER#", -2.74796, 0.0, -0.274847, "slate_church_main")
	play_custom_action_do("#PLAYER#", "lc08_scene01_player_1")
	teleport_to_slate_pos("CS_troy", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_troy", "lc08_scene01_troy_1")
end

function shot2()
	teleport_to_slate_pos("CS_dex", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_dex", "lc08_scene01_dex_2")
	teleport_to_slate_pos("#PLAYER#", -4.08636, 0.0, -0.518789, "slate_church_main")
	play_custom_action_do("#PLAYER#", "lc08_scene01_player_2")
	teleport_to_slate_pos("CS_troy", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_troy", "lc08_scene01_troy_2")
end

function shot3()
	teleport_to_slate_pos("CS_dex", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_dex", "lc08_scene01_dex_3")
	teleport_to_slate_pos("#PLAYER#", -4.15439, 0.0, -0.521329, "slate_church_main")
	play_custom_action_do("#PLAYER#", "lc08_scene01_player_3")
	teleport_to_slate_pos("CS_troy", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_troy", "lc08_scene01_troy_3")
end

function shot4()
	teleport_to_slate_pos("CS_dex", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_dex", "lc08_scene01_dex_4")
	teleport_to_slate_pos("#PLAYER#", -4.06535, 0.0, -0.563917, "slate_church_main")
	play_custom_action_do("#PLAYER#", "lc08_scene01_player_4")
	teleport_to_slate_pos("CS_troy", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_troy", "lc08_scene01_troy_4")
end

function shot5()
	teleport_to_slate_pos("CS_dex", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_dex", "lc08_scene01_dex_5")
	teleport_to_slate_pos("#PLAYER#", -4.05, 0.0, -0.459501, "slate_church_main")
	play_custom_action_do("#PLAYER#", "lc08_scene01_player_5")
	teleport_to_slate_pos("CS_troy", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_troy", "lc08_scene01_troy_5")
end

function shot6()
	teleport_to_slate_pos("CS_dex", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_dex", "lc08_scene01_dex_6")
	teleport_to_slate_pos("#PLAYER#", -4.08881, 0.0, -0.721643, "slate_church_main")
	play_custom_action_do("#PLAYER#", "lc08_scene01_player_6")
	teleport_to_slate_pos("CS_troy", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_troy", "lc08_scene01_troy_6")
end

function shot7()
	teleport_to_slate_pos("CS_dex", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_dex", "lc08_scene01_dex_7")
	teleport_to_slate_pos("#PLAYER#", -4.05506, 0.0, -0.578622, "slate_church_main")
	play_custom_action_do("#PLAYER#", "lc08_scene01_player_7")
	teleport_to_slate_pos("CS_troy", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_troy", "lc08_scene01_troy_7")
end

function shot8()
	teleport_to_slate_pos("CS_dex", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_dex", "lc08_scene01_dex_8")
	teleport_to_slate_pos("#PLAYER#", -4.06715, 0.0, -0.541065, "slate_church_main")
	play_custom_action_do("#PLAYER#", "lc08_scene01_player_8")
	teleport_to_slate_pos("CS_troy", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_troy", "lc08_scene01_troy_8")
end

function shot9()
	teleport_to_slate_pos("CS_dex", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_dex", "lc08_scene01_dex_9")
	teleport_to_slate_pos("#PLAYER#", -4.06715, 0.0, -0.541065, "slate_church_main")
	play_custom_action_do("#PLAYER#", "lc08_scene01_player_9")
	teleport_to_slate_pos("CS_troy", 0.0, 0.0, 0.0, "slate_church_main")
	play_custom_action_do("CS_troy", "lc08_scene01_troy_9")
	fade_out(0.0)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	stop_custom_actions("CS_dex")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_troy")
	letterbox_fade_out(true)
	fade_out(0.5)
end
