-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\lc10_scene02\lc10_scene02.cts
-- Level:D:\projects\blingbling\data\test\cutscene_lc10_scene02.cts
-------------------------------------


function cutscene_main()
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function shot8()
end

function shot9()
end

function shot10()
end

function shot11()
end

function shot12()
end

function shot13()
end

function shot14()
end

function cutscene_abort()
end

function cutscene_end()
end
