-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\pimping_trailerpark\pimping_trailerpark.cts
-- Level:D:\projects\blingbling\data\test\cutscene_pimping_trailerpark.cts
-------------------------------------


function cutscene_main()
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function cutscene_abort()
end

function cutscene_end()
end
