-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\racing_ashland\racing_ashland.cts
-- Level:D:\projects\blingbling\data\cutscenes\racing_ashland\racing_ashland.cts
-------------------------------------


function cutscene_main()
end

function shot1()
    --set_level_lights(false)
	time_of_day_character_shadows_enable(false)
	--cutscene_mesh_hide("AR_224_trailer_11")
	--cutscene_mesh_hide("09_AR_224_trailer_11")
	--cutscene_mesh_hide("ar_c09_CratShipB19")
	--cutscene_mesh_hide("ar_c09_CratShipB17")
	--cutscene_mesh_hide("ar_c09_CratShipB18")
end

function shot2()
end

function shot3()
end

function cutscene_abort()
	set_level_lights(true)
	time_of_day_character_shadows_enable(true)
end

function cutscene_end()
	set_level_lights(true)
	time_of_day_character_shadows_enable(true)
end
