---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: racing_downtown
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk33", true )
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
end

function shot1()
	fade_in(0.5)
	select_slate("slate_racing_downtown")
	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_tyrell", -1.443, 0.0, 0.656, "slate_racing_downtown")
	play_custom_action_do("CS_tyrell", "racing_downtown_tyrell_1")
	teleport_to_slate_pos("#PLAYER#", 3.309, 0.0, 2.592, "slate_racing_downtown")
	play_custom_action_do("#PLAYER#", "racing_downtown_player_1")
	teleport_to_slate_pos("CS_csDowntownRacing", -1.671, -0.215, -2.036, "slate_racing_downtown")
	play_custom_action_do("CS_csDowntownRacing", "racing_downtown_car_1")
	time_of_day_character_shadows_enable(false)
	set_level_lights(false)
	spawning_peds(false)
	spawning_cars(false)
	npc_unholster_best_weapon("CS_tyrell")
end

function shot2()
	teleport_to_slate_pos("CS_tyrell", -1.62, 0.0, 0.771, "slate_racing_downtown")
	play_custom_action_do("CS_tyrell", "racing_downtown_tyrell_2")
	teleport_to_slate_pos("#PLAYER#", -0.192, 0.0, 0.947, "slate_racing_downtown")
	play_custom_action_do("#PLAYER#", "racing_downtown_player_2")
	teleport_to_slate_pos("CS_csDowntownRacing", -1.671, -0.215, -2.036, "slate_racing_downtown")
	play_custom_action_do("CS_csDowntownRacing", "racing_downtown_car_2")
end

function shot3()
	teleport_to_slate_pos("CS_tyrell", -1.35, 0.0, 0.76, "slate_racing_downtown")
	play_custom_action_do("CS_tyrell", "racing_downtown_tyrell_3")
	teleport_to_slate_pos("#PLAYER#", -0.145, 0.0, 0.913, "slate_racing_downtown")
	play_custom_action_do("#PLAYER#", "racing_downtown_player_3")
	teleport_to_slate_pos("CS_csDowntownRacing", -1.671, -0.215, -2.036, "slate_racing_downtown")
	play_custom_action_do("CS_csDowntownRacing", "racing_downtown_car_3")
end

function shot4()
	teleport_to_slate_pos("CS_tyrell", -1.213, 0.0, 0.771, "slate_racing_downtown")
	play_custom_action_do("CS_tyrell", "racing_downtown_tyrell_4")
	teleport_to_slate_pos("#PLAYER#", -0.152, 0.0, 0.904, "slate_racing_downtown")
	play_custom_action_do("#PLAYER#", "racing_downtown_player_4")
	teleport_to_slate_pos("CS_csDowntownRacing", -1.671, -0.215, -2.036, "slate_racing_downtown")
	play_custom_action_do("CS_csDowntownRacing", "racing_downtown_car_4")
end

function shot5()
	teleport_to_slate_pos("CS_tyrell", -1.493, 0.0, 0.525, "slate_racing_downtown")
	play_custom_action_do("CS_tyrell", "racing_downtown_tyrell_5")
	teleport_to_slate_pos("#PLAYER#", -0.15, 0.0, 0.897, "slate_racing_downtown")
	play_custom_action_do("#PLAYER#", "racing_downtown_player_5")
	teleport_to_slate_pos("CS_csDowntownRacing", -1.671, -0.215, -2.036, "slate_racing_downtown")
	play_custom_action_do("CS_csDowntownRacing", "racing_downtown_car_5")
end

function shot6()
	teleport_to_slate_pos("CS_tyrell", -1.437, 0.0, 0.209, "slate_racing_downtown")
	play_custom_action_do("CS_tyrell", "racing_downtown_tyrell_6")
	teleport_to_slate_pos("#PLAYER#", -0.144, 0.0, 0.907, "slate_racing_downtown")
	play_custom_action_do("#PLAYER#", "racing_downtown_player_6")
	teleport_to_slate_pos("CS_csDowntownRacing", -1.671, -0.215, -2.036, "slate_racing_downtown")
	play_custom_action_do("CS_csDowntownRacing", "racing_downtown_car_6")
	delay(1.93333)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	time_of_day_character_shadows_enable(true)
	spawning_peds(true)
	spawning_cars(true)
end

function cutscene_end()
	stop_custom_actions("CS_tyrell")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_csDowntownRacing")
	letterbox_fade_out(true)
	fade_out(0.5)
	time_of_day_character_shadows_enable(true)
	spawning_peds(true)
	spawning_cars(true)
end
