-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\racing_downtown\racing_downtown.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk33__ground.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	load_chunk("sr_chunk33", true )
	select_slate("slate_racing_downtown")
	audio_play("CS Racing Downtown", "voice", true)
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function cutscene_abort()
end

function cutscene_end()
end
