-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\test_scripted_chars\test_scripted_chars.cts
-- Level:undefined.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
end

function shot1()
	fade_in(0.5)
	letterbox_fade_in(true)
	load_chunk("cutscene_test_scripted_chars", true )
	select_slate("slate_test_scriptchars")
	teleport_to_slate_pos("#PLAYER#", -2.0409, 0.00148093, -2.66336, "slate_test_scriptchars")
	play_custom_action_do("#PLAYER#", "test_scripted_1")
	thread_new("scripted_event1", 1)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	stop_custom_actions("#PLAYER#")
	letterbox_fade_out(true)
	fade_out(0.5)
end

function scripted_event1()
	play_action_sequence("CS_walker01", "stand ready")
	delay(5.0)
	play_action_sequence("CS_walker01", "talk confrontational", "walk")
	local walker01_navs01 = {"CS_$pathNav-walker01-01_1"}
	move_to("CS_walker01", walker01_navs01, 1)
	play_action_sequence("CS_walker01", "stand")
end
