-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\Projects\blingbling\data\cutscenes\test_cutscene_hide\test_cutscene_hide.cts
-- Level:D:\Projects\blingbling\data\test\cutscene_hide_test.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
end

function shot1()
	fade_in(0.5)
	letterbox_fade_in(true)
	delay(2)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	letterbox_fade_out(true)
	fade_out(0.5)
end
