-- /////////////////////////////////////////////////////////////
--                Code generated by LUA Cutscene Editor
--                      Version: 0.2b
--                      Date: 1/3/2006 12:42:02 PM
--                      Author: Ev.Religioso
-- Cutscene:D:\projects\blingbling\data\cutscenes\theft_apartments\theft_apartments.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk11_PS__interiors.cts
-- /////////////////////////////////////////////////////////////

function cutscene_main()
end

function shot1()
--NOTE use level lights off
-- NOTE, should use 	load_chunks("sr_chunk11_PS", "sr_chunk11" )
	character_hide("CS_walker01")
	character_hide("CS_walker02")
	character_hide("CS_walker03")
end

function shot2()
	character_show("CS_walker01")
	thread_new("scripted_event1", 1)
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
	character_show("CS_walker02")
	character_show("CS_walker03")
	thread_new("scripted_event3", 3)
	thread_new("scripted_event2", 2)
end

function shot8()
end

function cutscene_abort()
end

function cutscene_end()
end

function scripted_event1()
	teleport("CS_walker01", "CS_CharacterNav-walker01_1")
	local walker01_navpoints01 = {"CS_PathNav-walker01-01_1"}
	move_to("CS_walker01", walker01_navpoints01, 1)
end

function scripted_event2()
	teleport("CS_walker02", "CS_CharacterNav-walker02_1")
	local navpoints_walker02_01 = {"CS_PathNav-walker02_1"}
	move_to("CS_walker02", navpoints_walker02_01, 1)
end

function scripted_event3()
	teleport("CS_walker03", "CS_CharacterNav-walker03_1")
	local navpoints_walker03 = {"CS_PathNav-walker03_1"}
	move_to("CS_walker03", navpoints_walker03, 1)
end
