-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\tss01_scene02\tss01_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk02__ground.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
	thread_new_cutscene_shot("shot12", 12)
	thread_new_cutscene_shot("shot13", 13)
	thread_new_cutscene_shot("shot14", 14)
	thread_new_cutscene_shot("shot15", 15)
end

function shot1()
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("CS_jul", 0.425642, 0.0, -2.7402, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_1")
end

function shot2()
	teleport_to_slate_pos("CS_jul", 0.42051, 0.0, -2.72341, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_2")
end

function shot3()
	teleport_to_slate_pos("CS_jul", 0.341533, 0.0, -2.6839, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_3")
end

function shot4()
	teleport_to_slate_pos("CS_jul", 0.486493, 0.0, -2.64583, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_4")
end

function shot5()
	teleport_to_slate_pos("CS_jul", 0.852791, 0.0, -1.62609, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_5")
end

function shot6()
	teleport_to_slate_pos("CS_jul", 1.15512, 0.0, 0.674479, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_6")
end

function shot7()
	teleport_to_slate_pos("CS_jul", 0.725092, 0.0, 0.178728, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_7")
end

function shot8()
	teleport_to_slate_pos("CS_jul", 0.658117, 0.0, 0.170292, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_8")
end

function shot9()
	teleport_to_slate_pos("CS_jul", 0.665151, 0.0, 0.206888, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_9")
end

function shot10()
	teleport_to_slate_pos("CS_jul", 0.666628, 0.0, 0.203489, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_10")
end

function shot11()
	teleport_to_slate_pos("CS_jul", 0.643534, 0.0, 0.205029, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_11")
end

function shot12()
	teleport_to_slate_pos("CS_jul", 0.652658, 0.0, 0.216751, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_12")
end

function shot13()
	teleport_to_slate_pos("CS_jul", 0.653179, 0.0, 0.213734, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_13")
end

function shot14()
	teleport_to_slate_pos("CS_jul", 0.657362, 0.0, 0.213367, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_14")
end

function shot15()
	teleport_to_slate_pos("CS_jul", 0.656381, 0.0, 0.211309, "slate_chruch_yard")
	play_custom_action_do("CS_jul", "tss01_scene02_jul_15")
	fade_out(0.0)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
end

function cutscene_end()
	stop_custom_actions("CS_jnny")
	stop_custom_actions("CS_pc")
	stop_custom_actions("CS_dex")
	stop_custom_actions("CS_snta")
	stop_custom_actions("CS_sntc")
	stop_custom_actions("CS_sntb")
	stop_custom_actions("CS_troy")
	stop_custom_actions("CS_jul")
	letterbox_fade_out(true)
	fade_out(0.5)
end
