-- /////////////////////////////////////////////////////////////
--                Code generated by LUA Cutscene Editor
--                      Version: 0.2b
--                      Date: 11/21/2005 7:03:46 PM
--                      Author: ereligioso
-- Cutscene:D:\projects\blingbling\data\cutscenes\tss01_scene02\tss01_scene02.cts
-- Level:D:\projects\blingbling\data\test\cutscene_tss01_scene03.cts
-- /////////////////////////////////////////////////////////////

function cutscene_main()
end

function shot1()
	character_hide("CS_stander01")	
	character_hide("CS_stander02")	
	character_hide("CS_stander03")	
	character_hide("CS_stander04")
	character_hide("CS_dex")
	time_of_day_character_shadows_enable(false)
end

function shot2()
end

function shot3()
	character_show("CS_stander01")
	character_show("CS_stander02")
	character_show("CS_stander03")	
	character_show("CS_stander04")
	thread_new("scripted_event1", 1)
end

function shot4()
	fat_bones_enable("#PLAYER#", false) 
	character_show("CS_dex")
end

function shot5()
end

function shot6()
	fat_bones_enable("#PLAYER#", true) 
end

function shot7()
--	play_action_sequence("CS_stander01", "surrender")
end

function shot8()
end

function shot9()
end

function shot10()
end

function shot11()
end

function shot12()
end

function shot13()
end

function shot14()
end

function cutscene_abort()
	fat_bones_enable("#PLAYER#", true) 
	time_of_day_character_shadows_enable(true)
end

function cutscene_end()
	fat_bones_enable("#PLAYER#", true) 
	time_of_day_character_shadows_enable(true)
end

function scripted_event1()
--	teleport("CS_CSCharnav-stander01_1", "CS_CSCharnav-stander01_1")
	play_action_sequence("CS_stander01", "stand")
end
