---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: tss_intro
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunks("sr_chunk05", "sr_chunk03")
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
	thread_new_cutscene_shot("shot12", 12)
	thread_new_cutscene_shot("shot13", 13)
	thread_new_cutscene_shot("shot14", 14)
	thread_new_cutscene_shot("shot15", 15)
	thread_new_cutscene_shot("shot16", 16)
	thread_new_cutscene_shot("shot17", 17)
	thread_new_cutscene_shot("shot18", 18)
	thread_new_cutscene_shot("shot19", 19)
	thread_new_cutscene_shot("shot20", 20)
	thread_new_cutscene_shot("shot21", 21)
	thread_new_cutscene_shot("shot22", 22)
	thread_new_cutscene_shot("shot23", 23)
	thread_new_cutscene_shot("shot24", 24)
	thread_new_cutscene_shot("shot25", 25)
	thread_new_cutscene_shot("shot26", 26)
	thread_new_cutscene_shot("shot27", 27)
	thread_new_cutscene_shot("shot28", 28)
	thread_new_cutscene_shot("shot29", 29)
	thread_new_cutscene_shot("shot30", 30)
	thread_new_cutscene_shot("shot31", 31)
	thread_new_cutscene_shot("shot32", 32)
	thread_new_cutscene_shot("shot33", 33)
	thread_new_cutscene_shot("shot34", 34)
	thread_new_cutscene_shot("shot35", 35)
	thread_new_cutscene_shot("shot36", 36)
	thread_new_cutscene_shot("shot37", 37)
	thread_new_cutscene_shot("shot38", 38)
	thread_new_cutscene_shot("shot39", 39)
	thread_new_cutscene_shot("shot40", 40)
	thread_new_cutscene_shot("shot41", 41)
	thread_new_cutscene_shot("shot42", 42)
	thread_new_cutscene_shot("shot43", 43)
	thread_new_cutscene_shot("shot44", 44)
	thread_new_cutscene_shot("shot45", 45)
	thread_new_cutscene_shot("shot46", 46)
	thread_new_cutscene_shot("shot47", 47)
	thread_new_cutscene_shot("shot48", 48)
	thread_new_cutscene_shot("shot49", 49)
	thread_new_cutscene_shot("shot50", 50)
	thread_new_cutscene_shot("shot51", 51)
	thread_new_cutscene_shot("shot52", 52)
	thread_new_cutscene_shot("shot53", 53)
	thread_new_cutscene_shot("shot54", 54)
end

function shot1()
	local excluded_lights_1 = {"BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA31", "lampA32", "lampA33", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni07", "BB Omni08", "lampA40", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni23", "BB Omni24", "BB Omni26", "BB Omni27", "BB Omni28", "BB Omni30", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_1, 36, false)

	local included_lights_1 = {"BB Omni01", "lampA30", "lampA34", "BB Omni06", "BB Omni09", "BB Omni20", "BB Omni25", "lampA45", "BB Omni29", "BB Omni31"}
	light_set_lights(included_lights_1, 10, true)

	set_weather(0, true)
	fade_in(0.5)
	select_slate("slate_TSS_intro")
	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_ho", 8.197, 0.0, -2.002, "slate_TSS_intro")
	play_custom_action_do("CS_ho", "tss_intro_ho_1")
	teleport_to_slate_pos("CS_hustler", 12.275, 0.0, -2.282, "slate_TSS_intro")
	play_custom_action_do("CS_hustler", "tss_intro_hustler_1")
	teleport_to_slate_pos("#PLAYER#", 17.693, 0.0, -1.145, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_1")
	set_far_clip(5000)
	set_weather(0, true)
	set_time_of_day(22, 0)
	set_level_lights(false)

	
	inv_item_equip("watchcase","CS_hustler")
	
	thread_new("scripted_event1", 1)
	thread_new("scripted_event2", 2)
	thread_new("scripted_event3", 3)
	thread_new("scripted_event4", 4)
end

function shot2()
	local excluded_lights_2 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_2, 40, false)

	local included_lights_2 = {"BB Omni03", "lampA37", "lampA40", "BB Omni11", "BB Omni30", "BB Omni32"}
	light_set_lights(included_lights_2, 6, true)

	character_hide("#PLAYER#")
	teleport_to_slate_pos("CS_vkc", -3.072, 0.0, -11.458, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_2")
	teleport_to_slate_pos("CS_vb", -3.469, 0.0, -13.556, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_2")
	teleport_to_slate_pos("CS_wrb", -3.691, 0.0, -6.205, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_2")
	teleport_to_slate_pos("CS_wrc", -5.279, 0.0, -6.449, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_2")
	teleport_to_slate_pos("CS_vka", -3.335, 0.0, -12.57, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_2")
	set_far_clip(40)
	character_hide("CS_walker01")
    character_hide("CS_walker02")
    character_hide("CS_ho02")
    character_hide("CS_stander01") 
	
    character_hide("CS_hustler")
	
	inv_item_equip("spraycancut","CS_vkc")
	inv_item_equip("baseball_bat","CS_wra")

end

function shot3()
	local excluded_lights_3 = {"BB Omni01", "BB Omni02", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_3, 40, false)

	local included_lights_3 = {"BB Omni03", "BB Omni04", "lampA37", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_3, 6, true)

	teleport_to_slate_pos("CS_vkc", -3.075, 0.0, -11.45, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_3")
	teleport_to_slate_pos("CS_vb", -3.538, 0.0, -13.474, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_3")
	teleport_to_slate_pos("CS_wrb", -3.719, 0.0, -6.233, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_3")
	teleport_to_slate_pos("CS_wrc", -5.274, 0.0, -6.448, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_3")
	teleport_to_slate_pos("CS_vka", -3.354, 0.0, -12.614, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_3")
	set_far_clip(5000)
    thread_new("scripted_event5", 5)


end

function shot4()
	local excluded_lights_4 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_4, 40, false)

	local included_lights_4 = {"BB Omni03", "lampA37", "lampA40", "BB Omni11", "BB Omni20", "BB Omni30"}
	light_set_lights(included_lights_4, 6, true)

	teleport_to_slate_pos("CS_vkc", -2.686, 0.0, -11.555, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_4")
	teleport_to_slate_pos("CS_vb", -3.435, 0.0, -13.459, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_4")
	teleport_to_slate_pos("CS_wrb", -3.69, 0.0, -6.252, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_4")
	teleport_to_slate_pos("CS_wrc", -5.271, 0.0, -6.452, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_4")
	teleport_to_slate_pos("CS_vka", -3.229, 0.0, -12.501, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_4")
	set_far_clip(5000)
   character_hide("CS_walker03")
   thread_new("scripted_event6", 6)
   thread_new("scripted_event7", 7)


end

function shot5()
	local excluded_lights_5 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_5, 39, false)

	local included_lights_5 = {"BB Omni03", "lampA28", "lampA37", "BB Omni05", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_5, 7, true)

	teleport_to_slate_pos("CS_vkc", -2.555, 0.0, -11.558, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_5")
	teleport_to_slate_pos("CS_vb", -3.495, 0.0, -13.448, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_5")
	teleport_to_slate_pos("CS_wra", -4.549, 0.0, -7.541, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_5")
	teleport_to_slate_pos("CS_wrb", -3.564, 0.0, -6.324, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_5")
	teleport_to_slate_pos("CS_wrc", -5.188, 0.0, -6.55, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_5")
	teleport_to_slate_pos("CS_vka", -3.205, 0.0, -12.556, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_5")
	set_far_clip(200)
    character_hide("CS_ho03")
    character_hide("CS_ho04")
    thread_new("scripted_event8", 8)
	thread_new("scripted_event9", 9)
   

end

function shot6()
	local excluded_lights_6 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_6, 39, false)

	local included_lights_6 = {"BB Omni03", "lampA37", "BB Omni05", "lampA40", "BB Omni11", "BB Omni30", "BB Omni32"}
	light_set_lights(included_lights_6, 7, true)

	teleport_to_slate_pos("CS_vkc", -2.527, 0.0, -11.705, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_6")
	teleport_to_slate_pos("CS_vb", -3.652, 0.0, -13.412, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_6")
	teleport_to_slate_pos("CS_wra", -4.02, 0.0, -11.148, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_6")
	teleport_to_slate_pos("CS_wrb", -3.022, 0.0, -10.784, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_6")
	teleport_to_slate_pos("CS_wrc", -4.997, 0.0, -11.698, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_6")
	teleport_to_slate_pos("CS_vka", -3.182, 0.0, -12.517, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_6")
	set_far_clip(20)
    character_hide("CS_stander02")
    character_hide("CS_stander03")
   

end

function shot7()
	local excluded_lights_7 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_7, 41, false)

	local included_lights_7 = {"BB Omni03", "lampA37", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_7, 5, true)

	teleport_to_slate_pos("CS_vkc", -2.497, 0.0, -11.443, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_7")
	teleport_to_slate_pos("CS_vb", -4.018, 0.0, -12.852, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_7")
	teleport_to_slate_pos("CS_wra", -3.993, 0.0, -11.1, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_7")
	teleport_to_slate_pos("CS_wrb", -2.956, 0.0, -10.838, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_7")
	teleport_to_slate_pos("CS_wrc", -4.952, 0.0, -11.94, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_7")
	teleport_to_slate_pos("CS_vka", -3.28, 0.0, -12.364, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_7")
	set_far_clip(50)
end

function shot8()
	local excluded_lights_8 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_8, 40, false)

	local included_lights_8 = {"BB Omni03", "lampA37", "BB Omni05", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_8, 6, true)

	teleport_to_slate_pos("CS_vkc", -3.052, 0.0, -11.354, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_8")
	teleport_to_slate_pos("CS_vb", -4.397, 0.0, -12.96, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_8")
	teleport_to_slate_pos("CS_wra", -4.283, 0.0, -11.026, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_8")
	teleport_to_slate_pos("CS_wrb", -3.049, 0.0, -10.187, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_8")
	teleport_to_slate_pos("CS_wrc", -5.018, 0.0, -12.109, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_8")
	teleport_to_slate_pos("CS_vka", -3.088, 0.0, -12.854, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_8")
	set_far_clip(5000)
end	

function shot9()

end

function shot9()
	local excluded_lights_9 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_9, 40, false)

	local included_lights_9 = {"BB Omni03", "lampA37", "BB Omni05", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_9, 6, true)

	teleport_to_slate_pos("CS_vkc", -3.654, 0.0, -11.228, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_9")
	teleport_to_slate_pos("CS_vb", -4.396, 0.0, -12.959, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_9")
	teleport_to_slate_pos("CS_wra", -4.243, 0.0, -10.794, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_9")
	teleport_to_slate_pos("CS_wrb", -3.154, 0.0, -10.022, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_9")
	teleport_to_slate_pos("CS_wrc", -5.017, 0.0, -12.107, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_9")
	teleport_to_slate_pos("CS_vka", -2.902, 0.0, -13.19, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_9")

end

function shot10()
	local excluded_lights_10 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_10, 41, false)

	local included_lights_10 = {"BB Omni03", "BB Omni05", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_10, 5, true)

	teleport_to_slate_pos("CS_vkc", -3.609, 0.0, -11.805, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_10")
	teleport_to_slate_pos("CS_vb", -4.334, 0.0, -13.121, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_10")
	teleport_to_slate_pos("CS_wrb", -3.495, 0.0, -10.581, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_10")
	teleport_to_slate_pos("CS_wrc", -4.732, 0.0, -12.551, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_10")
	teleport_to_slate_pos("CS_vka", -2.902, 0.0, -13.159, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_10")
	set_far_clip(20)
	npc_holster("CS_wra") 

end

function shot11()
	local excluded_lights_11 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_11, 40, false)

	local included_lights_11 = {"BB Omni03", "lampA37", "BB Omni05", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_11, 6, true)

	teleport_to_slate_pos("CS_vkc", -3.539, 0.0, -12.227, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_11")
	teleport_to_slate_pos("CS_vb", -4.186, 0.0, -13.516, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_11")
	teleport_to_slate_pos("CS_wra", -4.481, 0.0, -10.659, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_11")
	teleport_to_slate_pos("CS_wrb", -3.125, 0.0, -10.319, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_11")
	teleport_to_slate_pos("CS_wrc", -4.483, 0.0, -12.915, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_11")
	teleport_to_slate_pos("CS_vka", -2.901, 0.0, -13.158, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_11")
	set_far_clip(5000)
end

function shot12()
	local excluded_lights_12 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_12, 41, false)

	local included_lights_12 = {"lampA37", "lampA40", "BB Omni11", "BB Omni30", "BB Omni32"}
	light_set_lights(included_lights_12, 5, true)

	teleport_to_slate_pos("CS_vkc", -1.496, 0.0, -11.979, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_12")
	teleport_to_slate_pos("CS_vb", -4.764, 0.0, -14.158, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_12")
	teleport_to_slate_pos("CS_wrb", -2.888, 0.0, -10.012, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_12")
	teleport_to_slate_pos("CS_wrc", -4.496, 0.0, -13.634, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_12")
	teleport_to_slate_pos("CS_vka", -2.9, 0.0, -13.159, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_12")

end

function shot13()
	local excluded_lights_13 = {"BB Omni01", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni06", "BB Omni07", "BB Omni08", "lampA42", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_13, 37, false)

	local included_lights_13 = {"BB Omni02", "lampA37", "BB Omni05", "lampA40", "BB Omni09", "lampA41", "BB Omni10", "BB Omni24", "BB Omni30"}
	light_set_lights(included_lights_13, 9, true)

	teleport_to_slate_pos("CS_vkc", -1.418, 0.0, -1.158, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_13")
	teleport_to_slate_pos("CS_vb", -4.89, 0.0, -13.641, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_13")
	teleport_to_slate_pos("CS_wrb", -2.946, 0.0, -9.915, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_13")
	teleport_to_slate_pos("CS_wrc", -4.773, 0.0, -12.699, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_13")
	teleport_to_slate_pos("CS_vka", -2.902, 0.0, -13.159, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_13")
	set_far_clip(70) 
end

function shot14()
	local excluded_lights_14 = {"BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni30", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_14, 40, false)

	local included_lights_14 = {"BB Omni01", "lampA30", "BB Omni06", "BB Omni25", "BB Omni29", "BB Omni31"}
	light_set_lights(included_lights_14, 6, true)

	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_ho", 8.163, 0.0, -1.46, "slate_TSS_intro")
	play_custom_action_do("CS_ho", "tss_intro_ho_14")
	teleport_to_slate_pos("CS_vkc", 0.079, 0.0, 1.351, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_14")
	teleport_to_slate_pos("CS_vb", -5.03, 0.0, -13.4, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_14")
	teleport_to_slate_pos("#PLAYER#", 9.249, 0.0, -1.504, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_14")
	teleport_to_slate_pos("CS_wra", 6.047, 0.0, -1.741, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_14")
	teleport_to_slate_pos("CS_wrb", -2.97, 0.0, -9.954, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_14")
	teleport_to_slate_pos("CS_wrc", -4.885, 0.0, -12.544, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_14")
	teleport_to_slate_pos("CS_vka", -2.901, 0.0, -13.159, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_14")
	set_far_clip(6)
end

function shot15()
	local excluded_lights_15 = {"BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni26", "BB Omni27", "BB Omni28", "BB Omni30", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_15, 39, false)

	local included_lights_15 = {"BB Omni01", "lampA30", "BB Omni06", "BB Omni25", "lampA45", "BB Omni29", "BB Omni31"}
	light_set_lights(included_lights_15, 7, true)

	teleport_to_slate_pos("CS_ho", 8.435, 0.0, -2.003, "slate_TSS_intro")
	play_custom_action_do("CS_ho", "tss_intro_ho_15")
	teleport_to_slate_pos("CS_vkc", 0.163, 0.0, 1.108, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_15")
	teleport_to_slate_pos("CS_vb", -4.592, 0.0, -13.161, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_15")
	teleport_to_slate_pos("#PLAYER#", 9.382, 0.0, -2.13, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_15")
	teleport_to_slate_pos("CS_wra", 8.51, 0.0, -0.763, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_15")
	teleport_to_slate_pos("CS_wrb", -3.036, 0.0, -9.931, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_15")
	teleport_to_slate_pos("CS_wrc", -4.865, 0.0, -12.538, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_15")
	teleport_to_slate_pos("CS_vka", -2.899, 0.0, -13.139, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_15")
	set_far_clip(6)
end

function shot16()
	local excluded_lights_16 = {"BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni30", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_16, 40, false)

	local included_lights_16 = {"BB Omni01", "lampA30", "BB Omni06", "BB Omni25", "BB Omni29", "BB Omni31"}
	light_set_lights(included_lights_16, 6, true)

	teleport_to_slate_pos("CS_ho", 8.638, 0.0, -2.184, "slate_TSS_intro")
	play_custom_action_do("CS_ho", "tss_intro_ho_16")
	teleport_to_slate_pos("CS_vkc", -2.033, 0.0, -6.878, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_16")
	teleport_to_slate_pos("CS_vb", -4.672, 0.0, -12.596, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_16")
	teleport_to_slate_pos("#PLAYER#", 9.382, 0.0, -2.184, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_16")
	teleport_to_slate_pos("CS_wrb", -3.12, 0.0, -9.922, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_16")
	teleport_to_slate_pos("CS_wrc", -4.896, 0.0, -12.505, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_16")
	teleport_to_slate_pos("CS_vka", -2.902, 0.0, -13.101, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_16")
	set_far_clip(6)
end

function shot17()
	local excluded_lights_17 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_17, 44, false)

	local included_lights_17 = {"lampA41", "BB Omni24"}
	light_set_lights(included_lights_17, 2, true)

	character_hide("#PLAYER#")
	teleport_to_slate_pos("CS_car", -3.787, -0.162, 3.102, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_17")
	teleport_to_slate_pos("CS_vkc", -2.344, 0.0, -7.365, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_17")
	teleport_to_slate_pos("CS_vb", -4.701, 0.0, -13.016, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_17")
	teleport_to_slate_pos("CS_lca", -3.723, 0.0, 3.529, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_17")
	teleport_to_slate_pos("CS_lcb", -3.732, 0.0, 2.598, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_17")
	teleport_to_slate_pos("CS_lcc", -4.685, 0.0, 3.168, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_17")
	teleport_to_slate_pos("CS_wrb", -3.196, 0.0, -9.915, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_17")
	teleport_to_slate_pos("CS_wrc", -4.868, 0.0, -12.501, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_17")
	teleport_to_slate_pos("CS_vka", -2.902, 0.0, -13.079, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_17")
	set_far_clip(5000)
   npc_unholster_best_weapon("CS_troy")
   npc_unholster_best_weapon("CS_vka")
   npc_unholster_best_weapon("CS_vb")
   npc_unholster_best_weapon("CS_lca")
   npc_unholster_best_weapon("CS_lcb")
   npc_unholster_best_weapon("CS_lcc")
   npc_unholster_best_weapon("CS_wrb")
   npc_unholster_best_weapon("CS_wrc")
   
   inv_item_equip("desert eagle","CS_vkc")
   inv_item_equip("ak47","CS_wra")
   
   spawning_remove_all() 


end

function shot18()
	local excluded_lights_18 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_18, 42, false)

	local included_lights_18 = {"lampA37", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_18, 4, true)

	teleport_to_slate_pos("CS_vkc", -2.298, 0.0, -7.531, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_18")
	teleport_to_slate_pos("CS_vb", -4.451, 0.0, -14.147, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_18")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_18")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_18")
	teleport_to_slate_pos("CS_lcc", -4.766, 0.0, 3.218, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_18")
	teleport_to_slate_pos("CS_wrb", -3.243, 0.0, -9.955, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_18")
	teleport_to_slate_pos("CS_wrc", -4.664, 0.0, -13.292, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_18")
	teleport_to_slate_pos("CS_vka", -3.126, 0.0, -12.983, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_18")
	
end

function shot19()
	local excluded_lights_19 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_19, 43, false)

	local included_lights_19 = {"BB Omni09", "lampA41", "BB Omni24"}
	light_set_lights(included_lights_19, 3, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_19")
	teleport_to_slate_pos("CS_vkc", -2.026, 0.0, -7.408, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_19")
	teleport_to_slate_pos("CS_vb", -4.164, 0.0, -14.436, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_19")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_19")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_19")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.22, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_19")
	teleport_to_slate_pos("CS_wrb", -3.266, 0.0, -9.936, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_19")
	teleport_to_slate_pos("CS_wrc", -4.678, 0.0, -13.233, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_19")
	teleport_to_slate_pos("CS_vka", -3.175, 0.0, -13.021, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_19")

end

function shot20()
	local excluded_lights_20 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_20, 41, false)

	local included_lights_20 = {"lampA37", "lampA40", "BB Omni11", "BB Omni30", "BB Omni32"}
	light_set_lights(included_lights_20, 5, true)

	teleport_to_slate_pos("CS_vkc", -2.121, 0.0, -7.692, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_20")
	teleport_to_slate_pos("CS_vb", -4.171, 0.0, -14.503, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_20")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_20")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_20")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.22, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_20")
	teleport_to_slate_pos("CS_wrb", -3.375, 0.0, -10.0, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_20")
	teleport_to_slate_pos("CS_wrc", -4.623, 0.0, -13.343, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_20")
	teleport_to_slate_pos("CS_vka", -3.129, 0.0, -13.101, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_20")
	
end

function shot21()
	local excluded_lights_21 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_21, 41, false)

	local included_lights_21 = {"lampA40", "lampA41", "BB Omni11", "BB Omni24", "BB Omni30"}
	light_set_lights(included_lights_21, 5, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_21")
	teleport_to_slate_pos("CS_vkc", -2.074, 0.0, -7.923, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_21")
	teleport_to_slate_pos("CS_vb", -4.112, 0.0, -14.624, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_21")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_21")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_21")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.22, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_21")
	teleport_to_slate_pos("CS_wrb", -3.486, 0.0, -10.181, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_21")
	teleport_to_slate_pos("CS_wrc", -4.636, 0.0, -13.43, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_21")
	teleport_to_slate_pos("CS_vka", -3.175, 0.0, -13.129, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_21")
	set_far_clip(300)
end

function shot22()
	local excluded_lights_22 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_22, 42, false)

	local included_lights_22 = {"BB Omni03", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_22, 4, true)

	teleport_to_slate_pos("CS_vkc", -2.051, 0.0, -7.997, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_22")
	teleport_to_slate_pos("CS_vb", -3.884, 0.0, -15.045, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_22")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_22")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_22")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.219, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_22")
	teleport_to_slate_pos("CS_wrb", -3.423, 0.0, -10.145, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_22")
	teleport_to_slate_pos("CS_wrc", -4.606, 0.0, -14.164, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_22")
	teleport_to_slate_pos("CS_vka", -3.074, 0.0, -12.911, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_22")
	set_far_clip(5000)
end

function shot23()
	local excluded_lights_23 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_23, 45, false)

	local included_lights_23 = {"BB Omni24"}
	light_set_lights(included_lights_23, 1, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_23")
	teleport_to_slate_pos("CS_vkc", -1.981, 0.0, -8.096, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_23")
	teleport_to_slate_pos("CS_vb", -3.577, 0.0, -15.346, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_23")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_23")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_23")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.218, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_23")
	teleport_to_slate_pos("CS_wrb", -3.472, 0.0, -10.417, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_23")
	teleport_to_slate_pos("CS_wrc", -4.579, 0.0, -14.244, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_23")
	teleport_to_slate_pos("CS_vka", -3.033, 0.0, -12.884, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_23")
	set_far_clip(50)
end

function shot24()
	local excluded_lights_24 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_24, 40, false)

	local included_lights_24 = {"BB Omni03", "lampA37", "lampA40", "BB Omni11", "BB Omni30", "BB Omni32"}
	light_set_lights(included_lights_24, 6, true)

	teleport_to_slate_pos("CS_vkc", -1.954, 0.0, -8.974, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_24")
	teleport_to_slate_pos("CS_vb", -3.021, 0.0, -15.328, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_24")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_24")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_24")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.215, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_24")
	teleport_to_slate_pos("CS_wrb", -3.52, 0.0, -11.069, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_24")
	teleport_to_slate_pos("CS_wrc", -4.603, 0.0, -14.171, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_24")
	teleport_to_slate_pos("CS_vka", -3.044, 0.0, -12.832, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_24")
	set_far_clip(5000)
end

function shot25()
	local excluded_lights_25 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_25, 43, false)

	local included_lights_25 = {"lampA40", "BB Omni11", "BB Omni32"}
	light_set_lights(included_lights_25, 3, true)

	teleport_to_slate_pos("CS_vkc", -2.008, 0.0, -8.7, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_25")
	teleport_to_slate_pos("CS_vb", -2.805, 0.0, -15.324, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_25")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_25")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_25")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.212, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_25")
	teleport_to_slate_pos("CS_wrb", -3.72, 0.0, -11.405, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_25")
	teleport_to_slate_pos("CS_wrc", -4.602, 0.0, -14.167, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_25")
	teleport_to_slate_pos("CS_vka", -2.943, 0.0, -12.926, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_25")

end

function shot26()
	local excluded_lights_26 = {"BB Omni01", "BB Omni02", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_26, 41, false)

	local included_lights_26 = {"BB Omni03", "lampA37", "lampA40", "BB Omni11", "BB Omni30"}
	light_set_lights(included_lights_26, 5, true)

	teleport_to_slate_pos("CS_vkc", -1.907, 0.0, -7.377, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_26")
	teleport_to_slate_pos("CS_vb", -3.153, 0.0, -15.662, "slate_TSS_intro")
	play_custom_action_do("CS_vb", "tss_intro_vb_26")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_26")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_26")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.209, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_26")
	teleport_to_slate_pos("CS_wrb", -3.717, 0.0, -11.405, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_26")
	teleport_to_slate_pos("CS_wrc", -4.602, 0.0, -14.167, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_26")
	teleport_to_slate_pos("CS_vka", -2.968, 0.0, -12.899, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_26")
	
end

function shot27()
	local excluded_lights_27 = {"BB Omni01", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_27, 40, false)

	local included_lights_27 = {"BB Omni02", "BB Omni03", "BB Omni05", "lampA41", "BB Omni24", "BB Omni30"}
	light_set_lights(included_lights_27, 6, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_27")
	teleport_to_slate_pos("CS_vkc", -1.522, 0.0, -6.327, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_27")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_27")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_27")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.206, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_27")
	teleport_to_slate_pos("CS_wrb", -3.714, 0.0, -11.406, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_27")
	teleport_to_slate_pos("CS_wrc", -4.602, 0.0, -14.167, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_27")
	set_far_clip(100)
end

function shot28()
	local excluded_lights_28 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_28, 44, false)

	local included_lights_28 = {"lampA41", "BB Omni24"}
	light_set_lights(included_lights_28, 2, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_28")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_28")
	teleport_to_slate_pos("CS_lcb", -3.447, 0.0, 2.457, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_28")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.204, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_28")
	teleport_to_slate_pos("CS_wrb", -3.715, 0.0, -11.406, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_28")
	teleport_to_slate_pos("CS_wrc", -4.602, 0.0, -14.167, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_28")
	set_far_clip(5000)
end

function shot29()
	local excluded_lights_29 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_29, 44, false)

	local included_lights_29 = {"lampA41", "BB Omni24"}
	light_set_lights(included_lights_29, 2, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_29")
	teleport_to_slate_pos("CS_lca", -3.456, 0.0, 3.385, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_29")
	teleport_to_slate_pos("CS_lcb", -3.477, 0.0, 2.551, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_29")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.203, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_29")
	teleport_to_slate_pos("CS_wrb", -3.715, 0.0, -11.406, "slate_TSS_intro")
	play_custom_action_do("CS_wrb", "tss_intro_wrb_29")
	teleport_to_slate_pos("CS_wrc", -4.602, 0.0, -14.167, "slate_TSS_intro")
	play_custom_action_do("CS_wrc", "tss_intro_wrc_29")
	set_far_clip(50)
end

function shot30()
	local excluded_lights_30 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_30, 43, false)

	local included_lights_30 = {"BB Omni09", "lampA41", "BB Omni24"}
	light_set_lights(included_lights_30, 3, true)

	teleport_to_slate_pos("CS_vkc", -2.195, 0.0, -0.24, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_30")
	teleport_to_slate_pos("CS_lca", -3.454, 0.0, 3.385, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_30")
	teleport_to_slate_pos("CS_lcb", -3.51, 0.0, 2.581, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_30")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.204, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_30")
	set_far_clip(100)
end

function shot31()
	local excluded_lights_31 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_31, 43, false)

	local included_lights_31 = {"BB Omni09", "lampA41", "BB Omni24"}
	light_set_lights(included_lights_31, 3, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_31")
	teleport_to_slate_pos("CS_vkc", -2.952, 0.0, 0.346, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_31")
	teleport_to_slate_pos("CS_lca", -3.453, 0.0, 3.385, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_31")
	teleport_to_slate_pos("CS_lcb", -3.504, 0.0, 2.588, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_31")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.206, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_31")
	set_far_clip(100)	
end

function shot32()
	local excluded_lights_32 = {"BB Omni01", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA36", "lampA37", "lampA38", "BB Omni06", "BB Omni07", "BB Omni08", "lampA42", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_32, 38, false)

	local included_lights_32 = {"BB Omni02", "lampA35", "BB Omni05", "lampA40", "BB Omni09", "lampA41", "BB Omni10", "BB Omni24"}
	light_set_lights(included_lights_32, 8, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_32")
	teleport_to_slate_pos("CS_vkc", -3.015, 0.0, 0.277, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_32")
	teleport_to_slate_pos("CS_lca", -3.452, 0.0, 3.385, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_32")
	teleport_to_slate_pos("CS_lcb", -3.493, 0.0, 2.576, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_32")
	teleport_to_slate_pos("CS_lcc", -4.701, 0.0, 3.21, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_32")
	set_far_clip(100)
end

function shot33()
	local excluded_lights_33 = {"BB Omni01", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_33, 42, false)

	local included_lights_33 = {"BB Omni02", "BB Omni09", "lampA41", "BB Omni24"}
	light_set_lights(included_lights_33, 4, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_33")
	teleport_to_slate_pos("CS_vkc", -2.992, 0.0, -0.269, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_33")
	teleport_to_slate_pos("CS_lca", -3.451, 0.0, 3.385, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_33")
	teleport_to_slate_pos("CS_lcb", -3.419, 0.0, 2.579, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_33")
	teleport_to_slate_pos("CS_lcc", -4.704, 0.0, 3.391, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_33")
	set_far_clip(50)
end

function shot34()
	local excluded_lights_34 = {"BB Omni01", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_34, 42, false)

	local included_lights_34 = {"BB Omni02", "BB Omni09", "lampA41", "BB Omni24"}
	light_set_lights(included_lights_34, 4, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_34")
	teleport_to_slate_pos("CS_vkc", -3.115, 0.0, -1.038, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_34")
	teleport_to_slate_pos("CS_lca", -3.451, 0.0, 3.385, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_34")
	teleport_to_slate_pos("CS_lcb", -3.419, 0.0, 2.579, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_34")
	teleport_to_slate_pos("CS_lcc", -4.704, 0.0, 3.4, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_34")
	set_far_clip(5000)
end

function shot35()
	local excluded_lights_35 = {"BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni23", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_35, 39, false)

	local included_lights_35 = {"BB Omni01", "lampA30", "BB Omni06", "lampA41", "BB Omni20", "BB Omni24", "BB Omni25"}
	light_set_lights(included_lights_35, 7, true)

	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_35")
	teleport_to_slate_pos("CS_ho", 7.553, 0.0, -1.489, "slate_TSS_intro")
	play_custom_action_do("CS_ho", "tss_intro_ho_35")
	teleport_to_slate_pos("#PLAYER#", 9.069, 0.0, -1.365, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_35")
	teleport_to_slate_pos("CS_lca", -3.46, 0.0, 3.384, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_35")
	teleport_to_slate_pos("CS_lcb", -3.419, 0.0, 2.579, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_35")
	teleport_to_slate_pos("CS_lcc", -4.703, 0.0, 3.401, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_35")
	teleport_to_slate_pos("CS_wra", 10.615, 0.0, -1.579, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_35")
	
end

function shot36()
	local excluded_lights_36 = {"BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_36, 41, false)

	local included_lights_36 = {"BB Omni01", "lampA34", "BB Omni06", "BB Omni25", "BB Omni31"}
	light_set_lights(included_lights_36, 5, true)

	character_hide("#PLAYER#")
	teleport_to_slate_pos("CS_ho", 7.598, 0.0, 1.445, "slate_TSS_intro")
	play_custom_action_do("CS_ho", "tss_intro_ho_36")
	teleport_to_slate_pos("CS_lca", -3.488, 0.0, 3.383, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_36")
	teleport_to_slate_pos("CS_lcb", -3.419, 0.0, 2.579, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_36")
	teleport_to_slate_pos("CS_lcc", -4.694, 0.0, 3.438, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_36")
	teleport_to_slate_pos("CS_wra", 7.587, 0.0, -1.303, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_36")
	
end

function shot37()
	local excluded_lights_37 = {"BB Omni01", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA37", "lampA38", "BB Omni05", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni25", "BB Omni26", "BB Omni27", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_37, 35, false)

	local included_lights_37 = {"BB Omni02", "lampA34", "lampA35", "lampA36", "BB Omni06", "lampA41", "lampA44", "BB Omni18", "BB Omni24", "BB Omni28", "BB FreeSpot02"}
	light_set_lights(included_lights_37, 11, true)

	teleport_to_slate_pos("CS_car", -3.564, -0.162, 2.946, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_37")
	teleport_to_slate_pos("CS_ho", 7.989, 0.0, 7.388, "slate_TSS_intro")
	play_custom_action_do("CS_ho", "tss_intro_ho_37")
	teleport_to_slate_pos("CS_vkc", -2.58, 0.0, -1.354, "slate_TSS_intro")
	play_custom_action_do("CS_vkc", "tss_intro_vkc_37")
	teleport_to_slate_pos("CS_lca", -3.517, 0.0, 3.382, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_37")
	teleport_to_slate_pos("CS_lcb", -3.419, 0.0, 2.579, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_37")
	teleport_to_slate_pos("CS_lcc", -4.687, 0.0, 3.468, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_37")
	teleport_to_slate_pos("CS_wra", 7.453, 0.0, -1.361, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_37")
	
end

function shot38()
	local excluded_lights_38 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_38, 44, false)

	local included_lights_38 = {"BB Omni13", "BB Omni23"}
	light_set_lights(included_lights_38, 2, true)

	teleport_to_slate_pos("CS_car", 17.895, -0.162, 10.304, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_38")
	teleport_to_slate_pos("CS_lca", 17.982, 0.0, 10.74, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_38")
	teleport_to_slate_pos("CS_lcb", 18.041, 0.0, 9.937, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_38")
	teleport_to_slate_pos("CS_lcc", 16.787, 0.0, 10.845, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_38")
	set_far_clip(50)
end

function shot39()
	local excluded_lights_39 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "BB Omni10", "BB Omni11", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(excluded_lights_39, 41, false)

	local included_lights_39 = {"lampA31", "lampA42", "BB Omni12", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(included_lights_39, 5, true)

	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_car", 33.06, -0.162, 15.255, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_39")
	teleport_to_slate_pos("#PLAYER#", 32.661, 0.0, 16.355, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_39")
	teleport_to_slate_pos("CS_lca", 33.009, 0.0, 15.662, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_39")
	teleport_to_slate_pos("CS_lcb", 33.263, 0.0, 14.916, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_39")
	teleport_to_slate_pos("CS_lcc", 31.887, 0.0, 15.617, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_39")
	set_far_clip(100)
end

function shot40()
	local excluded_lights_40 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_40, 45, false)

	local included_lights_40 = {"lampA31"}
	light_set_lights(included_lights_40, 1, true)

	character_hide("#PLAYER#")
	teleport_to_slate_pos("CS_car", 39.215, -0.162, 17.954, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_40")
	teleport_to_slate_pos("CS_lca", 39.353, 0.0, 18.346, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_40")
	teleport_to_slate_pos("CS_lcb", 39.251, 0.0, 17.554, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_40")
	teleport_to_slate_pos("CS_lcc", 38.23, 0.0, 18.972, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_40")
	set_far_clip(5000)
end

function shot41()
	local excluded_lights_41 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_41, 43, false)

	local included_lights_41 = {"BB Omni12", "BB Omni13", "BB Omni26"}
	light_set_lights(included_lights_41, 3, true)

	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_car", 39.318, -0.162, 17.989, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_41")
	teleport_to_slate_pos("#PLAYER#", 32.044, 0.0, 21.861, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_41")
	teleport_to_slate_pos("CS_lca", 39.492, 0.0, 18.373, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_41")
	teleport_to_slate_pos("CS_lcb", 39.379, 0.0, 17.598, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_41")
	teleport_to_slate_pos("CS_lcc", 38.286, 0.0, 19.743, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_41")
	set_far_clip(150)
end

function shot42()
	local excluded_lights_42 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_42, 43, false)

	local included_lights_42 = {"lampA31", "lampA32", "BB Omni26"}
	light_set_lights(included_lights_42, 3, true)

	character_hide("#PLAYER#")
	teleport_to_slate_pos("CS_car", 39.318, -0.162, 17.989, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_42")
	teleport_to_slate_pos("CS_lca", 39.492, 0.0, 18.373, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_42")
	teleport_to_slate_pos("CS_lcb", 39.379, 0.0, 17.598, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_42")
	teleport_to_slate_pos("CS_lcc", 38.276, 0.0, 19.74, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_42")
	teleport_to_slate_pos("CS_wra", 7.194, 0.0, -0.943, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_42")
	set_far_clip(140)
end

function shot43()
	local excluded_lights_43 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_43, 42, false)

	local included_lights_43 = {"lampA31", "BB Omni07", "BB Omni12", "BB Omni26"}
	light_set_lights(included_lights_43, 4, true)

	teleport_to_slate_pos("CS_car", 39.318, -0.162, 17.989, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_43")
	teleport_to_slate_pos("CS_lcb", 39.379, 0.0, 17.598, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_43")
	teleport_to_slate_pos("CS_lcc", 38.209, 0.0, 19.726, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_43")
	teleport_to_slate_pos("CS_wra", 34.507, 0.0, 18.396, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_43")
	set_far_clip(20)
end

function shot44()
	local excluded_lights_44 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "BB Omni10", "BB Omni11", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_44, 42, false)

	local included_lights_44 = {"BB Omni07", "lampA42", "BB Omni12", "BB Omni13"}
	light_set_lights(included_lights_44, 4, true)

	teleport_to_slate_pos("CS_lcc", 38.283, 0.0, 19.743, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_44")
	teleport_to_slate_pos("CS_wra", 34.962, 0.0, 18.967, "slate_TSS_intro")
	play_custom_action_do("CS_wra", "tss_intro_wra_44")
	teleport_to_slate_pos("CS_vka", -3.749, 0.0, -9.359, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_44")
	set_far_clip(5000)
end

function shot45()
	local excluded_lights_45 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_45, 44, false)

	local included_lights_45 = {"BB Omni12", "BB Omni13"}
	light_set_lights(included_lights_45, 2, true)

	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_julius", 32.014, 0.0, 35.576, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_45")
	teleport_to_slate_pos("CS_troy", 33.409, 0.0, 36.969, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_45")
	teleport_to_slate_pos("#PLAYER#", 32.021, 0.0, 21.806, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_45")
	teleport_to_slate_pos("CS_lcc", 38.283, 0.0, 19.743, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_45")
	teleport_to_slate_pos("CS_vka", 33.544, 0.0, 19.68, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_45")
	fat_bones_enable("#PLAYER#", false)
	
end

function shot46()
	local excluded_lights_46 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "BB Omni10", "BB Omni11", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_46, 41, false)

	local included_lights_46 = {"lampA42", "BB Omni12", "BB Omni13", "BB Omni14", "BB Omni26"}
	light_set_lights(included_lights_46, 5, true)

	character_hide("#PLAYER#")
	teleport_to_slate_pos("CS_julius", 31.953, 0.0, 35.227, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_46")
	teleport_to_slate_pos("CS_troy", 33.34, 0.0, 36.572, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_46")
	teleport_to_slate_pos("CS_lcc", 38.283, 0.0, 19.743, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_46")
	teleport_to_slate_pos("CS_vka", 33.047, 0.0, 20.747, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_46")

	delay(1)
	fade_out(0.5)
	delay(2.2)
	fade_in(0.5)
	character_hide("CS_lcb")
	character_hide("CS_lca")
end

function shot47()
	local excluded_lights_47 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_47, 43, false)

	local included_lights_47 = {"BB Omni13", "BB Omni14", "BB Omni23"}
	light_set_lights(included_lights_47, 3, true)

	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_car", 39.318, -0.162, 17.989, "slate_TSS_intro")
	play_custom_action_do("CS_car", "tss_intro_car_47")
	teleport_to_slate_pos("CS_julius", 32.032, 0.0, 21.178, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_47")
	teleport_to_slate_pos("CS_troy", 32.448, 0.0, 19.777, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_47")
	teleport_to_slate_pos("#PLAYER#", 31.876, 0.0, 21.949, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_47")
	teleport_to_slate_pos("CS_lca", 39.492, 0.0, 18.373, "slate_TSS_intro")
	play_custom_action_do("CS_lca", "tss_intro_lca_47")
	teleport_to_slate_pos("CS_lcb", 39.379, 0.0, 17.598, "slate_TSS_intro")
	play_custom_action_do("CS_lcb", "tss_intro_lcb_47")
	teleport_to_slate_pos("CS_lcc", 38.283, 0.0, 19.743, "slate_TSS_intro")
	play_custom_action_do("CS_lcc", "tss_intro_lcc_47")
	teleport_to_slate_pos("CS_vka", 34.266, 0.0, 21.838, "slate_TSS_intro")
	play_custom_action_do("CS_vka", "tss_intro_vka_47")
	set_far_clip(1000)
	fat_bones_enable("#PLAYER#", true)
end

function shot48()
	local excluded_lights_48 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32"}
	light_set_lights(excluded_lights_48, 41, false)

	local included_lights_48 = {"lampA44", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(included_lights_48, 5, true)

	teleport_to_slate_pos("CS_julius", 6.413, 0.0, 23.928, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_48")
	teleport_to_slate_pos("CS_troy", 8.675, 0.0, 22.48, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_48")
	teleport_to_slate_pos("#PLAYER#", 6.393, 0.0, 23.507, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_48")
	set_far_clip(5000)	
end

function shot49()
	local excluded_lights_49 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot02"}
	light_set_lights(excluded_lights_49, 42, false)

	local included_lights_49 = {"lampA44", "BB FreeSpot01", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(included_lights_49, 4, true)

	teleport_to_slate_pos("CS_julius", 2.775, 0.0, 24.039, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_49")
	teleport_to_slate_pos("CS_troy", 4.756, 0.0, 23.219, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_49")
	teleport_to_slate_pos("#PLAYER#", 2.187, 0.0, 23.563, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_49")
	
end

function shot50()
	local excluded_lights_50 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_50, 42, false)

	local included_lights_50 = {"BB Omni28", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15"}
	light_set_lights(included_lights_50, 4, true)

	teleport_to_slate_pos("CS_julius", 2.749, 0.0, 24.215, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_50")
	teleport_to_slate_pos("CS_troy", 4.043, 0.0, 23.615, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_50")
	teleport_to_slate_pos("#PLAYER#", 1.814, 0.0, 23.723, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_50")

end

function shot51()
	local excluded_lights_51 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB FreeSpot02"}
	light_set_lights(excluded_lights_51, 42, false)

	local included_lights_51 = {"lampA44", "BB FreeSpot01", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(included_lights_51, 4, true)

	teleport_to_slate_pos("CS_julius", 2.755, 0.0, 24.264, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_51")
	teleport_to_slate_pos("CS_troy", 3.704, 0.0, 23.83, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_51")
	teleport_to_slate_pos("#PLAYER#", 1.81, 0.0, 23.719, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_51")
	
end

function shot52()
	local excluded_lights_52 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_52, 42, false)

	local included_lights_52 = {"BB Omni28", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15"}
	light_set_lights(included_lights_52, 4, true)

	teleport_to_slate_pos("CS_julius", 2.747, 0.0, 24.231, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_52")
	teleport_to_slate_pos("CS_troy", 3.674, 0.0, 23.973, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_52")
	teleport_to_slate_pos("#PLAYER#", 1.805, 0.0, 23.722, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_52")
	
end

function shot53()
	local excluded_lights_53 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "BB Omni28", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32"}
	light_set_lights(excluded_lights_53, 41, false)

	local included_lights_53 = {"lampA44", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15", "BB Player FreeSpot03"}
	light_set_lights(included_lights_53, 5, true)

	teleport_to_slate_pos("CS_julius", 2.736, 0.0, 24.23, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_53")
	teleport_to_slate_pos("CS_troy", 3.66, 0.0, 23.812, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_53")
	teleport_to_slate_pos("#PLAYER#", 1.811, 0.0, 23.719, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_53")
	
end

function shot54()
	local excluded_lights_54 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni04", "lampA28", "lampA30", "lampA31", "lampA32", "lampA33", "lampA34", "lampA35", "lampA36", "lampA37", "lampA38", "BB Omni05", "BB Omni06", "BB Omni07", "BB Omni08", "lampA40", "BB Omni09", "lampA41", "lampA42", "BB Omni10", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni14", "lampA44", "BB Omni18", "BB Omni19", "BB Omni20", "BB Omni23", "BB Omni24", "BB Omni25", "BB Omni26", "BB Omni27", "lampA45", "BB Omni29", "BB Omni30", "BB Omni31", "BB Omni32", "BB Player FreeSpot03"}
	light_set_lights(excluded_lights_54, 42, false)

	local included_lights_54 = {"BB Omni28", "BB FreeSpot01", "BB FreeSpot02", "BB Omni15"}
	light_set_lights(included_lights_54, 4, true)

	teleport_to_slate_pos("CS_julius", 2.748, 0.0, 24.24, "slate_TSS_intro")
	play_custom_action_do("CS_julius", "tss_intro_julius_54")
	teleport_to_slate_pos("CS_troy", 3.673, 0.0, 23.878, "slate_TSS_intro")
	play_custom_action_do("CS_troy", "tss_intro_troy_54")
	teleport_to_slate_pos("#PLAYER#", 1.808, 0.0, 23.72, "slate_TSS_intro")
	play_custom_action_do("#PLAYER#", "tss_intro_player_54")
	delay(7.66667)
	fade_out(0.5)
 	--lay(7.6)
	--de_out(0.5)

end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
	set_far_clip(5000)
	spawning_on()
	set_level_lights(true)
	set_time_of_day(9, 0)
	fat_bones_enable("#PLAYER#", true)
end

function cutscene_end()
	character_show("#PLAYER#")
	stop_custom_actions("CS_car")
	stop_custom_actions("CS_ho")
	stop_custom_actions("CS_hustler")
	stop_custom_actions("CS_julius")
	stop_custom_actions("CS_troy")
	stop_custom_actions("CS_vkc")
	stop_custom_actions("CS_vb")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_lca")
	stop_custom_actions("CS_lcb")
	stop_custom_actions("CS_lcc")
	stop_custom_actions("CS_wra")
	stop_custom_actions("CS_wrb")
	stop_custom_actions("CS_wrc")
	stop_custom_actions("CS_vka")
	letterbox_fade_out(true)
	fade_out(0.5)
	set_far_clip(5000)
	spawning_on()
	set_level_lights(true)
	set_time_of_day(9, 0)
	fat_bones_enable("#PLAYER#", true)
end

function scripted_event1()
	local walker01 = {"CS_pathNav-walker01-01_1"}
	move_to("CS_walker01", walker01, 1)
end

function scripted_event2()
	local walker02 = {"CS_pathNav-walker02-01_1"}
	move_to("CS_walker02", walker02, 1)
end

function scripted_event3()
	teleport("CS_ho02", "CS_Charnav-ho02_1")
	play_action_sequence("CS_ho02", "stand")
end

function scripted_event4()
	teleport("CS_stander01", "CS_Charnav-stander01_1")
	play_action_sequence("CS_stander01", "drunk stand", "talk yell")
end

function scripted_event5()
	local walker03 = {"CS_pathNav-walker03-01_1"}
	move_to("CS_walker03", walker03, 3)
end

function scripted_event6()
	teleport("CS_ho03", "CS_Charnav-ho03_1")
	play_action_sequence("CS_ho03", "stand", "idle flirt")
end

function scripted_event7()
	teleport("CS_ho04", "CS_Charnav-ho04_1")
	play_action_sequence("CS_ho04", "stand", "idle Fix Hair")
end

function scripted_event8()
	teleport("CS_stander02", "CS_Charnav-stander02_1")
	play_action_sequence("CS_stander02", "angry stand")
end

function scripted_event9()
	teleport("CS_stander03", "CS_Charnav-stander03_1")
	play_action_sequence("CS_stander03", "drunk stand")
end
