-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vandalism_highend\vandalism_highend.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk37b_NC__interiors.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	load_chunk("sr_chunk37b_NC", true )
	select_slate("slate_vand_highend")
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function shot8()
end

function cutscene_abort()
end

function cutscene_end()
end
