-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vandalism_highend\vandalism_highend.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk37b__interiors.cts
-------------------------------------


function cutscene_main()
	load_chunk("sr_chunk37b_nc", true)
	time_of_day_lights_enable(false)
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function shot8()
end

function cutscene_abort()
	time_of_day_lights_enable(true)
end

function cutscene_end()
	time_of_day_lights_enable(false)
end
