---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: vandalism_wrsuburbs
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk39", true)
	load_chunks("sr_chunk39_nc", "sr_chunk39")
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
end

function shot1()
	local excluded_lights_1 = {"glitz_Omni09", "glitz_Omni11", "glitz_Omni12", "glitz_Omni13", "glitz_Omni14", "glitz_Omni16", "glitz_Omni19"}
	light_set_lights(excluded_lights_1, 7, false)

	local included_lights_1 = {"glitz_Omni08", "glitz_Omni10", "glitz_Omni15", "glitz_Omni21", "glitz_Omni22", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(included_lights_1, 7, true)

	fade_in(0.5)
	select_slate("slate_popclub")
	character_show("#PLAYER#")
	teleport_to_slate_pos("#PLAYER#", -2.953, 0.0, -0.84, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_1")
	teleport_to_slate_pos("CS_jackson", -2.102, 0.0, -0.33, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_1")
	teleport_to_slate_pos("CS_reno", 2.793, 0.0, 1.869, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_1")
	teleport_to_slate_pos("CS_skinnyHoA", 2.315, 0.0, 2.356, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_1")
	teleport_to_slate_pos("CS_skinnyHoB", 3.127, 0.0, 1.434, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_1")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_1")
	set_level_lights(false)
end

function shot2()
	local excluded_lights_2 = {"glitz_Omni09", "glitz_Omni10", "glitz_Omni11", "glitz_Omni12", "glitz_Omni13", "glitz_Omni14", "glitz_Omni15", "glitz_Omni16", "glitz_Omni19", "glitz_Omni21"}
	light_set_lights(excluded_lights_2, 10, false)

	local included_lights_2 = {"glitz_Omni08", "glitz_Omni22", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(included_lights_2, 4, true)

	teleport_to_slate_pos("#PLAYER#", -2.994, 0.0, -0.744, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_2")
	teleport_to_slate_pos("CS_jackson", -2.041, 0.0, -0.243, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_2")
	teleport_to_slate_pos("CS_reno", 2.795, 0.0, 1.867, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_2")
	teleport_to_slate_pos("CS_skinnyHoA", 2.381, 0.0, 2.293, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_2")
	teleport_to_slate_pos("CS_skinnyHoB", 3.05, 0.0, 1.38, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_2")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_2")
end

function shot3()
	local excluded_lights_3 = {"glitz_Omni09", "glitz_Omni12", "glitz_Omni14", "glitz_Omni15", "glitz_Omni16", "glitz_Omni19", "glitz_Omni21", "BB FreeSpot01"}
	light_set_lights(excluded_lights_3, 8, false)

	local included_lights_3 = {"glitz_Omni08", "glitz_Omni10", "glitz_Omni11", "glitz_Omni13", "glitz_Omni22", "BB FreeSpot02"}
	light_set_lights(included_lights_3, 6, true)

	teleport_to_slate_pos("#PLAYER#", -1.569, 0.0, -0.25, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_3")
	teleport_to_slate_pos("CS_jackson", -0.5, 0.0, 0.633, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_3")
	teleport_to_slate_pos("CS_reno", 2.795, 0.0, 1.871, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_3")
	teleport_to_slate_pos("CS_skinnyHoA", 2.385, 0.0, 2.296, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_3")
	teleport_to_slate_pos("CS_skinnyHoB", 3.053, 0.0, 1.381, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_3")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_3")
end

function shot4()
	local excluded_lights_4 = {"glitz_Omni08", "glitz_Omni09", "glitz_Omni11", "glitz_Omni12", "glitz_Omni14", "glitz_Omni15", "glitz_Omni16", "glitz_Omni19", "glitz_Omni21"}
	light_set_lights(excluded_lights_4, 9, false)

	local included_lights_4 = {"glitz_Omni10", "glitz_Omni13", "glitz_Omni22", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(included_lights_4, 5, true)

	teleport_to_slate_pos("#PLAYER#", 0.475, 0.0, 0.234, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_4")
	teleport_to_slate_pos("CS_jackson", 0.359, 0.0, 1.188, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_4")
	teleport_to_slate_pos("CS_reno", 2.794, 0.0, 1.868, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_4")
	teleport_to_slate_pos("CS_skinnyHoA", 2.385, 0.0, 2.295, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_4")
	teleport_to_slate_pos("CS_skinnyHoB", 3.051, 0.0, 1.38, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_4")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_4")
end

function shot5()
	local excluded_lights_5 = {"glitz_Omni09", "glitz_Omni10", "glitz_Omni13", "glitz_Omni14", "glitz_Omni15", "glitz_Omni16", "glitz_Omni19"}
	light_set_lights(excluded_lights_5, 7, false)

	local included_lights_5 = {"glitz_Omni08", "glitz_Omni11", "glitz_Omni12", "glitz_Omni21", "glitz_Omni22", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(included_lights_5, 7, true)

	teleport_to_slate_pos("#PLAYER#", 0.489, 0.0, 0.244, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_5")
	teleport_to_slate_pos("CS_jackson", 0.439, 0.0, 1.799, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_5")
	teleport_to_slate_pos("CS_reno", 2.679, 0.0, 1.75, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_5")
	teleport_to_slate_pos("CS_skinnyHoA", 2.373, 0.0, 2.323, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_5")
	teleport_to_slate_pos("CS_skinnyHoB", 3.109, 0.0, 1.381, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_5")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_5")
	thread_new("scripted_event3", 3)
	thread_new("scripted_event4", 4)
end

function shot6()
	local excluded_lights_6 = {"glitz_Omni08", "glitz_Omni09", "glitz_Omni12", "glitz_Omni14", "glitz_Omni15", "glitz_Omni16", "glitz_Omni19", "glitz_Omni21"}
	light_set_lights(excluded_lights_6, 8, false)

	local included_lights_6 = {"glitz_Omni10", "glitz_Omni11", "glitz_Omni13", "glitz_Omni22", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(included_lights_6, 6, true)

	teleport_to_slate_pos("#PLAYER#", 0.484, 0.0, 0.242, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_6")
	teleport_to_slate_pos("CS_jackson", 0.446, 0.0, 1.802, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_6")
	teleport_to_slate_pos("CS_reno", 2.472, 0.0, 1.753, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_6")
	teleport_to_slate_pos("CS_skinnyHoA", 2.376, 0.0, 2.319, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_6")
	teleport_to_slate_pos("CS_skinnyHoB", 3.112, 0.0, 1.381, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_6")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_6")
end

function shot7()
	local excluded_lights_7 = {"glitz_Omni09", "glitz_Omni12", "glitz_Omni13", "glitz_Omni14", "glitz_Omni15", "glitz_Omni19"}
	light_set_lights(excluded_lights_7, 6, false)

	local included_lights_7 = {"glitz_Omni08", "glitz_Omni10", "glitz_Omni11", "glitz_Omni16", "glitz_Omni21", "glitz_Omni22", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(included_lights_7, 8, true)

	teleport_to_slate_pos("#PLAYER#", 0.484, 0.0, 0.252, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_7")
	teleport_to_slate_pos("CS_jackson", 0.452, 0.0, 1.779, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_7")
	teleport_to_slate_pos("CS_reno", 1.296, 0.0, 0.965, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_7")
	teleport_to_slate_pos("CS_skinnyHoA", 2.459, 0.0, 2.296, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_7")
	teleport_to_slate_pos("CS_skinnyHoB", 3.094, 0.0, 1.396, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_7")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_7")
end

function shot8()
	local excluded_lights_8 = {"glitz_Omni09", "glitz_Omni12", "glitz_Omni13", "glitz_Omni14", "glitz_Omni15", "glitz_Omni16", "glitz_Omni19", "glitz_Omni21"}
	light_set_lights(excluded_lights_8, 8, false)

	local included_lights_8 = {"glitz_Omni08", "glitz_Omni10", "glitz_Omni11", "glitz_Omni22", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(included_lights_8, 6, true)

	teleport_to_slate_pos("#PLAYER#", 0.467, 0.0, 0.231, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_8")
	teleport_to_slate_pos("CS_jackson", 0.438, 0.0, 1.774, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_8")
	teleport_to_slate_pos("CS_reno", 1.265, 0.0, 0.578, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_8")
	teleport_to_slate_pos("CS_skinnyHoA", 2.461, 0.0, 2.295, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_8")
	teleport_to_slate_pos("CS_skinnyHoB", 3.083, 0.0, 1.399, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_8")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_8")
end

function shot9()
	local excluded_lights_9 = {"glitz_Omni10", "glitz_Omni13", "glitz_Omni14", "glitz_Omni15", "glitz_Omni16", "glitz_Omni19", "glitz_Omni21", "BB FreeSpot02"}
	light_set_lights(excluded_lights_9, 8, false)

	local included_lights_9 = {"glitz_Omni08", "glitz_Omni09", "glitz_Omni11", "glitz_Omni12", "glitz_Omni22", "BB FreeSpot01"}
	light_set_lights(included_lights_9, 6, true)

	teleport_to_slate_pos("#PLAYER#", 0.46, 0.0, 0.25, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_9")
	teleport_to_slate_pos("CS_jackson", 0.434, 0.0, 1.776, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_9")
	teleport_to_slate_pos("CS_reno", 1.218, 0.0, 0.565, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_9")
	teleport_to_slate_pos("CS_skinnyHoA", 2.483, 0.0, 2.407, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_9")
	teleport_to_slate_pos("CS_skinnyHoB", 2.918, 0.0, 1.053, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_9")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_9")
	character_hide("CS_reno")
end

function shot10()
	local excluded_lights_10 = {"glitz_Omni09", "glitz_Omni12", "glitz_Omni13", "glitz_Omni14", "glitz_Omni15", "glitz_Omni16", "glitz_Omni19", "glitz_Omni21"}
	light_set_lights(excluded_lights_10, 8, false)

	local included_lights_10 = {"glitz_Omni08", "glitz_Omni10", "glitz_Omni11", "glitz_Omni22", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(included_lights_10, 6, true)

	teleport_to_slate_pos("#PLAYER#", 0.457, 0.0, 0.254, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_10")
	teleport_to_slate_pos("CS_jackson", 0.435, 0.0, 1.777, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_10")
	teleport_to_slate_pos("CS_reno", 1.209, 0.0, 0.624, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_10")
	teleport_to_slate_pos("CS_skinnyHoA", 2.543, 0.0, 2.369, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_10")
	teleport_to_slate_pos("CS_skinnyHoB", 2.908, 0.0, 1.072, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_10")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_10")
	character_show("CS_reno")
end

function shot11()
	local excluded_lights_11 = {"glitz_Omni09", "glitz_Omni12", "glitz_Omni13", "glitz_Omni14", "glitz_Omni15", "glitz_Omni16", "glitz_Omni19", "glitz_Omni21"}
	light_set_lights(excluded_lights_11, 8, false)

	local included_lights_11 = {"glitz_Omni08", "glitz_Omni10", "glitz_Omni11", "glitz_Omni22", "BB FreeSpot01", "BB FreeSpot02"}
	light_set_lights(included_lights_11, 6, true)

	teleport_to_slate_pos("#PLAYER#", 0.468, 0.0, 0.287, "slate_popclub")
	play_custom_action_do("#PLAYER#", "vandalism_wrsuburbs_pc_11")
	teleport_to_slate_pos("CS_jackson", 0.435, 0.0, 1.777, "slate_popclub")
	play_custom_action_do("CS_jackson", "vandalism_wrsuburbs_ja_11")
	teleport_to_slate_pos("CS_reno", 1.245, 0.0, 0.542, "slate_popclub")
	play_custom_action_do("CS_reno", "vandalism_wrsuburbs_reno_11")
	teleport_to_slate_pos("CS_skinnyHoA", 2.553, 0.0, 2.374, "slate_popclub")
	play_custom_action_do("CS_skinnyHoA", "vandalism_wrsuburbs_wa_11")
	teleport_to_slate_pos("CS_skinnyHoB", 2.897, 0.0, 1.075, "slate_popclub")
	play_custom_action_do("CS_skinnyHoB", "vandalism_wrsuburbs_wb_11")
	teleport_to_slate_pos("CS_table", 2.145, 0.0, 0.395, "slate_popclub")
	play_custom_action_do("CS_table", "vandalism_wrsuburbs_table_11")
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
end

function cutscene_end()
	character_show("#PLAYER#")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_jackson")
	stop_custom_actions("CS_reno")
	stop_custom_actions("CS_skinnyHoA")
	stop_custom_actions("CS_skinnyHoB")
	stop_custom_actions("CS_table")
	letterbox_fade_out(true)
	fade_out(0.5)
end

function scripted_event3()
	teleport("CS_walker03", "CS_CSCharnav-walker03_1")
	play_action_sequence("CS_walker03", "talk confrontational")
end

function scripted_event4()
	teleport("CS_stander01", "CS_CSCharnav-stander01_1")
	play_action_sequence("CS_stander01", "talk yell")
end
