-- /////////////////////////////////////////////////////////////
--                Code generated by LUA Cutscene Editor
--                      Version: 0.2b
--                      Date: 4/19/2006 10:53:44 AM
--                      Author: Ev.Religioso
-- Cutscene:D:\projects\blingbling\data\cutscenes\vandalism_highend\vandalism_highend.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk37b__interiors.cts
-- /////////////////////////////////////////////////////////////

function cutscene_main()
end

function shot1()
	pvs_enable(false)
	spawning_remove_all()
	thread_new("scripted_event1", 1)
	thread_new("scripted_event2", 2)
	thread_new("scripted_event3", 3)
	thread_new("scripted_event4", 4)
	thread_new("scripted_event5", 5)
	set_level_lights(false)
	character_hide("CS_walker01")
	character_hide("CS_sitter01")
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function shot8()
	spawning_on()
end

function cutscene_abort()
	spawning_on()
end

function cutscene_end()
end

function scripted_event1()
	teleport("CS_dancer01", "CS_charnav-dancer-01_1")
	play_action_sequence("CS_dancer01", "dance b")
end

function scripted_event2()
	teleport("CS_dancer02", "CS_charnav-dancer-02_1")
	play_action_sequence("CS_dancer02", "dance a")
end

function scripted_event3()
	teleport("CS_sitter01", "CS_charnav-sitter-01_1")
	play_action_sequence("CS_sitter01", "sitting", "Sitting Eating")
end

function scripted_event4()
	teleport("CS_sitter02", "CS_charnav-sitter-02_1")
	play_action_sequence("CS_sitter02", "sitting")
end

function scripted_event5()
	teleport("CS_sitter03", "CS_charnav-sitter-03_1")
	play_action_sequence("CS_sitter03", "sitting")
end
