-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vandalism_trainyard\vandalism_trainyard.cts
-- Level:D:\projects\blingbling\data\test\cutscene_vandalism_trainyard.cts
-------------------------------------


function cutscene_main()
	load_chunk("sr_chunk13_nc", true )
	time_of_day_lights_enable(false)
end

function shot1()
	character_hide("CS_ho")
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
	character_show("CS_ho")
end

function shot6()
end

function shot7()
end

function shot8()
end

function shot9()
end

function shot10()
end

function shot11()
end

function cutscene_abort()
	time_of_day_lights_enable(true)
end

function cutscene_end()
	time_of_day_lights_enable(true)
end
