---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: vk01_scene01
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk02", true )
	load_chunks("sr_chunk02_church", "sr_chunk02")
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
	thread_new_cutscene_shot("shot12", 12)
	thread_new_cutscene_shot("shot13", 13)
	thread_new_cutscene_shot("shot14", 14)
	thread_new_cutscene_shot("shot15", 15)
	thread_new_cutscene_shot("shot16", 16)
end

function shot1()
	local excluded_lights_1 = {"CH_FreeSpot01", "BB Omni01", "BB Omni04"}
	light_set_lights(excluded_lights_1, 3, false)

	local included_lights_1 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni02", "BB Omni03", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_1, 6, true)

	fade_in(0.5)
	select_slate("slate_church_johnnyroom")
	character_show("#PLAYER#")
	teleport_to_slate_pos("#PLAYER#", -1.359, 0.0, 0.281, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_1")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_1")
	teleport_to_slate_pos("CS_dex", -2.451, 0.0, -5.596, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_1")
	teleport_to_slate_pos("CS_WoodChair", -2.636, 0.0, -2.88, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_1")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_1")
	set_level_lights(false)
	fat_bones_enable("#PLAYER#", false)
end

function shot2()
	local excluded_lights_2 = {"CH_FreeSpot02", "BB Omni04"}
	light_set_lights(excluded_lights_2, 2, false)

	local included_lights_2 = {"CH_FreeSpot01", "CH_FreeSpot03", "BB Omni01", "BB Omni02", "BB Omni03", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_2, 7, true)

	teleport_to_slate_pos("#PLAYER#", -1.887, 0.0, -0.864, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_2")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_2")
	teleport_to_slate_pos("CS_dex", -2.451, 0.0, -5.596, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_2")
	teleport_to_slate_pos("CS_WoodChair", -2.636, 0.0, -2.88, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_2")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_2")
end

function shot3()
	local excluded_lights_3 = {"CH_FreeSpot01", "BB Omni04"}
	light_set_lights(excluded_lights_3, 2, false)

	local included_lights_3 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni01", "BB Omni02", "BB Omni03", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_3, 7, true)

	teleport_to_slate_pos("#PLAYER#", -2.318, 0.0, -1.651, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_3")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_3")
	teleport_to_slate_pos("CS_dex", -2.451, 0.0, -5.596, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_3")
	teleport_to_slate_pos("CS_WoodChair", -2.509, 0.0, -2.519, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_3")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_3")
end

function shot4()
	local excluded_lights_4 = {"CH_FreeSpot01", "BB Omni01", "BB Omni04"}
	light_set_lights(excluded_lights_4, 3, false)

	local included_lights_4 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni02", "BB Omni03", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_4, 6, true)

	teleport_to_slate_pos("#PLAYER#", -2.673, 0.0, -2.378, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_4")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_4")
	teleport_to_slate_pos("CS_dex", -2.451, 0.0, -5.596, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_4")
	teleport_to_slate_pos("CS_WoodChair", -2.776, 0.0, -2.52, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_4")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_4")
end

function shot5()
	local excluded_lights_5 = {"CH_FreeSpot01", "CH_FreeSpot03", "BB Omni01", "BB Omni04"}
	light_set_lights(excluded_lights_5, 4, false)

	local included_lights_5 = {"CH_FreeSpot02", "BB Omni02", "BB Omni03", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_5, 5, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_5")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_5")
	teleport_to_slate_pos("CS_dex", -2.451, 0.0, -5.596, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_5")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_5")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_5")
end

function shot6()
	local excluded_lights_6 = {"CH_FreeSpot02", "BB Omni03", "BB Omni04", "BB Omni06"}
	light_set_lights(excluded_lights_6, 4, false)

	local included_lights_6 = {"CH_FreeSpot01", "CH_FreeSpot03", "BB Omni01", "BB Omni02", "BB Omni05"}
	light_set_lights(included_lights_6, 5, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_6")
	teleport_to_slate_pos("CS_dex", -2.451, 0.0, -5.596, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_6")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_6")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_6")
end

function shot7()
	local excluded_lights_7 = {"CH_FreeSpot01", "BB Omni01", "BB Omni04"}
	light_set_lights(excluded_lights_7, 3, false)

	local included_lights_7 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni02", "BB Omni03", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_7, 6, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_7")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_7")
	teleport_to_slate_pos("CS_dex", -2.451, 0.0, -5.596, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_7")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_7")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_7")
	set_human_cutscene_weapon("cellphone1l", "CS_johnny")
end

function shot8()
	local excluded_lights_8 = {"CH_FreeSpot01", "CH_FreeSpot03", "BB Omni01", "BB Omni04"}
	light_set_lights(excluded_lights_8, 4, false)

	local included_lights_8 = {"CH_FreeSpot02", "BB Omni02", "BB Omni03", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_8, 5, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_8")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_8")
	teleport_to_slate_pos("CS_dex", -2.451, 0.0, -5.596, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_8")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_8")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_8")
end

function shot9()
	local excluded_lights_9 = {"CH_FreeSpot01", "BB Omni01", "BB Omni04"}
	light_set_lights(excluded_lights_9, 3, false)

	local included_lights_9 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni02", "BB Omni03", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_9, 6, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_9")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_9")
	teleport_to_slate_pos("CS_dex", -2.451, 0.0, -5.596, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_9")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_9")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_9")
end

function shot10()
	local excluded_lights_10 = {"CH_FreeSpot01", "BB Omni01", "BB Omni04"}
	light_set_lights(excluded_lights_10, 3, false)

	local included_lights_10 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni02", "BB Omni03", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_10, 6, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_10")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_10")
	teleport_to_slate_pos("CS_dex", -2.509, 0.0, -5.439, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_10")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_10")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_10")
end

function shot11()
	local excluded_lights_11 = {"CH_FreeSpot01", "BB Omni01", "BB Omni03", "BB Omni04"}
	light_set_lights(excluded_lights_11, 4, false)

	local included_lights_11 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni02", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_11, 5, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_11")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_11")
	teleport_to_slate_pos("CS_dex", -2.589, 0.0, -5.228, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_11")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_11")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_11")
	set_human_cutscene_weapon("","CS_johnny")
end

function shot12()
	local excluded_lights_12 = {"CH_FreeSpot01", "BB Omni01"}
	light_set_lights(excluded_lights_12, 2, false)

	local included_lights_12 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni02", "BB Omni03", "BB Omni04", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_12, 7, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_12")
	teleport_to_slate_pos("CS_johnny", -3.901, 0.0, -4.449, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_12")
	teleport_to_slate_pos("CS_dex", -2.589, 0.0, -5.228, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_12")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_12")
	teleport_to_slate_pos("CS_LeathChair", -4.119, 0.0, -4.475, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_12")
end

function shot13()
	local excluded_lights_13 = {"CH_FreeSpot01", "BB Omni01"}
	light_set_lights(excluded_lights_13, 2, false)

	local included_lights_13 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni02", "BB Omni03", "BB Omni04", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_13, 7, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_13")
	teleport_to_slate_pos("CS_johnny", -3.766, 0.0, -4.404, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_13")
	teleport_to_slate_pos("CS_dex", -2.589, 0.0, -5.228, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_13")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_13")
	teleport_to_slate_pos("CS_LeathChair", -4.521, 0.0, -4.455, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_13")
end

function shot14()
	local excluded_lights_14 = {"CH_FreeSpot01", "CH_FreeSpot02", "CH_FreeSpot03", "BB Omni01"}
	light_set_lights(excluded_lights_14, 4, false)

	local included_lights_14 = {"BB Omni02", "BB Omni03", "BB Omni04", "BB Omni05", "BB Omni06"}
	light_set_lights(included_lights_14, 5, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_14")
	teleport_to_slate_pos("CS_johnny", -3.631, 0.0, -4.359, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_14")
	teleport_to_slate_pos("CS_dex", -2.589, 0.0, -5.228, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_14")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_14")
	teleport_to_slate_pos("CS_LeathChair", -4.521, 0.0, -4.455, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_14")
end

function shot15()
	local excluded_lights_15 = {"CH_FreeSpot01", "BB Omni01", "BB Omni05"}
	light_set_lights(excluded_lights_15, 3, false)

	local included_lights_15 = {"CH_FreeSpot02", "CH_FreeSpot03", "BB Omni02", "BB Omni03", "BB Omni04", "BB Omni06"}
	light_set_lights(included_lights_15, 6, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_15")
	teleport_to_slate_pos("CS_johnny", -3.629, 0.0, -4.358, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_15")
	teleport_to_slate_pos("CS_dex", -2.589, 0.0, -5.228, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_15")
	teleport_to_slate_pos("CS_WoodChair", -2.786, 0.0, -2.517, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_15")
	teleport_to_slate_pos("CS_LeathChair", -4.521, 0.0, -4.455, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_15")
end

function shot16()
	local excluded_lights_16 = {"CH_FreeSpot01", "CH_FreeSpot03", "BB Omni01", "BB Omni05"}
	light_set_lights(excluded_lights_16, 4, false)

	local included_lights_16 = {"CH_FreeSpot02", "BB Omni02", "BB Omni03", "BB Omni04", "BB Omni06"}
	light_set_lights(included_lights_16, 5, true)

	teleport_to_slate_pos("#PLAYER#", -2.706, 0.0, -2.338, "slate_church_johnnyroom")
	play_custom_action_do("#PLAYER#", "vk01_scene01_p_16")
	teleport_to_slate_pos("CS_johnny", -3.629, 0.0, -4.358, "slate_church_johnnyroom")
	play_custom_action_do("CS_johnny", "vk01_scene01_j_16")
	teleport_to_slate_pos("CS_dex", -2.589, 0.0, -5.228, "slate_church_johnnyroom")
	play_custom_action_do("CS_dex", "vk01_scene01_d_16")
	teleport_to_slate_pos("CS_WoodChair", -2.791, 0.0, -2.524, "slate_church_johnnyroom")
	play_custom_action_do("CS_WoodChair", "vk01_scene01_pchair_16")
	teleport_to_slate_pos("CS_LeathChair", -4.521, 0.0, -4.455, "slate_church_johnnyroom")
	play_custom_action_do("CS_LeathChair", "vk01_scene01_jchair_16")
	delay(1.76667)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
	fat_bones_enable("#PLAYER#", true)
end

function cutscene_end()
	character_show("#PLAYER#")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_johnny")
	stop_custom_actions("CS_dex")
	stop_custom_actions("CS_WoodChair")
	stop_custom_actions("CS_LeathChair")
	letterbox_fade_out(true)
	fade_out(0.5)
	fat_bones_enable("#PLAYER#", true)
end
