-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk01_kidnapper\vk01_kidnapper.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk06__RLDinteriors.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	load_chunk("sr_chunk06", true )
	select_slate("slate_vk01_warehouse")
end

function shot2()
end

function cutscene_abort()
end

function cutscene_end()
end
