-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk03b_scene01\vk03b_scene01.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk34_vk09__int.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	pvs_enable(false)
	time_of_day_character_shadows_enable(false)
	set_level_lights(false)
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function shot8()
end

function shot9()
end

function shot10()
end

function shot11()
end

function shot12()
end

function shot13()
end

function shot14()
end

function shot15()
end

function shot16()
end

function shot17()
end

function shot18()
end

function shot19()
end

function shot20()
end

function shot21()
end

function shot22()
end

function shot23()
end

function shot24()
end

function cutscene_abort()
	time_of_day_character_shadows_enable(true)
end

function cutscene_end()
	time_of_day_character_shadows_enable(true)
end
