-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk04a_scene02\vk04a_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk08_vk4a__interiors.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	time_of_day_character_shadows_enable(false)
	set_level_lights(false)
	spawning_peds(false)
	spawning_cars(false)
	character_hide("CS_anth")
	set_human_cutscene_weapon("beretta")
-- NOTE use 	load_chunks("sr_chunk08_vk4a", "sr_chunk08")
end

function shot2()
	character_show("CS_anth")
end

function shot3()
	set_human_cutscene_weapon("")
end

function shot4()
end

function shot5()

end

function shot6()
end

function shot7()

end

function shot8()
end

function shot9()
end

function shot10()
end

function shot11()
end

function shot12()
end

function shot13()
end

function shot14()
end

function shot15()
end

function shot16()
end

function shot17()
end

function shot18()
end

function shot19()
end

function shot20()
	tree_shadows_enable(false)
	set_framebuffer_tint (0.223,0.190,0.119,9)
	set_framebuffer_saturation (0.5)
end

function shot21()
	set_framebuffer_tint (0.223,0.190,0.119,9)
	set_framebuffer_saturation (0.5)
end

function shot22()

end

function shot23()

end

function shot24()

end

function shot25()

end

function shot26()

end

function shot27()

end

function shot28()
	character_hide("#PLAYER#")

end

function shot29()

end

function shot30()
	set_human_cutscene_weapon("knifel", "CS_jnny")

end

function shot31()
	set_human_cutscene_weapon("", "CS_jnny")
end

function shot32()

end

function shot33()

end

function shot34()
	character_show("#PLAYER#")

end

function shot35()

end

function shot36()

end

function shot37()

end

function shot38()

end

function shot39()
	character_hide("#PLAYER#")

end

function shot40()
	set_far_clip(30)
	character_show("#PLAYER#")
end

function shot41()
	set_far_clip(5000)
end

function shot42()
	set_far_clip(30)
end

function shot43()
end

function cutscene_abort()
	set_far_clip(5000)
	time_of_day_character_shadows_enable(true)
	 set_level_lights(true)
	tree_shadows_enable(true)
	spawning_peds(true)
	spawning_cars(true)
end

function cutscene_end()
	set_far_clip(5000)
	time_of_day_character_shadows_enable(true)
	set_level_lights(true)
	tree_shadows_enable(true)
	spawning_peds(true)
	spawning_cars(true)
end
