-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk05_scene05\vk05_scene05.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk38__interiors.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	character_hide("CS_pist")
	set_level_lights(false)
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
	character_show("CS_pist")
end

function shot7()
end

function shot8()
end

function shot9()
end

function shot10()
end

function cutscene_abort()
end

function cutscene_end()
end
