-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk05_scene04\vk05_scene04.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk38__interiors.cts
-------------------------------------


function cutscene_main()
	load_chunk("sr_chunk38", true )
	load_chunks("sr_chunk38_greens", "sr_chunk38" )
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function cutscene_abort()
end

function cutscene_end()
end
