-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk05_scene02\vk05_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk32__interiors.cts
-------------------------------------


function cutscene_main()
end

function shot1()
end

function shot2()
end

function shot3()
end

function cutscene_abort()
end

function cutscene_end()
end
