-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk06a_scene02\vk06a_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk34_vk09__int.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	set_level_lights(false)
end

function shot2()
end

function shot3()
	set_force_time_of_day_lights("true")
end

function shot4()
	set_force_time_of_day_lights("false")
end

function shot5()
	set_force_time_of_day_lights("true")
end

function shot6()
	set_force_time_of_day_lights("false")
end

function cutscene_abort()
	set_force_time_of_day_lights("disabled")
end

function cutscene_end()
	set_force_time_of_day_lights("disabled")
end
