-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk06b_scene02\vk06b_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk32__interiors.cts
-------------------------------------


function cutscene_main()
	load_chunk("sr_chunk32", true )
	load_chunks("sr_chunk32_ms2", "sr_chunk32")
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function cutscene_abort()
end

function cutscene_end()
end
