-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk06a_scene02\vk06a_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk34_vk09__int.cts
-------------------------------------


function cutscene_main()
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function cutscene_abort()
end

function cutscene_end()
end
