-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk08_scene01\vk08_scene01.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk02_church__interiors.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
	thread_new_cutscene_shot("shot12", 12)
	thread_new_cutscene_shot("shot13", 13)
	thread_new_cutscene_shot("shot14", 14)
	thread_new_cutscene_shot("shot15", 15)
	thread_new_cutscene_shot("shot16", 16)
	thread_new_cutscene_shot("shot17", 17)
	thread_new_cutscene_shot("shot18", 18)
	thread_new_cutscene_shot("shot19", 19)
	thread_new_cutscene_shot("shot20", 20)
	thread_new_cutscene_shot("shot21", 21)
	thread_new_cutscene_shot("shot22", 22)
	thread_new_cutscene_shot("shot23", 23)
	thread_new_cutscene_shot("shot24", 24)
	thread_new_cutscene_shot("shot25", 25)
	thread_new_cutscene_shot("shot26", 26)
	thread_new_cutscene_shot("shot27", 27)
	thread_new_cutscene_shot("shot28", 28)
	thread_new_cutscene_shot("shot29", 29)
	thread_new_cutscene_shot("shot30", 30)
	thread_new_cutscene_shot("shot31", 31)
	thread_new_cutscene_shot("shot32", 32)
end

function shot1()
	set_level_lights(false)
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("CS_johnny", 1.65522, 0.0, 1.38448, "slate_church_juliusroom")
	play_custom_action_do("CS_johnny", "vk08_scene01_johnny_1")
	teleport_to_slate_pos("#PLAYER#", -0.600047, 0.0, 2.69849, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_1")
	teleport_to_slate_pos("CS_king", -2.56776, 0.0, 1.26154, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_1")
	teleport_to_slate_pos("CS_julius", -2.88717, 0.0, 2.20159, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_1")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_1")
	teleport_to_slate_pos("CS_jochair", 1.71123, 0.0, 1.32424, "slate_church_juliusroom")
	play_custom_action_do("CS_jochair", "vk08_scene01_jochair_1")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_1")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_1")
end

function shot2()
	teleport_to_slate_pos("#PLAYER#", 0.17206, 0.0, 2.56462, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_2")
	teleport_to_slate_pos("CS_julius", -1.43288, 0.0, 2.14981, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_2")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_2")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_2")
end

function shot3()
	teleport_to_slate_pos("CS_king", -2.56632, 0.0, 1.26417, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_3")
	teleport_to_slate_pos("CS_julius", -1.05995, 0.0, 2.4447, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_3")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_3")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_3")
end

function shot4()
	teleport_to_slate_pos("CS_julius", -1.05363, 0.0, 2.45275, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_4")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_4")
end

function shot5()
	teleport_to_slate_pos("CS_johnny", 1.6551, 0.0, 1.3848, "slate_church_juliusroom")
	play_custom_action_do("CS_johnny", "vk08_scene01_johnny_5")
	teleport_to_slate_pos("#PLAYER#", 0.288866, 0.0, 2.84869, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_5")
	teleport_to_slate_pos("CS_king", -2.55695, 0.0, 1.26518, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_5")
	teleport_to_slate_pos("CS_julius", -1.05459, 0.0, 2.46071, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_5")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_5")
	teleport_to_slate_pos("CS_jochair", 1.71123, 0.0, 1.32424, "slate_church_juliusroom")
	play_custom_action_do("CS_jochair", "vk08_scene01_jochair_5")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_5")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_5")
end

function shot6()
	teleport_to_slate_pos("CS_johnny", 1.65576, 0.0, 1.38472, "slate_church_juliusroom")
	play_custom_action_do("CS_johnny", "vk08_scene01_johnny_6")
	teleport_to_slate_pos("CS_jochair", 1.71123, 0.0, 1.32424, "slate_church_juliusroom")
	play_custom_action_do("CS_jochair", "vk08_scene01_jochair_6")
end

function shot7()
	teleport_to_slate_pos("CS_king", -2.56088, 0.0, 1.26159, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_7")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_7")
end

function shot8()
	teleport_to_slate_pos("CS_julius", -1.05361, 0.0, 2.46389, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_8")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_8")
end

function shot9()
	teleport_to_slate_pos("CS_king", -2.56071, 0.0, 1.26284, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_9")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_9")
end

function shot10()
	teleport_to_slate_pos("#PLAYER#", 0.290724, 0.0, 2.84817, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_10")
	teleport_to_slate_pos("CS_julius", -1.05415, 0.0, 2.45979, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_10")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_10")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_10")
end

function shot11()
	teleport_to_slate_pos("CS_king", -2.54855, 0.0, 1.25814, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_11")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_11")
end

function shot12()
	teleport_to_slate_pos("CS_julius", -1.05643, 0.0, 2.45277, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_12")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_12")
end

function shot13()
	teleport_to_slate_pos("CS_king", -2.54421, 0.0, 1.26383, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_13")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_13")
end

function shot14()
	teleport_to_slate_pos("CS_julius", -1.05539, 0.0, 2.44923, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_14")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_14")
end

function shot15()
	teleport_to_slate_pos("CS_king", -2.54301, 0.0, 1.26371, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_15")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_15")
end

function shot16()
	teleport_to_slate_pos("CS_johnny", 1.71183, 0.0, 1.3982, "slate_church_juliusroom")
	play_custom_action_do("CS_johnny", "vk08_scene01_johnny_16")
	teleport_to_slate_pos("#PLAYER#", 0.288709, 0.0, 2.84423, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_16")
	teleport_to_slate_pos("CS_julius", -1.05609, 0.0, 2.44893, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_16")
	teleport_to_slate_pos("CS_jochair", 1.71123, 0.0, 1.32424, "slate_church_juliusroom")
	play_custom_action_do("CS_jochair", "vk08_scene01_jochair_16")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_16")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_16")
end

function shot17()
	teleport_to_slate_pos("CS_johnny", 1.6288, 0.0, 1.37223, "slate_church_juliusroom")
	play_custom_action_do("CS_johnny", "vk08_scene01_johnny_17")
	teleport_to_slate_pos("CS_jochair", 1.71123, 0.0, 1.32424, "slate_church_juliusroom")
	play_custom_action_do("CS_jochair", "vk08_scene01_jochair_17")
end

function shot18()
	teleport_to_slate_pos("CS_king", -2.54235, 0.0, 1.26364, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_18")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_18")
end

function shot19()
	teleport_to_slate_pos("CS_julius", -1.04849, 0.0, 2.46058, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_19")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_19")
end

function shot20()
	teleport_to_slate_pos("CS_king", -2.53596, 0.0, 1.26757, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_20")
	teleport_to_slate_pos("CS_julius", -1.05482, 0.0, 2.44861, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_20")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_20")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_20")
end

function shot21()
	teleport_to_slate_pos("#PLAYER#", 0.289079, 0.0, 2.84904, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_21")
	teleport_to_slate_pos("CS_king", -2.51624, 0.0, 1.20831, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_21")
	teleport_to_slate_pos("CS_julius", -1.14557, 0.0, 2.29068, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_21")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_21")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_21")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_21")
end

function shot22()
	teleport_to_slate_pos("CS_johnny", 1.35754, 0.0, 1.22067, "slate_church_juliusroom")
	play_custom_action_do("CS_johnny", "vk08_scene01_johnny_22")
	teleport_to_slate_pos("#PLAYER#", 0.288818, 0.0, 2.84906, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_22")
	teleport_to_slate_pos("CS_king", -2.56885, 0.0, 1.23955, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_22")
	teleport_to_slate_pos("CS_julius", -1.04928, 0.0, 2.44008, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_22")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_22")
	teleport_to_slate_pos("CS_jochair", 1.71123, 0.0, 1.32424, "slate_church_juliusroom")
	play_custom_action_do("CS_jochair", "vk08_scene01_jochair_22")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_22")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_22")
end

function shot23()
	teleport_to_slate_pos("CS_julius", -1.05001, 0.0, 2.43525, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_23")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_23")
end

function shot24()
	teleport_to_slate_pos("CS_king", -2.57046, 0.0, 1.24288, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_24")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_24")
end

function shot25()
	teleport_to_slate_pos("#PLAYER#", 0.28875, 0.0, 2.84446, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_25")
	teleport_to_slate_pos("CS_julius", -1.05414, 0.0, 2.44173, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_25")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_25")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_25")
end

function shot26()
	teleport_to_slate_pos("CS_king", -2.5586, 0.0, 1.24155, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_26")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_26")
end

function shot27()
	teleport_to_slate_pos("CS_julius", -1.05604, 0.0, 2.43188, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_27")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_27")
end

function shot28()
	teleport_to_slate_pos("#PLAYER#", 0.289093, 0.0, 2.84925, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_28")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_28")
end

function shot29()
	teleport_to_slate_pos("CS_king", -2.54564, 0.0, 1.24387, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_29")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_29")
end

function shot30()
	teleport_to_slate_pos("#PLAYER#", 0.289839, 0.0, 2.84273, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_30")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_30")
end

function shot31()
	teleport_to_slate_pos("CS_king", -2.5466, 0.0, 1.24337, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_31")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_31")
end

function shot32()
	teleport_to_slate_pos("CS_johnny", 1.65977, 0.0, 1.40115, "slate_church_juliusroom")
	play_custom_action_do("CS_johnny", "vk08_scene01_johnny_32")
	teleport_to_slate_pos("#PLAYER#", 0.412265, 0.0, 3.38906, "slate_church_juliusroom")
	play_custom_action_do("#PLAYER#", "vk08_scene01_player_32")
	teleport_to_slate_pos("CS_king", -2.59029, 0.0, 1.25184, "slate_church_juliusroom")
	play_custom_action_do("CS_king", "vk08_scene01_king_32")
	teleport_to_slate_pos("CS_julius", -1.50423, 0.0, 2.39765, "slate_church_juliusroom")
	play_custom_action_do("CS_julius", "vk08_scene01_julius_32")
	teleport_to_slate_pos("CS_kchair", -2.49468, 0.0, 1.26511, "slate_church_juliusroom")
	play_custom_action_do("CS_kchair", "vk08_scene01_kchair_32")
	teleport_to_slate_pos("CS_jochair", 1.71123, 0.0, 1.32424, "slate_church_juliusroom")
	play_custom_action_do("CS_jochair", "vk08_scene01_jochair_32")
	teleport_to_slate_pos("CS_pchair", 0.14419, 0.0, 2.50792, "slate_church_juliusroom")
	play_custom_action_do("CS_pchair", "vk08_scene01_pchair_32")
	teleport_to_slate_pos("CS_juchair", -1.09974, 0.0, 2.37056, "slate_church_juliusroom")
	play_custom_action_do("CS_juchair", "vk08_scene01_juchair_32")
	delay(3.7)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end

function cutscene_end()
	stop_custom_actions("CS_johnny")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_king")
	stop_custom_actions("CS_julius")
	stop_custom_actions("CS_kchair")
	stop_custom_actions("CS_jochair")
	stop_custom_actions("CS_pchair")
	stop_custom_actions("CS_juchair")
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end
