-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk09_scene02\vk09_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk34__interiors.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
end

function shot1()
	set_level_lights(false)
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("CS_johnny", 1.34842, -0.0337531, -2.2556, "slate_vk09_scene02")
	play_custom_action_do("CS_johnny", "vk09_scene02_johnny_1")
	teleport_to_slate_pos("#PLAYER#", 0.826434, -0.042714, -0.430085, "slate_vk09_scene02")
	play_custom_action_do("#PLAYER#", "vk09_scene02_player_1")
	teleport_to_slate_pos("CS_king", -0.819676, -0.043016, -2.01392, "slate_vk09_scene02")
	play_custom_action_do("CS_king", "vk09_scene02_king_1")
	teleport_to_slate_pos("CS_DoorA", 1.62217, 0.0, -3.41232, "slate_vk09_scene02")
	play_custom_action_do("CS_DoorA", "vk09_scene02_doorA_1")
	teleport_to_slate_pos("CS_doorB", 1.62217, 0.0, -3.41232, "slate_vk09_scene02")
	play_custom_action_do("CS_doorB", "vk09_scene02_doorb_1")
end

function shot2()
	teleport_to_slate_pos("CS_johnny", 2.11494, -0.0357415, -3.54583, "slate_vk09_scene02")
	play_custom_action_do("CS_johnny", "vk09_scene02_johnny_2")
	teleport_to_slate_pos("#PLAYER#", 1.74725, -0.0359049, -2.92311, "slate_vk09_scene02")
	play_custom_action_do("#PLAYER#", "vk09_scene02_player_2")
	teleport_to_slate_pos("CS_king", 0.808075, -0.0454086, -3.37012, "slate_vk09_scene02")
	play_custom_action_do("CS_king", "vk09_scene02_king_2")
	teleport_to_slate_pos("CS_DoorA", 1.62217, 0.0, -3.41232, "slate_vk09_scene02")
	play_custom_action_do("CS_DoorA", "vk09_scene02_doorA_2")
	teleport_to_slate_pos("CS_doorB", 1.62217, 0.0, -3.41232, "slate_vk09_scene02")
	play_custom_action_do("CS_doorB", "vk09_scene02_doorb_2")
end

function shot3()
	teleport_to_slate_pos("CS_johnny", 2.73173, -0.0354639, -4.31843, "slate_vk09_scene02")
	play_custom_action_do("CS_johnny", "vk09_scene02_johnny_3")
	teleport_to_slate_pos("#PLAYER#", 1.68817, -0.0729031, -3.71996, "slate_vk09_scene02")
	play_custom_action_do("#PLAYER#", "vk09_scene02_player_3")
	teleport_to_slate_pos("CS_king", 0.292381, -0.0469077, -3.0426, "slate_vk09_scene02")
	play_custom_action_do("CS_king", "vk09_scene02_king_3")
	teleport_to_slate_pos("CS_DoorA", 1.62217, 0.0, -3.41232, "slate_vk09_scene02")
	play_custom_action_do("CS_DoorA", "vk09_scene02_doorA_3")
	teleport_to_slate_pos("CS_doorB", 1.62217, 0.0, -3.41232, "slate_vk09_scene02")
	play_custom_action_do("CS_doorB", "vk09_scene02_doorb_3")
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end

function cutscene_end()
	stop_custom_actions("CS_johnny")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_king")
	stop_custom_actions("CS_DoorA")
	stop_custom_actions("CS_doorB")
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end
