-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\vk09_scene02\vk09_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk34__interiors.cts
-------------------------------------


function cutscene_main()
end

function shot1()
	load_chunk("sr_chunk34", true )
	select_slate("slate_vk09_scene02")
	audio_play("VK09_SCENE02", "voice", true)
end

function shot2()
end

function shot3()
end

function cutscene_abort()
end

function cutscene_end()
end
