-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\wr01_scene01\wr01_scene01.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk09__ground.cts
-------------------------------------


function cutscene_main()
	load_chunk("sr_chunk09", true )
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function shot8()
end

function shot9()
end

function cutscene_abort()
end

function cutscene_end()
end
