---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: wr04_scene02
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk40", true)
	load_chunks("sr_chunk40_price", "sr_chunk40")
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
	thread_new_cutscene_shot("shot12", 12)
	thread_new_cutscene_shot("shot13", 13)
	thread_new_cutscene_shot("shot14", 14)
end

function shot1()
	local excluded_lights_1 = {"BB FreeSpot01", "BB FreeSpot02", "BB FreeSpot06", "BB Level Omni18", "BB Level Omni19", "BB Don Lin Key Omni15"}
	light_set_lights(excluded_lights_1, 6, false)

	local included_lights_1 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni12", "BB FreeSpot05", "BB Omni13", "BB Omni14", "BB Lin Don Fill Omni15", "BB Lin Level Omni16", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(included_lights_1, 13, true)

	fade_in(0.5)
	select_slate("slate_smansion_main")
	character_hide("#PLAYER#")
	teleport_to_slate_pos("CS_price", 7.164, 0.0, -2.111, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_1")
	teleport_to_slate_pos("CS_donnie", 1.76, 0.0, 0.839, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_1")
	teleport_to_slate_pos("CS_sharp", 6.185, 0.0, -2.667, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_1")
	teleport_to_slate_pos("CS_lin", 2.627, 0.0, 0.83, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_1")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_1")
	teleport_to_slate_pos("CS_blunt", 1.859, 0.0, 1.272, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_1")
	set_level_lights(false)
	--load_chunks("sr_chunk40", "sr_chunk40_Price")
end

function shot2()
	local excluded_lights_2 = {"BB Omni03", "BB Omni07", "BB Omni12", "BB FreeSpot02", "BB FreeSpot05", "BB Omni13", "BB Omni14", "BB Lin Don Fill Omni15", "BB Lin Level Omni16", "BB Level Omni18", "BB Level Omni19", "BB Don Lin Key Omni15", "BB Price Sharp Walkin Omni16"}
	light_set_lights(excluded_lights_2, 13, false)

	local included_lights_2 = {"BB Omni01", "BB Omni02", "BB Omni06", "BB FreeSpot01", "BB FreeSpot06", "BB Sharp fill Omni16"}
	light_set_lights(included_lights_2, 6, true)

	teleport_to_slate_pos("CS_price", 0.485, 0.0, -2.67, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_2")
	teleport_to_slate_pos("CS_donnie", 1.756, 0.0, 0.832, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_2")
	teleport_to_slate_pos("CS_sharp", -0.814, 0.0, -2.926, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_2")
	teleport_to_slate_pos("CS_lin", 2.631, 0.0, 0.823, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_2")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_2")
	teleport_to_slate_pos("CS_blunt", 1.859, 0.0, 1.272, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_2")
end

function shot3()
	local excluded_lights_3 = {"BB FreeSpot01", "BB Omni12", "BB FreeSpot02", "BB Lin Level Omni16", "BB Level Omni18", "BB Don Lin Key Omni15", "BB Price Sharp Walkin Omni16"}
	light_set_lights(excluded_lights_3, 7, false)

	local included_lights_3 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni06", "BB Omni07", "BB FreeSpot05", "BB FreeSpot06", "BB Omni13", "BB Omni14", "BB Lin Don Fill Omni15", "BB Level Omni19", "BB Sharp fill Omni16"}
	light_set_lights(included_lights_3, 12, true)

	teleport_to_slate_pos("CS_price", 0.232, 0.0, -2.971, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_3")
	teleport_to_slate_pos("CS_donnie", 1.755, 0.0, 1.008, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_3")
	teleport_to_slate_pos("CS_sharp", -0.94, 0.0, -2.95, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_3")
	teleport_to_slate_pos("CS_lin", 2.625, 0.0, 1.255, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_3")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_3")
	teleport_to_slate_pos("CS_blunt", 1.859, 0.0, 1.272, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_3")
end

function shot4()
	local excluded_lights_4 = {"BB FreeSpot01", "BB FreeSpot06", "BB Lin Don Fill Omni15", "BB Level Omni18", "BB Level Omni19", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(excluded_lights_4, 7, false)

	local included_lights_4 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni12", "BB FreeSpot02", "BB FreeSpot05", "BB Omni13", "BB Omni14", "BB Lin Level Omni16", "BB Don Lin Key Omni15"}
	light_set_lights(included_lights_4, 12, true)

	teleport_to_slate_pos("CS_price", 0.319, 0.0, -3.248, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_4")
	teleport_to_slate_pos("CS_donnie", 1.019, 0.0, -0.426, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_4")
	teleport_to_slate_pos("CS_sharp", -0.913, 0.0, -2.951, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_4")
	teleport_to_slate_pos("CS_lin", 0.202, 0.0, 0.323, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_4")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_4")
	teleport_to_slate_pos("CS_blunt", 1.859, 0.0, 1.272, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_4")
end

function shot5()
	local excluded_lights_5 = {"BB Omni03", "BB Omni06", "BB FreeSpot01", "BB Omni12", "BB FreeSpot02", "BB FreeSpot06", "BB Omni13", "BB Lin Don Fill Omni15", "BB Lin Level Omni16", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(excluded_lights_5, 11, false)

	local included_lights_5 = {"BB Omni01", "BB Omni02", "BB Omni07", "BB FreeSpot05", "BB Omni14", "BB Level Omni18", "BB Level Omni19", "BB Don Lin Key Omni15"}
	light_set_lights(included_lights_5, 8, true)

	teleport_to_slate_pos("CS_price", 0.296, 0.0, -2.91, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_5")
	teleport_to_slate_pos("CS_donnie", 0.27, 0.0, -1.887, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_5")
	teleport_to_slate_pos("CS_sharp", -0.911, 0.0, -2.967, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_5")
	teleport_to_slate_pos("CS_lin", -0.411, 0.0, -1.56, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_5")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_5")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_5")
end

function shot6()
	local excluded_lights_6 = {"BB Omni03", "BB Omni07", "BB FreeSpot01", "BB FreeSpot02", "BB FreeSpot06", "BB Omni14", "BB Lin Don Fill Omni15", "BB Level Omni18", "BB Level Omni19", "BB Don Lin Key Omni15", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(excluded_lights_6, 12, false)

	local included_lights_6 = {"BB Omni01", "BB Omni02", "BB Omni06", "BB Omni12", "BB FreeSpot05", "BB Omni13", "BB Lin Level Omni16"}
	light_set_lights(included_lights_6, 7, true)

	teleport_to_slate_pos("CS_price", 0.175, 0.0, -3.075, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_6")
	teleport_to_slate_pos("CS_donnie", 0.262, 0.0, -1.836, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_6")
	teleport_to_slate_pos("CS_sharp", -0.91, 0.0, -2.975, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_6")
	teleport_to_slate_pos("CS_lin", -0.416, 0.0, -1.559, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_6")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_6")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_6")
end

function shot7()
	local excluded_lights_7 = {"BB FreeSpot01", "BB Omni12", "BB FreeSpot06", "BB Omni13", "BB Omni14", "BB Lin Don Fill Omni15", "BB Level Omni18", "BB Level Omni19", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(excluded_lights_7, 10, false)

	local included_lights_7 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni06", "BB Omni07", "BB FreeSpot02", "BB FreeSpot05", "BB Lin Level Omni16", "BB Don Lin Key Omni15"}
	light_set_lights(included_lights_7, 9, true)

	teleport_to_slate_pos("CS_price", 0.293, 0.0, -2.831, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_7")
	teleport_to_slate_pos("CS_donnie", 0.348, 0.0, -1.913, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_7")
	teleport_to_slate_pos("CS_sharp", -0.911, 0.0, -2.972, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_7")
	teleport_to_slate_pos("CS_lin", -0.411, 0.0, -1.564, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_7")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_7")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_7")
end

function shot8()
	local excluded_lights_8 = {"BB Omni02", "BB Omni03", "BB Omni07", "BB FreeSpot01", "BB Omni12", "BB FreeSpot02", "BB Omni14", "BB Lin Don Fill Omni15", "BB Lin Level Omni16", "BB Level Omni18", "BB Level Omni19", "BB Don Lin Key Omni15", "BB Price Sharp Walkin Omni16"}
	light_set_lights(excluded_lights_8, 13, false)

	local included_lights_8 = {"BB Omni01", "BB Omni06", "BB FreeSpot05", "BB FreeSpot06", "BB Omni13", "BB Sharp fill Omni16"}
	light_set_lights(included_lights_8, 6, true)

	teleport_to_slate_pos("CS_price", 0.197, 0.0, -3.179, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_8")
	teleport_to_slate_pos("CS_donnie", 0.258, 0.0, -1.729, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_8")
	teleport_to_slate_pos("CS_sharp", -0.92, 0.0, -2.93, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_8")
	teleport_to_slate_pos("CS_lin", -0.402, 0.0, -1.559, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_8")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_8")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_8")
end

function shot9()
	local excluded_lights_9 = {"BB Omni02", "BB Omni03", "BB Omni07", "BB FreeSpot01", "BB Omni12", "BB FreeSpot02", "BB FreeSpot05", "BB Omni13", "BB Omni14", "BB Lin Don Fill Omni15", "BB Lin Level Omni16", "BB Level Omni18", "BB Level Omni19", "BB Don Lin Key Omni15", "BB Price Sharp Walkin Omni16"}
	light_set_lights(excluded_lights_9, 15, false)

	local included_lights_9 = {"BB Omni01", "BB Omni06", "BB FreeSpot06", "BB Sharp fill Omni16"}
	light_set_lights(included_lights_9, 4, true)

	teleport_to_slate_pos("CS_price", 0.187, 0.0, -3.186, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_9")
	teleport_to_slate_pos("CS_donnie", 0.27, 0.0, -1.729, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_9")
	teleport_to_slate_pos("CS_sharp", -0.903, 0.0, -2.923, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_9")
	teleport_to_slate_pos("CS_lin", -0.404, 0.0, -1.56, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_9")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_9")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_9")
end

function shot10()
	local excluded_lights_10 = {"BB Omni06", "BB FreeSpot01", "BB Omni12", "BB FreeSpot05", "BB FreeSpot06", "BB Omni14", "BB Lin Don Fill Omni15", "BB Level Omni18", "BB Level Omni19", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(excluded_lights_10, 11, false)

	local included_lights_10 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni07", "BB FreeSpot02", "BB Omni13", "BB Lin Level Omni16", "BB Don Lin Key Omni15"}
	light_set_lights(included_lights_10, 8, true)

	teleport_to_slate_pos("CS_price", 0.182, 0.0, -3.196, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_10")
	teleport_to_slate_pos("CS_donnie", 0.32, 0.0, -1.704, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_10")
	teleport_to_slate_pos("CS_sharp", -0.9, 0.0, -2.927, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_10")
	teleport_to_slate_pos("CS_lin", -0.404, 0.0, -1.561, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_10")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_10")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_10")
end

function shot11()
	local excluded_lights_11 = {"BB Omni01", "BB Omni03", "BB Omni07", "BB FreeSpot01", "BB FreeSpot02", "BB FreeSpot06", "BB Omni13", "BB Omni14", "BB Lin Don Fill Omni15", "BB Level Omni18", "BB Level Omni19", "BB Don Lin Key Omni15", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(excluded_lights_11, 14, false)

	local included_lights_11 = {"BB Omni02", "BB Omni06", "BB Omni12", "BB FreeSpot05", "BB Lin Level Omni16"}
	light_set_lights(included_lights_11, 5, true)

	teleport_to_slate_pos("CS_price", 0.196, 0.0, -2.987, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_11")
	teleport_to_slate_pos("CS_donnie", 0.445, 0.0, -1.826, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_11")
	teleport_to_slate_pos("CS_sharp", -0.899, 0.0, -2.929, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_11")
	teleport_to_slate_pos("CS_lin", -0.402, 0.0, -1.562, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_11")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_11")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_11")
end

function shot12()
	local excluded_lights_12 = {"BB Omni06", "BB FreeSpot01", "BB Omni12", "BB FreeSpot05", "BB FreeSpot06", "BB Omni13", "BB Omni14", "BB Lin Don Fill Omni15", "BB Lin Level Omni16", "BB Level Omni18", "BB Level Omni19", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(excluded_lights_12, 13, false)

	local included_lights_12 = {"BB Omni01", "BB Omni02", "BB Omni03", "BB Omni07", "BB FreeSpot02", "BB Don Lin Key Omni15"}
	light_set_lights(included_lights_12, 6, true)

	teleport_to_slate_pos("CS_price", 0.086, 0.0, -2.877, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_12")
	teleport_to_slate_pos("CS_donnie", 0.35, 0.0, -1.774, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_12")
	teleport_to_slate_pos("CS_sharp", -0.898, 0.0, -2.929, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_12")
	teleport_to_slate_pos("CS_lin", -0.405, 0.0, -1.56, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_12")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_12")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_12")
end

function shot13()
	local excluded_lights_13 = {"BB Omni01", "BB Omni03", "BB Omni07", "BB FreeSpot01", "BB FreeSpot02", "BB FreeSpot06", "BB Omni13", "BB Omni14", "BB Lin Don Fill Omni15", "BB Level Omni18", "BB Level Omni19", "BB Don Lin Key Omni15", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(excluded_lights_13, 14, false)

	local included_lights_13 = {"BB Omni02", "BB Omni06", "BB Omni12", "BB FreeSpot05", "BB Lin Level Omni16"}
	light_set_lights(included_lights_13, 5, true)

	teleport_to_slate_pos("CS_price", 0.196, 0.0, -2.906, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_13")
	teleport_to_slate_pos("CS_donnie", 0.377, 0.0, -1.839, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_13")
	teleport_to_slate_pos("CS_sharp", -0.897, 0.0, -2.932, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_13")
	teleport_to_slate_pos("CS_lin", -0.402, 0.0, -1.555, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_13")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_13")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_13")
end

function shot14()
	local excluded_lights_14 = {"BB Omni03", "BB Omni06", "BB Omni07", "BB FreeSpot01", "BB Omni12", "BB FreeSpot02", "BB FreeSpot05", "BB FreeSpot06", "BB Omni13", "BB Lin Don Fill Omni15", "BB Lin Level Omni16", "BB Price Sharp Walkin Omni16", "BB Sharp fill Omni16"}
	light_set_lights(excluded_lights_14, 13, false)

	local included_lights_14 = {"BB Omni01", "BB Omni02", "BB Omni14", "BB Level Omni18", "BB Level Omni19", "BB Don Lin Key Omni15"}
	light_set_lights(included_lights_14, 6, true)

	teleport_to_slate_pos("CS_price", 0.269, 0.0, -2.667, "slate_smansion_main")
	play_custom_action_do("CS_price", "wr04_scene02_price_14")
	teleport_to_slate_pos("CS_donnie", 0.4, 0.0, -1.832, "slate_smansion_main")
	play_custom_action_do("CS_donnie", "wr04_scene02_donnie_14")
	teleport_to_slate_pos("CS_sharp", -0.896, 0.0, -2.931, "slate_smansion_main")
	play_custom_action_do("CS_sharp", "wr04_scene02_sharp_14")
	teleport_to_slate_pos("CS_lin", -0.401, 0.0, -1.558, "slate_smansion_main")
	play_custom_action_do("CS_lin", "wr04_scene02_lin_14")
	teleport_to_slate_pos("CS_couch", 3.029, 0.0, 0.576, "slate_smansion_main")
	play_custom_action_do("CS_couch", "wr04_scene02_couch_14")
	teleport_to_slate_pos("CS_blunt", 1.89, 0.0, 1.296, "slate_smansion_main")
	play_custom_action_do("CS_blunt", "wr04_scene02_blunt_14")
	delay(3.13333)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
end

function cutscene_end()
	character_show("#PLAYER#")
	stop_custom_actions("CS_price")
	stop_custom_actions("CS_donnie")
	stop_custom_actions("CS_sharp")
	stop_custom_actions("CS_lin")
	stop_custom_actions("CS_couch")
	stop_custom_actions("CS_blunt")
	letterbox_fade_out(true)
	fade_out(0.5)
end
