---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: wr05_scene01
-- Exported By: Ev.religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk40", true )
	load_chunks("sr_chunk40_Price", "sr_chunk40")
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
	thread_new_cutscene_shot("shot12", 12)
	thread_new_cutscene_shot("shot13", 13)
	thread_new_cutscene_shot("shot14", 14)
	thread_new_cutscene_shot("shot15", 15)
	thread_new_cutscene_shot("shot16", 16)
	thread_new_cutscene_shot("shot17", 17)
	thread_new_cutscene_shot("shot18", 18)
	thread_new_cutscene_shot("shot19", 19)
	thread_new_cutscene_shot("shot20", 20)
	thread_new_cutscene_shot("shot21", 21)
	thread_new_cutscene_shot("shot22", 22)
	thread_new_cutscene_shot("shot23", 23)
	thread_new_cutscene_shot("shot24", 24)
	thread_new_cutscene_shot("shot25", 25)
	thread_new_cutscene_shot("shot26", 26)
end

function shot1()
	local excluded_lights_1 = {"BB FreeSpot02", "BB Omni01", "BB Omni07", "BB Omni11", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Omni18", "BB Price Walkaway Fill", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Omni14", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_1, 16, false)

	local included_lights_1 = {"BB FreeSpot01", "BB Omni02", "BB Omni03", "BB Omni06", "BB Omni12", "BB Price Key Omni20", "BB Chair Couch Omni21", "BB Shadowcast FreeSpot06", "BB Omni15"}
	light_set_lights(included_lights_1, 9, true)

	fade_in(0.5)
	select_slate("slate_smansion_living")
	character_hide("#PLAYER#")
	teleport_to_slate_pos("CS_priceh", 4.058, 0.0, 0.631, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_1")
	teleport_to_slate_pos("CS_lin", 13.341, 0.0, 6.332, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_1")
	teleport_to_slate_pos("CS_donnie", 8.957, 0.0, 5.376, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_1")
	teleport_to_slate_pos("CS_sharp", 0.327, 0.0, -1.712, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_1")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_1")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_1")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_1")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_1")
	set_level_lights(false)
end

function shot2()
	local excluded_lights_2 = {"BB FreeSpot02", "BB Omni01", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni15", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_2, 20, false)

	local included_lights_2 = {"BB FreeSpot01", "BB Omni02", "BB Omni12", "BB Omni13", "BB Omni04"}
	light_set_lights(included_lights_2, 5, true)

	teleport_to_slate_pos("CS_priceh", 4.057, 0.0, 0.631, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_2")
	teleport_to_slate_pos("CS_lin", 13.342, 0.0, 6.427, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_2")
	teleport_to_slate_pos("CS_donnie", 8.967, 0.0, 5.378, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_2")
	teleport_to_slate_pos("CS_sharp", 0.331, 0.0, -1.714, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_2")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_2")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_2")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_2")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_2")
end

function shot3()
	local excluded_lights_3 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni07", "BB Omni12", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Omni18", "BB Price Walkaway Fill", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Omni14", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_3, 18, false)

	local included_lights_3 = {"BB Omni03", "BB Omni06", "BB Omni11", "BB Price Key Omni20", "BB Chair Couch Omni21", "BB Shadowcast FreeSpot06", "BB Omni15"}
	light_set_lights(included_lights_3, 7, true)

	teleport_to_slate_pos("CS_priceh", 4.047, 0.0, 0.632, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_3")
	teleport_to_slate_pos("CS_lin", 13.342, 0.0, 6.511, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_3")
	teleport_to_slate_pos("CS_donnie", 8.963, 0.0, 5.376, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_3")
	teleport_to_slate_pos("CS_sharp", 0.332, 0.0, -1.709, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_3")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_3")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_3")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_3")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_3")
end

function shot4()
	local excluded_lights_4 = {"BB FreeSpot02", "BB Omni01", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni15", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_4, 20, false)

	local included_lights_4 = {"BB FreeSpot01", "BB Omni02", "BB Omni12", "BB Omni13", "BB Omni04"}
	light_set_lights(included_lights_4, 5, true)

	teleport_to_slate_pos("CS_priceh", 4.043, 0.0, 0.63, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_4")
	teleport_to_slate_pos("CS_lin", 13.342, 0.0, 6.549, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_4")
	teleport_to_slate_pos("CS_donnie", 8.964, 0.0, 5.373, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_4")
	teleport_to_slate_pos("CS_sharp", 0.327, 0.0, -1.711, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_4")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_4")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_4")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_4")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_4")
end

function shot5()
	local excluded_lights_5 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni07", "BB Omni12", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Omni18", "BB Price Walkaway Fill", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_5, 18, false)

	local included_lights_5 = {"BB Omni03", "BB Omni06", "BB Omni11", "BB Price Key Omni20", "BB Chair Couch Omni21", "BB Omni15", "BB Omni16"}
	light_set_lights(included_lights_5, 7, true)

	teleport_to_slate_pos("CS_priceh", 4.045, 0.0, 0.634, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_5")
	teleport_to_slate_pos("CS_lin", 13.342, 0.0, 6.597, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_5")
	teleport_to_slate_pos("CS_donnie", 8.959, 0.0, 5.373, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_5")
	teleport_to_slate_pos("CS_sharp", 0.327, 0.0, -1.73, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_5")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_5")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_5")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_5")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_5")
end

function shot6()
	local excluded_lights_6 = {"BB FreeSpot02", "BB Omni01", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Shadowcast FreeSpot06", "BB Omni15", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_6, 19, false)

	local included_lights_6 = {"BB FreeSpot01", "BB Omni02", "BB Omni12", "BB Omni04", "BB FreeSpot03", "BB Omni14"}
	light_set_lights(included_lights_6, 6, true)

	teleport_to_slate_pos("CS_priceh", 4.042, 0.0, 0.634, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_6")
	teleport_to_slate_pos("CS_lin", 11.588, 0.0, 6.319, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_6")
	teleport_to_slate_pos("CS_donnie", 8.938, 0.0, 5.38, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_6")
	teleport_to_slate_pos("CS_sharp", 0.325, 0.0, -1.718, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_6")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_6")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_6")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_6")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_6")
end

function shot7()
	local excluded_lights_7 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni11", "BB Omni13", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Walkaway Fill", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Omni14", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_7, 14, false)

	local included_lights_7 = {"BB Omni02", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni12", "BB Omni17", "BB Price Key Omni20", "BB Omni18", "BB Chair Couch Omni21", "BB Shadowcast FreeSpot06", "BB Omni15"}
	light_set_lights(included_lights_7, 11, true)

	teleport_to_slate_pos("CS_priceh", 4.044, 0.0, 0.635, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_7")
	teleport_to_slate_pos("CS_lin", 7.921, 0.0, 3.258, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_7")
	teleport_to_slate_pos("CS_donnie", 6.836, 0.0, 4.671, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_7")
	teleport_to_slate_pos("CS_sharp", 0.325, 0.0, -1.716, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_7")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_7")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_7")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_7")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_7")
end

function shot8()
	local excluded_lights_8 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni15", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_8, 18, false)

	local included_lights_8 = {"BB Omni02", "BB Omni12", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni16"}
	light_set_lights(included_lights_8, 7, true)

	teleport_to_slate_pos("CS_priceh", 4.04, 0.0, 0.638, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_8")
	teleport_to_slate_pos("CS_lin", 5.0, 0.0, 3.191, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_8")
	teleport_to_slate_pos("CS_donnie", 4.653, 0.0, 4.192, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_8")
	teleport_to_slate_pos("CS_sharp", 0.325, 0.0, -1.715, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_8")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_8")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_8")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_8")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_8")
end

function shot9()
	local excluded_lights_9 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni02", "BB Omni12", "BB Omni13", "BB Lin CU key Omni19", "BB Omni18", "BB Price Walkaway Fill", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Omni14", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_9, 13, false)

	local included_lights_9 = {"BB Omni01", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni17", "BB Donnie key Omni18", "BB Price Key Omni20", "BB Chair Couch Omni21", "BB Shadowcast FreeSpot06", "BB Omni15", "BB Omni16"}
	light_set_lights(included_lights_9, 12, true)

	teleport_to_slate_pos("CS_priceh", 4.04, 0.0, 0.64, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_9")
	teleport_to_slate_pos("CS_lin", 3.777, 0.0, 3.009, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_9")
	teleport_to_slate_pos("CS_donnie", 3.723, 0.0, 3.369, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_9")
	teleport_to_slate_pos("CS_sharp", 0.325, 0.0, -1.716, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_9")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_9")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_9")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_9")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_9")
end

function shot10()
	local excluded_lights_10 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni02", "BB Omni03", "BB Omni11", "BB Omni12", "BB Omni13", "BB Lin CU key Omni19", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_10, 17, false)

	local included_lights_10 = {"BB Omni01", "BB Omni06", "BB Omni07", "BB Omni17", "BB Donnie key Omni18", "BB Price Key Omni20", "BB Omni18", "BB Omni15"}
	light_set_lights(included_lights_10, 8, true)

	teleport_to_slate_pos("CS_priceh", 3.761, 0.0, 1.064, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_10")
	teleport_to_slate_pos("CS_lin", 3.792, 0.0, 2.151, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_10")
	teleport_to_slate_pos("CS_donnie", 3.339, 0.0, 2.675, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_10")
	teleport_to_slate_pos("CS_sharp", 0.325, 0.0, -1.715, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_10")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_10")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_10")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_10")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_10")
end

function shot11()
	local excluded_lights_11 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni07", "BB Omni12", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_11, 20, false)

	local included_lights_11 = {"BB Omni03", "BB Omni06", "BB Omni11", "BB Price Key Omni20", "BB Omni15"}
	light_set_lights(included_lights_11, 5, true)

	teleport_to_slate_pos("CS_priceh", 3.812, 0.0, 1.147, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_11")
	teleport_to_slate_pos("CS_lin", 3.796, 0.0, 2.145, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_11")
	teleport_to_slate_pos("CS_donnie", 3.439, 0.0, 2.711, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_11")
	teleport_to_slate_pos("CS_sharp", 0.325, 0.0, -1.715, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_11")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_11")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_11")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_11")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_11")
end

function shot12()
	local excluded_lights_12 = {"BB FreeSpot02", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni15", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_12, 19, false)

	local included_lights_12 = {"BB FreeSpot01", "BB Omni01", "BB Omni02", "BB Omni12", "BB Omni13", "BB Omni04"}
	light_set_lights(included_lights_12, 6, true)

	teleport_to_slate_pos("CS_priceh", 3.834, 0.0, 1.233, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_12")
	teleport_to_slate_pos("CS_lin", 3.801, 0.0, 2.146, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_12")
	teleport_to_slate_pos("CS_donnie", 3.446, 0.0, 2.688, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_12")
	teleport_to_slate_pos("CS_sharp", 0.325, 0.0, -1.715, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_12")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_12")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_12")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_12")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_12")
end

function shot13()
	local excluded_lights_13 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni03", "BB Omni07", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Omni18", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_13, 20, false)

	local included_lights_13 = {"BB Omni06", "BB Price Key Omni20", "BB Price Walkaway Fill", "BB Omni15", "BB Omni16"}
	light_set_lights(included_lights_13, 5, true)

	teleport_to_slate_pos("CS_priceh", 3.83, 0.0, 1.263, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_13")
	teleport_to_slate_pos("CS_lin", 3.799, 0.0, 2.137, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_13")
	teleport_to_slate_pos("CS_donnie", 3.423, 0.0, 2.701, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_13")
	teleport_to_slate_pos("CS_sharp", 0.325, 0.0, -1.715, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_13")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_13")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_13")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_13")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_13")
end

function shot14()
	local excluded_lights_14 = {"BB FreeSpot02", "BB Omni01", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni15", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_14, 20, false)

	local included_lights_14 = {"BB FreeSpot01", "BB Omni02", "BB Omni12", "BB Omni13", "BB Omni04"}
	light_set_lights(included_lights_14, 5, true)

	teleport_to_slate_pos("CS_priceh", 4.422, 0.0, 1.695, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_14")
	teleport_to_slate_pos("CS_lin", 3.718, 0.0, 2.328, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_14")
	teleport_to_slate_pos("CS_donnie", 3.431, 0.0, 2.729, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_14")
	teleport_to_slate_pos("CS_sharp", 0.326, 0.0, -1.721, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_14")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_14")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_14")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_14")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_14")
end

function shot15()
	local excluded_lights_15 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni06", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Price Key Omni20", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni16"}
	light_set_lights(excluded_lights_15, 19, false)

	local included_lights_15 = {"BB Omni03", "BB Omni07", "BB Lin CU key Omni19", "BB Omni18", "BB Omni15", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(included_lights_15, 6, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_15")
	teleport_to_slate_pos("CS_lin", 3.678, 0.0, 1.962, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_15")
	teleport_to_slate_pos("CS_donnie", 3.342, 0.0, 2.73, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_15")
	teleport_to_slate_pos("CS_sharp", 0.327, 0.0, -1.712, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_15")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_15")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_15")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_15")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_15")
end

function shot16()
	local excluded_lights_16 = {"BB FreeSpot02", "BB Omni01", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni15", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_16, 20, false)

	local included_lights_16 = {"BB FreeSpot01", "BB Omni02", "BB Omni12", "BB Omni13", "BB Omni04"}
	light_set_lights(included_lights_16, 5, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_16")
	teleport_to_slate_pos("CS_lin", 3.454, 0.0, 1.601, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_16")
	teleport_to_slate_pos("CS_donnie", 3.35, 0.0, 2.772, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_16")
	teleport_to_slate_pos("CS_sharp", 0.327, 0.0, -1.711, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_16")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_16")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_16")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_16")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_16")
end

function shot17()
	local excluded_lights_17 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni06", "BB Omni12", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni16"}
	light_set_lights(excluded_lights_17, 19, false)

	local included_lights_17 = {"BB Omni03", "BB Omni07", "BB Omni11", "BB Lin CU key Omni19", "BB Omni15", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(included_lights_17, 6, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_17")
	teleport_to_slate_pos("CS_lin", 3.469, 0.0, 1.62, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_17")
	teleport_to_slate_pos("CS_donnie", 3.327, 0.0, 2.738, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_17")
	teleport_to_slate_pos("CS_sharp", 0.327, 0.0, -1.71, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_17")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_17")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_17")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_17")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_17")
end

function shot18()
	local excluded_lights_18 = {"BB FreeSpot02", "BB Omni01", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni15", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_18, 20, false)

	local included_lights_18 = {"BB FreeSpot01", "BB Omni02", "BB Omni12", "BB Omni13", "BB Omni04"}
	light_set_lights(included_lights_18, 5, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_18")
	teleport_to_slate_pos("CS_lin", 3.502, 0.0, 1.614, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_18")
	teleport_to_slate_pos("CS_donnie", 3.334, 0.0, 2.723, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_18")
	teleport_to_slate_pos("CS_sharp", 0.328, 0.0, -1.71, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_18")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_18")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_18")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_18")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_18")
end

function shot19()
	local excluded_lights_19 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni03", "BB Omni11", "BB Omni13", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Omni14", "BB Omni16"}
	light_set_lights(excluded_lights_19, 16, false)

	local included_lights_19 = {"BB Omni06", "BB Omni07", "BB Omni12", "BB Omni17", "BB Donnie key Omni18", "BB Omni18", "BB Shadowcast FreeSpot06", "BB Omni15", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(included_lights_19, 9, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_19")
	teleport_to_slate_pos("CS_lin", 3.498, 0.0, 1.608, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_19")
	teleport_to_slate_pos("CS_donnie", 3.328, 0.0, 2.724, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_19")
	teleport_to_slate_pos("CS_sharp", 0.328, 0.0, -1.709, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_19")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_19")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_19")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_19")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_19")
end

function shot20()
	local excluded_lights_20 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni03", "BB Omni11", "BB Omni12", "BB Omni13", "BB Price Key Omni20", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni16"}
	light_set_lights(excluded_lights_20, 17, false)

	local included_lights_20 = {"BB Omni06", "BB Omni07", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Omni18", "BB Omni15", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(included_lights_20, 8, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_20")
	teleport_to_slate_pos("CS_lin", 3.47, 0.0, 1.628, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_20")
	teleport_to_slate_pos("CS_donnie", 3.418, 0.0, 2.703, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_20")
	teleport_to_slate_pos("CS_sharp", 0.327, 0.0, -1.707, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_20")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_20")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_20")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_20")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_20")
end

function shot21()
	local excluded_lights_21 = {"BB FreeSpot02", "BB Omni01", "BB Omni03", "BB Omni11", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Lin Walkaway Fill01", "BB FreeSpot03", "BB Omni14", "BB Omni15", "BB Omni16"}
	light_set_lights(excluded_lights_21, 15, false)

	local included_lights_21 = {"BB FreeSpot01", "BB Omni02", "BB Omni06", "BB Omni07", "BB Omni12", "BB Omni13", "BB Chair Couch Omni21", "BB Omni04", "BB Shadowcast FreeSpot06", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(included_lights_21, 10, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_21")
	teleport_to_slate_pos("CS_lin", 3.394, 0.0, 1.578, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_21")
	teleport_to_slate_pos("CS_donnie", 3.516, 0.0, 2.541, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_21")
	teleport_to_slate_pos("CS_sharp", 0.327, 0.0, -1.708, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_21")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_21")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_21")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_21")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_21")
end

function shot22()
	local excluded_lights_22 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni02", "BB Omni03", "BB Omni11", "BB Omni12", "BB Omni13", "BB Price Key Omni20", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni16"}
	light_set_lights(excluded_lights_22, 16, false)

	local included_lights_22 = {"BB Omni01", "BB Omni06", "BB Omni07", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Omni18", "BB Omni15", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(included_lights_22, 9, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_22")
	teleport_to_slate_pos("CS_lin", 3.372, 0.0, 1.515, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_22")
	teleport_to_slate_pos("CS_donnie", 3.465, 0.0, 2.688, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_22")
	teleport_to_slate_pos("CS_sharp", 0.326, 0.0, -1.708, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_22")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_22")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_22")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_22")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_22")
end

function shot23()
	local excluded_lights_23 = {"BB FreeSpot02", "BB Omni01", "BB Omni03", "BB Omni06", "BB Omni07", "BB Omni11", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Omni18", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni15", "BB Omni16", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(excluded_lights_23, 20, false)

	local included_lights_23 = {"BB FreeSpot01", "BB Omni02", "BB Omni12", "BB Omni13", "BB Omni04"}
	light_set_lights(included_lights_23, 5, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_23")
	teleport_to_slate_pos("CS_lin", 3.371, 0.0, 1.512, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_23")
	teleport_to_slate_pos("CS_donnie", 3.39, 0.0, 2.685, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_23")
	teleport_to_slate_pos("CS_sharp", 0.326, 0.0, -1.709, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_23")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_23")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_23")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_23")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_23")
end

function shot24()
	local excluded_lights_24 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni02", "BB Omni03", "BB Omni11", "BB Omni12", "BB Omni13", "BB Price Key Omni20", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni16"}
	light_set_lights(excluded_lights_24, 16, false)

	local included_lights_24 = {"BB Omni01", "BB Omni06", "BB Omni07", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Omni18", "BB Omni15", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(included_lights_24, 9, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_24")
	teleport_to_slate_pos("CS_lin", 3.375, 0.0, 1.513, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_24")
	teleport_to_slate_pos("CS_donnie", 3.33, 0.0, 2.718, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_24")
	teleport_to_slate_pos("CS_sharp", 0.325, 0.0, -1.737, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_24")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_24")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_24")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_24")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_24")
end

function shot25()
	local excluded_lights_25 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni11", "BB Omni13", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Price Walkaway Fill", "BB Lin Walkaway Fill01", "BB Omni04", "BB FreeSpot03", "BB Omni14", "BB Omni16"}
	light_set_lights(excluded_lights_25, 14, false)

	local included_lights_25 = {"BB Omni03", "BB Omni06", "BB Omni07", "BB Omni12", "BB Omni17", "BB Donnie key Omni18", "BB Omni18", "BB Chair Couch Omni21", "BB Shadowcast FreeSpot06", "BB Omni15", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(included_lights_25, 11, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_25")
	teleport_to_slate_pos("CS_lin", 3.4, 0.0, 1.703, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_25")
	teleport_to_slate_pos("CS_donnie", 3.377, 0.0, 2.772, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_25")
	teleport_to_slate_pos("CS_sharp", 0.323, 0.0, -1.743, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_25")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_25")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_25")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_25")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_25")
end

function shot26()
	local excluded_lights_26 = {"BB FreeSpot01", "BB FreeSpot02", "BB Omni01", "BB Omni02", "BB Omni03", "BB Omni06", "BB Omni11", "BB Omni12", "BB Omni13", "BB Omni17", "BB Donnie key Omni18", "BB Lin CU key Omni19", "BB Price Key Omni20", "BB Price Walkaway Fill", "BB Chair Couch Omni21", "BB Omni04", "BB FreeSpot03", "BB Shadowcast FreeSpot06", "BB Omni14", "BB Omni15", "BB Omni16"}
	light_set_lights(excluded_lights_26, 21, false)

	local included_lights_26 = {"BB Omni07", "BB Omni18", "BB Lin Walkaway Fill01", "BB Lin Flat Key FreeSpot04"}
	light_set_lights(included_lights_26, 4, true)

	teleport_to_slate_pos("CS_priceh", 10.605, 0.0, 4.674, "slate_smansion_living")
	play_custom_action_do("CS_priceh", "wr05_scene01_price_26")
	teleport_to_slate_pos("CS_lin", 3.842, 0.0, 3.229, "slate_smansion_living")
	play_custom_action_do("CS_lin", "wr05_scene01_lin_26")
	teleport_to_slate_pos("CS_donnie", 4.53, 0.0, 3.645, "slate_smansion_living")
	play_custom_action_do("CS_donnie", "wr05_scene01_donnie_26")
	teleport_to_slate_pos("CS_sharp", 0.324, 0.0, -1.737, "slate_smansion_living")
	play_custom_action_do("CS_sharp", "wr05_scene01_sharp_26")
	teleport_to_slate_pos("CS_Couch", 3.501, 0.0, -0.192, "slate_smansion_living")
	play_custom_action_do("CS_Couch", "wr05_scene01_Couch_26")
	teleport_to_slate_pos("CS_Chair", 4.615, 0.0, 2.501, "slate_smansion_living")
	play_custom_action_do("CS_Chair", "wr05_scene01_Chair_26")
	teleport_to_slate_pos("CS_ChairB", 0.324, 0.0, -1.727, "slate_smansion_living")
	play_custom_action_do("CS_ChairB", "wr05_scene01_ChairB_26")
	teleport_to_slate_pos("CS_AutoMag", 4.102, 0.0, 1.137, "slate_smansion_living")
	play_custom_action_do("CS_AutoMag", "wr05_scene01_AutoMag_26")
	delay(2.8)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
end

function cutscene_end()
	character_show("#PLAYER#")
	stop_custom_actions("CS_priceh")
	stop_custom_actions("CS_lin")
	stop_custom_actions("CS_donnie")
	stop_custom_actions("CS_sharp")
	stop_custom_actions("CS_Couch")
	stop_custom_actions("CS_Chair")
	stop_custom_actions("CS_ChairB")
	stop_custom_actions("CS_AutoMag")
	letterbox_fade_out(true)
	fade_out(0.5)
end
