-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\wr05_scene02\wr05_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk40_Price__interiors.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
	thread_new_cutscene_shot("shot9", 9)
	thread_new_cutscene_shot("shot10", 10)
	thread_new_cutscene_shot("shot11", 11)
	thread_new_cutscene_shot("shot12", 12)
	thread_new_cutscene_shot("shot13", 13)
	thread_new_cutscene_shot("shot14", 14)
	thread_new_cutscene_shot("shot15", 15)
	thread_new_cutscene_shot("shot16", 16)
	thread_new_cutscene_shot("shot17", 17)
	thread_new_cutscene_shot("shot18", 18)
	thread_new_cutscene_shot("shot19", 19)
end

function shot1()
	set_level_lights(false)
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("CS_cell", 0.601083, 0.0, 3.34699, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_1")
	teleport_to_slate_pos("CS_Price", 0.682268, 0.0, 3.21352, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_1")
	teleport_to_slate_pos("CS_Sharp", 0.93466, 0.0, 4.78171, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_1")
end

function shot2()
	teleport_to_slate_pos("CS_cell", -1.40458, 0.0, 3.38747, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_2")
	teleport_to_slate_pos("CS_Price", -1.28802, 0.0, 3.26617, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_2")
	teleport_to_slate_pos("CS_Sharp", 0.933169, 0.0, 4.78662, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_2")
end

function shot3()
	teleport_to_slate_pos("CS_cell", -0.0947543, 0.0, 6.19041, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_3")
	teleport_to_slate_pos("CS_Price", 0.178454, 0.0, 3.59073, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_3")
	teleport_to_slate_pos("CS_Sharp", 0.932829, 0.0, 4.78707, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_3")
end

function shot4()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_4")
	teleport_to_slate_pos("CS_Price", 0.340461, 0.0, 3.10861, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_4")
	teleport_to_slate_pos("CS_Sharp", 0.940502, 0.0, 4.77134, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_4")
end

function shot5()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_5")
	teleport_to_slate_pos("CS_Price", 0.932944, 0.0, 3.16246, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_5")
	teleport_to_slate_pos("CS_Sharp", 0.941625, 0.0, 4.76826, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_5")
end

function shot6()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_6")
	teleport_to_slate_pos("CS_Price", 0.595044, 0.0, 3.11375, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_6")
	teleport_to_slate_pos("CS_Sharp", 0.941462, 0.0, 4.76743, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_6")
end

function shot7()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_7")
	teleport_to_slate_pos("CS_Price", 0.597071, 0.0, 3.11901, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_7")
	teleport_to_slate_pos("CS_Sharp", 0.94069, 0.0, 4.76877, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_7")
end

function shot8()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_8")
	teleport_to_slate_pos("CS_Price", 0.922872, 0.0, 3.09875, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_8")
	teleport_to_slate_pos("CS_Sharp", 0.933865, 0.0, 4.64603, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_8")
end

function shot9()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_9")
	teleport_to_slate_pos("CS_Price", 1.4407, 0.0, 3.20162, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_9")
	teleport_to_slate_pos("CS_Sharp", 0.513703, 0.0, 3.866, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_9")
end

function shot10()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_10")
	teleport_to_slate_pos("CS_Price", 1.58537, 0.0, 3.28381, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_10")
	teleport_to_slate_pos("CS_Sharp", 0.547069, 0.0, 3.86591, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_10")
end

function shot11()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_11")
	teleport_to_slate_pos("CS_Price", 1.59681, 0.0, 3.2751, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_11")
	teleport_to_slate_pos("CS_Sharp", 0.546011, 0.0, 3.87163, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_11")
end

function shot12()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_12")
	teleport_to_slate_pos("CS_Price", 1.55595, 0.0, 3.22897, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_12")
	teleport_to_slate_pos("CS_Sharp", 0.548195, 0.0, 3.87251, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_12")
end

function shot13()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_13")
	teleport_to_slate_pos("CS_Price", 1.44332, 0.0, 3.15817, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_13")
	teleport_to_slate_pos("CS_Sharp", 0.556205, 0.0, 3.87831, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_13")
end

function shot14()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_14")
	teleport_to_slate_pos("CS_Price", 1.32424, 0.0, 3.13812, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_14")
	teleport_to_slate_pos("CS_Sharp", 0.493874, 0.0, 3.8661, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_14")
end

function shot15()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_15")
	teleport_to_slate_pos("CS_Price", 1.39635, 0.0, 3.14745, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_15")
	teleport_to_slate_pos("CS_Sharp", 1.16551, 0.0, 3.98823, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_15")
end

function shot16()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_16")
	teleport_to_slate_pos("CS_Price", 1.2913, 0.0, 3.1323, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_16")
	teleport_to_slate_pos("CS_Sharp", 1.17844, 0.0, 3.95856, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_16")
end

function shot17()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_17")
	teleport_to_slate_pos("CS_Price", 1.30247, 0.0, 3.10431, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_17")
	teleport_to_slate_pos("CS_Sharp", 1.56762, 0.0, 4.01133, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_17")
end

function shot18()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_18")
	teleport_to_slate_pos("CS_Price", 1.36156, 0.0, 3.63366, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_18")
	teleport_to_slate_pos("CS_Sharp", 2.64249, 0.0, 4.45567, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_18")
end

function shot19()
	teleport_to_slate_pos("CS_cell", -0.2029, 0.0, 6.20669, "slate_smansion_main")
	play_custom_action_do("CS_cell", "wr05_scene02_cell_19")
	teleport_to_slate_pos("CS_Price", 1.361, 0.0, 3.62427, "slate_smansion_main")
	play_custom_action_do("CS_Price", "wr05_scene02_price_19")
	teleport_to_slate_pos("CS_Sharp", 2.64393, 0.0, 4.4516, "slate_smansion_main")
	play_custom_action_do("CS_Sharp", "wr05_scene02_sharp_19")
	delay(3)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end

function cutscene_end()
	stop_custom_actions("CS_cell")
	stop_custom_actions("CS_Price")
	stop_custom_actions("CS_Sharp")
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end
