-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\wr06_scene02\wr06_scene02.cts
-- Level:D:\projects\blingbling\data\levels\SaintsRow\sr_chunk09_ph__interiors.cts
-------------------------------------


function cutscene_main()
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
end

function shot1()
	set_level_lights(false)
	fade_in(0.5)
	letterbox_fade_in(true)
	teleport_to_slate_pos("#PLAYER#", 1.92727, 0.0, -1.37469, "slate_wr_poolhall")
	play_custom_action_do("#PLAYER#", "wr06_scene02_player_1")
	teleport_to_slate_pos("CS_lin", -1.68522, 0.0, -0.171719, "slate_wr_poolhall")
	play_custom_action_do("CS_lin", "wr06_scene02_lin_1")
	teleport_to_slate_pos("CS_sharp", -5.40728, 0.0, -0.786783, "slate_wr_poolhall")
	play_custom_action_do("CS_sharp", "wr06_scene02_sharp_1")
	teleport_to_slate_pos("CS_rollerz", -5.4972, 0.0, 0.375112, "slate_wr_poolhall")
	play_custom_action_do("CS_rollerz", "wr06_scene02_rollerz_1")
	teleport_to_slate_pos("CS_bat_rollerz", -5.49238, 0.0, 0.226346, "slate_wr_poolhall")
	play_custom_action_do("CS_bat_rollerz", "wr06_scene02_bat_rollerz_1")
	teleport_to_slate_pos("CS_chair", -1.57588, 0.0, -0.197016, "slate_wr_poolhall")
	play_custom_action_do("CS_chair", "wr06_scene02_chair_1")
end

function shot2()
	teleport_to_slate_pos("#PLAYER#", -2.08816, 0.0, 1.20388, "slate_wr_poolhall")
	play_custom_action_do("#PLAYER#", "wr06_scene02_player_2")
	teleport_to_slate_pos("CS_lin", -1.68522, 0.0, -0.171719, "slate_wr_poolhall")
	play_custom_action_do("CS_lin", "wr06_scene02_lin_2")
	teleport_to_slate_pos("CS_sharp", -5.40672, 0.0, -0.777288, "slate_wr_poolhall")
	play_custom_action_do("CS_sharp", "wr06_scene02_sharp_2")
	teleport_to_slate_pos("CS_rollerz", -5.46451, 0.0, 0.320571, "slate_wr_poolhall")
	play_custom_action_do("CS_rollerz", "wr06_scene02_rollerz_2")
	teleport_to_slate_pos("CS_bat_rollerz", -5.56255, 0.0, 0.215041, "slate_wr_poolhall")
	play_custom_action_do("CS_bat_rollerz", "wr06_scene02_bat_rollerz_2")
	teleport_to_slate_pos("CS_chair", -1.57588, 0.0, -0.197016, "slate_wr_poolhall")
	play_custom_action_do("CS_chair", "wr06_scene02_chair_2")
end

function shot3()
	teleport_to_slate_pos("#PLAYER#", -2.90998, 0.0, -0.275618, "slate_wr_poolhall")
	play_custom_action_do("#PLAYER#", "wr06_scene02_player_3")
	teleport_to_slate_pos("CS_lin", -1.68522, 0.0, -0.171719, "slate_wr_poolhall")
	play_custom_action_do("CS_lin", "wr06_scene02_lin_3")
	teleport_to_slate_pos("CS_sharp", -5.42191, 0.0, -0.700301, "slate_wr_poolhall")
	play_custom_action_do("CS_sharp", "wr06_scene02_sharp_3")
	teleport_to_slate_pos("CS_rollerz", -5.34825, 0.0, 0.187338, "slate_wr_poolhall")
	play_custom_action_do("CS_rollerz", "wr06_scene02_rollerz_3")
	teleport_to_slate_pos("CS_bat_rollerz", -5.45386, 0.0, 0.10764, "slate_wr_poolhall")
	play_custom_action_do("CS_bat_rollerz", "wr06_scene02_bat_rollerz_3")
	teleport_to_slate_pos("CS_chair", -1.57588, 0.0, -0.197016, "slate_wr_poolhall")
	play_custom_action_do("CS_chair", "wr06_scene02_chair_3")
end

function shot4()
	teleport_to_slate_pos("#PLAYER#", -2.8697, 0.0, -0.354777, "slate_wr_poolhall")
	play_custom_action_do("#PLAYER#", "wr06_scene02_player_4")
	teleport_to_slate_pos("CS_lin", -1.68522, 0.0, -0.171719, "slate_wr_poolhall")
	play_custom_action_do("CS_lin", "wr06_scene02_lin_4")
	teleport_to_slate_pos("CS_sharp", -4.24549, 0.0, -0.708424, "slate_wr_poolhall")
	play_custom_action_do("CS_sharp", "wr06_scene02_sharp_4")
	teleport_to_slate_pos("CS_rollerz", -3.95515, 0.0, 0.120663, "slate_wr_poolhall")
	play_custom_action_do("CS_rollerz", "wr06_scene02_rollerz_4")
	teleport_to_slate_pos("CS_bat_rollerz", -4.18562, 0.0, 0.145153, "slate_wr_poolhall")
	play_custom_action_do("CS_bat_rollerz", "wr06_scene02_bat_rollerz_4")
	teleport_to_slate_pos("CS_chair", -1.57588, 0.0, -0.197016, "slate_wr_poolhall")
	play_custom_action_do("CS_chair", "wr06_scene02_chair_4")
	delay(11.4667)
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end

function cutscene_end()
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_lin")
	stop_custom_actions("CS_sharp")
	stop_custom_actions("CS_rollerz")
	stop_custom_actions("CS_bat_rollerz")
	stop_custom_actions("CS_chair")
	letterbox_fade_out(true)
	fade_out(0.5)
	set_level_lights(true)
end
