-------------------------------------
-- Generated by "One Button Export"
-- Cutscene:D:\projects\blingbling\data\cutscenes\wr06_scene01\wr06_scene01.cts
-- Level:D:\projects\blingbling\data\cutscenes\wr06_scene01\wr06_scene01.cts
-------------------------------------


function cutscene_main()
	load_chunk("sr_chunk02_church", true )
	load_chunks("sr_chunk02", "sr_chunk09_ph")
	load_chunks("sr_chunk09_ph", "sr_chunk02")
end

function shot1()
end

function shot2()
end

function shot3()
end

function shot4()
end

function shot5()
end

function shot6()
end

function shot7()
end

function shot8()
end

function shot9()
end

function cutscene_abort()
end

function cutscene_end()
end
