---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: wr09_scene02
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk40", true )
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
end

function shot1()
	fade_in(0.5)
	select_slate("slate_wr09_scene02")
	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_truck", -48.028, -6.679, -69.933, "slate_wr09_scene02")
	play_custom_action_do("CS_truck", "wr09_scene02_truck_1")
	teleport_to_slate_pos("CS_trailer", -57.56, -6.842, -78.639, "slate_wr09_scene02")
	play_custom_action_do("CS_trailer", "wr09_scene02_trailer_1")
	teleport_to_slate_pos("#PLAYER#", 5.835, 0.0, -5.505, "slate_wr09_scene02")
	play_custom_action_do("#PLAYER#", "wr09_scene02_player_1")
	teleport_to_slate_pos("CS_price", -68.149, 0.0, -75.782, "slate_wr09_scene02")
	play_custom_action_do("CS_price", "wr09_scene02_price_1")
	spawning_peds(false)
	spawning_cars(false)
	set_human_cutscene_weapon("beretta")
end

function shot2()
	teleport_to_slate_pos("CS_truck", -40.305, -5.396, -46.68, "slate_wr09_scene02")
	play_custom_action_do("CS_truck", "wr09_scene02_truck_2")
	teleport_to_slate_pos("CS_trailer", -47.877, -5.376, -57.102, "slate_wr09_scene02")
	play_custom_action_do("CS_trailer", "wr09_scene02_trailer_2")
	teleport_to_slate_pos("#PLAYER#", 2.654, 0.0, -4.118, "slate_wr09_scene02")
	play_custom_action_do("#PLAYER#", "wr09_scene02_player_2")
	teleport_to_slate_pos("CS_price", -68.177, 0.0, -75.812, "slate_wr09_scene02")
	play_custom_action_do("CS_price", "wr09_scene02_price_2")
end

function shot3()
	teleport_to_slate_pos("CS_truck", -40.149, -0.205, -45.64, "slate_wr09_scene02")
	play_custom_action_do("CS_truck", "wr09_scene02_truck_3")
	teleport_to_slate_pos("CS_trailer", -48.342, -0.182, -55.605, "slate_wr09_scene02")
	play_custom_action_do("CS_trailer", "wr09_scene02_trailer_3")
	teleport_to_slate_pos("#PLAYER#", 2.709, 0.0, -4.109, "slate_wr09_scene02")
	play_custom_action_do("#PLAYER#", "wr09_scene02_player_3")
	teleport_to_slate_pos("CS_price", -39.132, 0.0, -43.722, "slate_wr09_scene02")
	play_custom_action_do("CS_price", "wr09_scene02_price_3")
end

function shot4()
	teleport_to_slate_pos("CS_truck", -2.546, -0.205, -6.261, "slate_wr09_scene02")
	play_custom_action_do("CS_truck", "wr09_scene02_truck_4")
	teleport_to_slate_pos("CS_trailer", -11.376, -0.182, -15.678, "slate_wr09_scene02")
	play_custom_action_do("CS_trailer", "wr09_scene02_trailer_4")
	teleport_to_slate_pos("#PLAYER#", 0.968, 0.0, 0.952, "slate_wr09_scene02")
	play_custom_action_do("#PLAYER#", "wr09_scene02_player_4")
	teleport_to_slate_pos("CS_price", -1.554, 0.0, -4.316, "slate_wr09_scene02")
	play_custom_action_do("CS_price", "wr09_scene02_price_4")
end

function shot5()
	teleport_to_slate_pos("CS_truck", 22.607, -0.205, 19.945, "slate_wr09_scene02")
	play_custom_action_do("CS_truck", "wr09_scene02_truck_5")
	teleport_to_slate_pos("CS_trailer", 13.652, -0.182, 10.647, "slate_wr09_scene02")
	play_custom_action_do("CS_trailer", "wr09_scene02_trailer_5")
	teleport_to_slate_pos("#PLAYER#", 0.254, 0.0, 3.176, "slate_wr09_scene02")
	play_custom_action_do("#PLAYER#", "wr09_scene02_player_5")
	teleport_to_slate_pos("CS_price", 23.598, 0.0, 21.918, "slate_wr09_scene02")
	play_custom_action_do("CS_price", "wr09_scene02_price_5")
end

function shot6()
	teleport_to_slate_pos("CS_truck", 30.002, -0.205, 27.646, "slate_wr09_scene02")
	play_custom_action_do("CS_truck", "wr09_scene02_truck_6")
	teleport_to_slate_pos("CS_trailer", 21.005, -0.182, 18.389, "slate_wr09_scene02")
	play_custom_action_do("CS_trailer", "wr09_scene02_trailer_6")
	teleport_to_slate_pos("#PLAYER#", 0.1, 0.0, 2.944, "slate_wr09_scene02")
	play_custom_action_do("#PLAYER#", "wr09_scene02_player_6")
	teleport_to_slate_pos("CS_price", 31.002, 0.0, 29.615, "slate_wr09_scene02")
	play_custom_action_do("CS_price", "wr09_scene02_price_6")
end

function shot7()
	teleport_to_slate_pos("CS_truck", 30.002, -0.205, 27.646, "slate_wr09_scene02")
	play_custom_action_do("CS_truck", "wr09_scene02_truck_7")
	teleport_to_slate_pos("CS_trailer", 21.005, -0.182, 18.389, "slate_wr09_scene02")
	play_custom_action_do("CS_trailer", "wr09_scene02_trailer_7")
	teleport_to_slate_pos("#PLAYER#", 4.864, 0.0, -4.805, "slate_wr09_scene02")
	play_custom_action_do("#PLAYER#", "wr09_scene02_player_7")
	teleport_to_slate_pos("CS_price", 31.002, 0.0, 29.615, "slate_wr09_scene02")
	play_custom_action_do("CS_price", "wr09_scene02_price_7")
	fade_out(0.5)
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	spawning_peds(true)
	spawning_cars(true)
end

function cutscene_end()
	stop_custom_actions("CS_truck")
	stop_custom_actions("CS_trailer")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_price")
	letterbox_fade_out(true)
	fade_out(0.5)
	spawning_peds(true)
	spawning_cars(true)
end
