---------------------------------
-- Generated By: SR Cutscene Exporter
-- Cutscene: wr09_scene04
-- Exported By: Ev.Religioso
---------------------------------


function cutscene_main()
	load_chunk("sr_chunk01", true )
	thread_new_cutscene_shot("shot1", 1)
	thread_new_cutscene_shot("shot2", 2)
	thread_new_cutscene_shot("shot3", 3)
	thread_new_cutscene_shot("shot4", 4)
	thread_new_cutscene_shot("shot5", 5)
	thread_new_cutscene_shot("shot6", 6)
	thread_new_cutscene_shot("shot7", 7)
	thread_new_cutscene_shot("shot8", 8)
end

function shot1()
	fade_in(0.5)
	select_slate("slate_wr09_scene04")
	character_show("#PLAYER#")
	teleport_to_slate_pos("CS_Price", -7.673, -0.125, -1.584, "slate_wr09_scene04")
	play_custom_action_do("CS_Price", "wr09_scene04_pr_1")
	teleport_to_slate_pos("#PLAYER#", 1.394, 0.318, -0.787, "slate_wr09_scene04")
	play_custom_action_do("#PLAYER#", "wr09_scene04_pl_1")
	teleport_to_slate_pos("CS_keys", -7.436, 0.0, -1.447, "slate_wr09_scene04")
	play_custom_action_do("CS_keys", "wr09_scene04_keys_1")
	teleport_to_slate_pos("CS_cellphone", 1.391, 0.0, -0.793, "slate_wr09_scene04")
	play_custom_action_do("CS_cellphone", "wr09_scene04_cell_1")
	time_of_day_character_shadows_enable(false)
	set_level_lights(false)
	spawning_peds(false)
	spawning_cars(false)
end

function shot2()
	teleport_to_slate_pos("CS_Price", -7.673, -0.125, -1.584, "slate_wr09_scene04")
	play_custom_action_do("CS_Price", "wr09_scene04_pr_2")
	teleport_to_slate_pos("#PLAYER#", -4.025, 0.058, -1.155, "slate_wr09_scene04")
	play_custom_action_do("#PLAYER#", "wr09_scene04_pl_2")
	teleport_to_slate_pos("CS_keys", -7.436, 0.0, -1.447, "slate_wr09_scene04")
	play_custom_action_do("CS_keys", "wr09_scene04_keys_2")
	teleport_to_slate_pos("CS_cellphone", -4.007, 0.0, -1.16, "slate_wr09_scene04")
	play_custom_action_do("CS_cellphone", "wr09_scene04_cell_2")
end

function shot3()
	teleport_to_slate_pos("CS_Price", -7.673, -0.125, -1.584, "slate_wr09_scene04")
	play_custom_action_do("CS_Price", "wr09_scene04_pr_3")
	teleport_to_slate_pos("#PLAYER#", -6.696, -0.101, -1.497, "slate_wr09_scene04")
	play_custom_action_do("#PLAYER#", "wr09_scene04_pl_3")
	teleport_to_slate_pos("CS_keys", -7.436, 0.0, -1.447, "slate_wr09_scene04")
	play_custom_action_do("CS_keys", "wr09_scene04_keys_3")
	teleport_to_slate_pos("CS_cellphone", -6.724, 0.0, -1.358, "slate_wr09_scene04")
	play_custom_action_do("CS_cellphone", "wr09_scene04_cell_3")
end

function shot4()
	teleport_to_slate_pos("CS_Price", -7.673, -0.125, -1.584, "slate_wr09_scene04")
	play_custom_action_do("CS_Price", "wr09_scene04_pr_4")
	teleport_to_slate_pos("#PLAYER#", -6.694, -0.119, -1.546, "slate_wr09_scene04")
	play_custom_action_do("#PLAYER#", "wr09_scene04_pl_4")
	teleport_to_slate_pos("CS_keys", -7.436, 0.0, -1.447, "slate_wr09_scene04")
	play_custom_action_do("CS_keys", "wr09_scene04_keys_4")
	teleport_to_slate_pos("CS_cellphone", -6.879, 0.0, -1.346, "slate_wr09_scene04")
	play_custom_action_do("CS_cellphone", "wr09_scene04_cell_4")
end

function shot5()
	fat_bones_enable("#PLAYER#", false) 
	teleport_to_slate_pos("CS_Price", -7.673, -0.125, -1.584, "slate_wr09_scene04")
	play_custom_action_do("CS_Price", "wr09_scene04_pr_5")
	teleport_to_slate_pos("#PLAYER#", -6.69, -0.097, -1.693, "slate_wr09_scene04")
	play_custom_action_do("#PLAYER#", "wr09_scene04_pl_5")
	teleport_to_slate_pos("CS_keys", -7.464, 0.0, -1.573, "slate_wr09_scene04")
	play_custom_action_do("CS_keys", "wr09_scene04_keys_5")
	teleport_to_slate_pos("CS_cellphone", -6.988, 0.0, -1.401, "slate_wr09_scene04")
	play_custom_action_do("CS_cellphone", "wr09_scene04_cell_5")
end

function shot6()
	teleport_to_slate_pos("CS_Price", -7.673, -0.125, -1.584, "slate_wr09_scene04")
	play_custom_action_do("CS_Price", "wr09_scene04_pr_6")
	teleport_to_slate_pos("#PLAYER#", -6.626, -0.087, -1.571, "slate_wr09_scene04")
	play_custom_action_do("#PLAYER#", "wr09_scene04_pl_6")
	teleport_to_slate_pos("CS_keys", -7.127, 0.0, -1.736, "slate_wr09_scene04")
	play_custom_action_do("CS_keys", "wr09_scene04_keys_6")
	teleport_to_slate_pos("CS_cellphone", -7.0, 0.0, -1.226, "slate_wr09_scene04")
	play_custom_action_do("CS_cellphone", "wr09_scene04_cell_6")
	set_far_clip(1000)
end

function shot7()
	teleport_to_slate_pos("CS_Price", -7.673, -0.125, -1.584, "slate_wr09_scene04")
	play_custom_action_do("CS_Price", "wr09_scene04_pr_7")
	teleport_to_slate_pos("#PLAYER#", -4.436, 0.073, -1.077, "slate_wr09_scene04")
	play_custom_action_do("#PLAYER#", "wr09_scene04_pl_7")
	teleport_to_slate_pos("CS_keys", -4.652, 0.0, -0.795, "slate_wr09_scene04")
	play_custom_action_do("CS_keys", "wr09_scene04_keys_7")
	teleport_to_slate_pos("CS_cellphone", -4.313, 0.0, -1.194, "slate_wr09_scene04")
	play_custom_action_do("CS_cellphone", "wr09_scene04_cell_7")
end

function shot8()
	teleport_to_slate_pos("CS_Price", -7.673, -0.125, -1.584, "slate_wr09_scene04")
	play_custom_action_do("CS_Price", "wr09_scene04_pr_8")
	teleport_to_slate_pos("#PLAYER#", -0.526, 0.297, 0.241, "slate_wr09_scene04")
	play_custom_action_do("#PLAYER#", "wr09_scene04_pl_8")
	teleport_to_slate_pos("CS_keys", -0.64, 0.0, 0.484, "slate_wr09_scene04")
	play_custom_action_do("CS_keys", "wr09_scene04_keys_8")
	teleport_to_slate_pos("CS_cellphone", -0.402, 0.0, 0.072, "slate_wr09_scene04")
	play_custom_action_do("CS_cellphone", "wr09_scene04_cell_8")
	fade_out(0.5)
	spawning_on()
end

function cutscene_abort()
	letterbox_fade_out(true)
	fade_out(0.5)
	character_show("#PLAYER#")
	time_of_day_character_shadows_enable(true)
	set_far_clip(4000)
	spawning_peds(true)
	spawning_cars(true)
	fat_bones_enable("#PLAYER#", true) 
end

function cutscene_end()
	fat_bones_enable("#PLAYER#", true) 
	character_show("#PLAYER#")
	stop_custom_actions("CS_Price")
	stop_custom_actions("#PLAYER#")
	stop_custom_actions("CS_keys")
	stop_custom_actions("CS_cellphone")
	letterbox_fade_out(true)
	fade_out(0.5)
	time_of_day_character_shadows_enable(true)
	set_far_clip(4000)
	spawning_peds(true)
	spawning_cars(true)
end
